// GENERATED by scripts/fonts/sync-fonts.ts (npm run fonts:sync) — do not edit by hand.
// Files live in public/fonts/admin/ (content-hashed names, served immutable).

export type AdminFontFace = { subset: "latin" | "latin-ext"; style: string; weight: string; unicodeRange: string; src: string };
export type AdminFontFallback = { font: string; ascent: string; descent: string; lineGap: string; sizeAdjust: string };

export const ADMIN_FONT_FACES = {
  "Barlow Condensed": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "500",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/barlow-condensed-latin-ext-normal-500.f8ec026d88.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "500",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/barlow-condensed-latin-normal-500.31ff5e6e96.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "600",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/barlow-condensed-latin-ext-normal-600.a2f92ada1d.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "600",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/barlow-condensed-latin-normal-600.5bc49d41f3.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/barlow-condensed-latin-ext-normal-700.0c1655655b.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/barlow-condensed-latin-normal-700.e3e520cb74.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "130.73%",
      "descent": "26.15%",
      "lineGap": "0.00%",
      "sizeAdjust": "76.49%"
    }
  },
  "IBM Plex Sans": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/ibm-plex-sans-latin-ext-normal-400.ae1d854fef.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/ibm-plex-sans-latin-normal-400.056e4e2459.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "500",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/ibm-plex-sans-latin-ext-normal-400.ae1d854fef.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "500",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/ibm-plex-sans-latin-normal-400.056e4e2459.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "600",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/ibm-plex-sans-latin-ext-normal-400.ae1d854fef.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "600",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/ibm-plex-sans-latin-normal-400.056e4e2459.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/ibm-plex-sans-latin-ext-normal-400.ae1d854fef.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/ibm-plex-sans-latin-normal-400.056e4e2459.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "101.32%",
      "descent": "27.18%",
      "lineGap": "0.00%",
      "sizeAdjust": "101.17%"
    }
  },
  "IBM Plex Mono": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/ibm-plex-mono-latin-ext-normal-400.f1050dc531.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/ibm-plex-mono-latin-normal-400.c36f509c0a.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "500",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/ibm-plex-mono-latin-ext-normal-500.77f03e26f9.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "500",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/ibm-plex-mono-latin-normal-500.a76f53ca66.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "76.16%",
      "descent": "20.43%",
      "lineGap": "0.00%",
      "sizeAdjust": "134.59%"
    }
  },
  "Big Shoulders Stencil": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/big-shoulders-stencil-latin-ext-normal-100-900.35743dac84.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/big-shoulders-stencil-latin-normal-100-900.c16a466351.woff2"
      }
    ],
    "fallback": null
  },
  "Public Sans": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/public-sans-latin-ext-normal-100-900.1c8a26c0ed.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/public-sans-latin-normal-100-900.c1b6da516e.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "90.59%",
      "descent": "21.46%",
      "lineGap": "0.00%",
      "sizeAdjust": "104.87%"
    }
  },
  "JetBrains Mono": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 800",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/jetbrains-mono-latin-ext-normal-100-800.7db7affbce.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 800",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/jetbrains-mono-latin-normal-100-800.1e06740a02.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "75.79%",
      "descent": "22.29%",
      "lineGap": "0.00%",
      "sizeAdjust": "134.59%"
    }
  },
  "Hanken Grotesk": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/hanken-grotesk-latin-ext-normal-100-900.a1376a5637.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/hanken-grotesk-latin-normal-100-900.1f21c6eaa0.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "99.07%",
      "descent": "30.02%",
      "lineGap": "0.00%",
      "sizeAdjust": "100.94%"
    }
  },
  "Sofia Sans Condensed": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "1 1000",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/sofia-sans-condensed-latin-ext-normal-1-1000.08f05bdfef.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "1 1000",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/sofia-sans-condensed-latin-normal-1-1000.1f21036449.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "120.13%",
      "descent": "40.04%",
      "lineGap": "0.00%",
      "sizeAdjust": "74.92%"
    }
  },
  "Geist Mono": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/admin/geist-mono-latin-ext-normal-100-900.745994b5cd.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/admin/geist-mono-latin-normal-100-900.5f3d6ad60f.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "74.67%",
      "descent": "21.92%",
      "lineGap": "0.00%",
      "sizeAdjust": "134.59%"
    }
  }
} as const satisfies Record<string, { faces: readonly AdminFontFace[]; fallback: AdminFontFallback | null }>;
