/* Screen copy for the product create / edit screens (English). */

import type { StockMovementReason } from "@/generated/prisma/enums";

export const copy = {
  crumbInventory: "Inventory",
  newTitle: "New product",
  newIntro: "Start with the basics. Photos, description and everything else follow on the next screen.",
  create: "Create product",
  creating: "Creating…",
  createdToast: "Product created.",

  saved: "Saved",
  unsaved: "Unsaved changes",
  save: "Save",
  saving: "Saving…",
  savedToast: "Product saved.",
  viewInShop: "View in shop ↗",
  viewInShopHint: "The shop is not live yet (phase 3).",
  duplicate: "Duplicate",
  duplicating: "Duplicating…",

  fields: {
    title: "Title",
    price: "Price",
    quantity: "Quantity",
    quantityHint: "Opening stock. Unique items: 1.",
    category: "Category",
    noCategory: "No category",
    description: "Description",
    descriptionHint: "Markdown: **bold**, *italic*, lists with “- ”, links as [text](url).",
    specifications: "Specifications",
    tags: "Tags",
    tagsHint: "Enter or comma adds a tag. New tags are created on save.",
    purchaseRecord: "Purchase record",
    noPurchaseRecord: "Not linked",
    notes: "Internal notes",
    notesHint: "Never shown in the shop.",
    purchasePrice: "Purchase price",
    weight: "Weight",
    sku: "SKU",
    acceptsOffers: "Accept offers",
    blurred: "Login only",
    blurredHint: "Photos blurred and details hidden for guests.",
    restrictedSymbols: "Contains restricted symbols",
    restrictedSymbolsHint: "Compliance display rules apply (e.g. §86a).",
    requiresDeactivationCert: "Deactivated weapon",
    requiresDeactivationCertHint: "Can only be put up for sale with a deactivation certificate uploaded (Provenance & authenticity).",
    ageRestricted: "18+ required",
    onSale: "On sale",
    showInArchive: "Show in sold archive",
    showInArchiveHint: "Once sold, the item stays visible in the shop's sold archive as a reference.",
    showSoldPrice: "Show sold price in archive",
    showSoldPriceHint: "Off: the archive and the item page show “Sold” without a price.",
    slug: "Slug",
    regenerateSlug: "Regenerate slug from title on save",
    seoTitle: "SEO title",
    seoTitleHint: "Defaults to the product title.",
    seoDescription: "SEO description",
    seoDescriptionHint: "About 150 characters. Defaults to the start of the description.",
  },

  cards: {
    photos: "Photos",
    photosAside: (n: number, limit: number) => `${n} of ${limit} · first = cover`,
    description: "Description",
    provenance: "Provenance",
    provenanceAside: "internal",
    status: "Status",
    priceStock: "Price & stock",
    visibility: "Visibility",
    soldArchive: "Sold archive",
    soldArchiveAside: "applies once sold",
    seo: "Search engine",
    danger: "Danger zone",
  },

  photos: {
    label: "Product photos",
    hint: (mb: number) => `JPEG, PNG, WebP or AVIF, up to ${mb} MB each. HEIC: export as JPEG first.`,
    heic: "HEIC images are not supported; export as JPEG first.",
    uploaded: (n: number) => (n === 1 ? "Photo uploaded." : `${n} photos uploaded.`),
    uploadFailed: "Upload failed",
    tooLargeForTransport: (mb: number) => `File is larger than ${mb} MB.`,
    reordered: "Photo order saved.",
    waitForUploads: "Wait for the uploads to finish before reordering.",
    altTitle: "Alt text",
    altHint: "Describe each photo for screen readers and search engines.",
    altLabel: (name: string) => `Alt text for ${name}`,
    altPlaceholder: "e.g. Left side of the helmet with decal",
    altSaved: "Alt text saved.",
    deleteTrigger: "Delete",
    deleteLabel: (name: string) => `Delete ${name}`,
    deleteTitle: "Delete this photo?",
    deleteBody: "The photo and its resized versions are removed from storage. This cannot be undone.",
    deleteConfirm: "Delete photo",
    deleted: "Photo deleted.",
    cover: "Cover",
  },

  specs: {
    label: "Label",
    value: "Value",
    add: "Add row",
    remove: (n: number) => `Remove row ${n}`,
    up: (n: number) => `Move row ${n} up`,
    down: (n: number) => `Move row ${n} down`,
    empty: "No specifications yet. Add rows such as “Maker” or “Size”.",
    labelPlaceholder: "e.g. Maker",
    valuePlaceholder: "e.g. Eisenhüttenwerke Thale",
  },

  provenance: {
    recordDetails: "Purchase details",
    openRecord: "Open purchase record →",
    supplier: "Supplier",
    purchasedAt: "Purchased",
    invoice: "Invoice",
    totalCost: "Invoice total",
    publicElsewhere: "Internal only. Public provenance text, documents and certificates are in “Provenance & authenticity”.",
  },

  status: {
    legend: "Status",
    options: { DRAFT: "Draft", ACTIVE: "For sale", SOLD: "Sold", ARCHIVED: "Archived" },
    other: "Other status",
    otherNone: "—",
    otherOptions: { RESERVED: "Reserved", STOLEN: "Stolen" },
    changed: (label: string) => `Status set to ${label}.`,
    blocked: (reason: string) => `Can’t put this up for sale: ${reason}.`,
    blockedHint: "Save a price and stock first.",
    published: "Published",
    sold: "Sold",
    notPublished: "Not yet",
    reserved: "In a cart",
    reservedUntil: "until",
    notReserved: "No",
    release: "Release",
    releaseConfirm: "Release the hold?",
    releaseYes: "Yes, release",
    releaseCancel: "Keep",
    released: "Reservation released.",
    releaseNone: "There was no active reservation.",
    wishlist: "On wishlists",
    bump: "Bump to top",
    bumped: "Moved to the top of the shop.",
  },

  stock: {
    onHand: "On hand",
    adjust: "Adjust stock",
    drawerTitle: "Adjust stock",
    drawerDescription: (code: number) => `#${code} · corrections are booked as ADJUSTMENT`,
    mode: "Change",
    modeSet: "Set quantity",
    modeDelta: "Add / remove",
    quantity: "New quantity",
    delta: "Change by",
    deltaHint: "Negative numbers remove stock, e.g. -1.",
    note: "Note",
    notePlaceholder: "Why? e.g. found in storage, damaged",
    apply: "Book adjustment",
    applying: "Booking…",
    done: (q: number) => `Stock is now ${q}.`,
    noChange: "Nothing changed.",
    history: "Movement history",
    historyEmpty: "No movements yet.",
    after: "after",
    by: "by",
    reasons: {
      PURCHASE: "Purchase",
      SALE: "Sale",
      ADJUSTMENT: "Adjustment",
      RESERVE: "Reserve",
      RELEASE: "Release",
      RETURN: "Return",
    } satisfies Record<StockMovementReason, string>,
    close: "Close",
  },

  margin: {
    label: "Margin",
    unknown: "Enter a purchase price to see the margin.",
  },

  seo: {
    preview: "Preview",
    shopNotLive: "Shop URLs follow this pattern once the shop is live.",
  },

  danger: {
    deleteTrigger: "Delete product",
    deleteTitle: "Delete this product?",
    deleteBody: (code: number) => `#${code} and its photos are removed permanently. This cannot be undone.`,
    deleteConfirm: "Delete permanently",
    deletedToast: "Product deleted.",
    cannotDelete: "Only drafts without orders or stock history can be deleted. Archive this product instead.",
    archive: "Archive instead",
    archiveTitle: "Archive this product?",
    archiveBody: "It disappears from the shop and from the default inventory view. You can restore it later.",
    archiveConfirm: "Archive",
    archived: "Product archived.",
  },

  errors: {
    generic: "Something went wrong. Try again.",
    checkFields: "Check the highlighted fields.",
    notFound: "This product no longer exists.",
    forbidden: "You don’t have access to this shop.",
    unauthenticated: "Your session has expired. Sign in again.",
    loadTitle: "This product could not be loaded",
    loadBody: "Something went wrong while loading the product. Try again, or go back to the inventory.",
    retry: "Try again",
    back: "Back to inventory",
    titleRequired: "Enter a title.",
    tooLong: (max: number) => `Use at most ${max} characters.`,
    priceInvalid: "Enter a valid price.",
    weightInvalid: "Enter the weight in whole grams.",
    quantityInvalid: "Enter a whole number of 0 or more.",
    specLabel: "Each specification needs a label.",
    deltaZero: "Enter a change other than 0.",
  },
} as const;

export const productEditPath = (id: string) => `/admin/inventory/${id}`;
