/* Screen copy for /admin/categories (categories tree + tags tab). */

const plural = (n: number, one: string, many = `${one}s`) => `${n} ${n === 1 ? one : many}`;

export const copy = {
  crumb: "Catalog",
  title: "Categories",
  tabs: { label: "Taxonomy", categories: "Categories", tags: "Tags" },
  loading: "Loading categories",
  error: {
    title: "This page could not be loaded",
    body: "Something went wrong while loading categories and tags. Try again; if it keeps happening, reload the page.",
    retry: "Try again",
  },
  categories: {
    new: "New category",
    treeLabel: "Category tree",
    emptyTitle: "No categories yet",
    emptyBody: "Categories group products in the shop menu. Start with a top level such as a period or a country.",
    inactive: "Hidden",
    products: (direct: number, total: number) =>
      total === direct ? plural(direct, "product") : `${plural(direct, "product")} · ${total} incl. subcategories`,
    edit: "Edit",
    addChild: "Add subcategory",
    addChildLabel: (title: string) => `Add a subcategory to ${title}`,
    editLabel: (title: string) => `Edit ${title}`,
    viewProducts: "Products",
    viewProductsLabel: (title: string) => `Show the products in ${title}`,
    moveUp: (title: string) => `Move ${title} up`,
    moveDown: (title: string) => `Move ${title} down`,
    summary: (n: number, products: number) => `${plural(n, "category", "categories")} · ${plural(products, "categorised product")}`,
  },
  form: {
    createTitle: "New category",
    editTitle: "Edit category",
    title: "Title",
    parent: "Parent",
    root: "None (top level)",
    slug: "Slug",
    slugHintCreate: "Leave empty to generate it from the title.",
    slugHintEdit: "Used in the shop URL. Changing it breaks old links.",
    regenerateSlug: "Generate a new slug from the title",
    active: "Visible in the shop",
    activeHint: "Hidden categories keep their products but are not shown in the shop menu.",
    description: "Description",
    seo: "Search engines",
    seoTitle: "SEO title",
    seoDescription: "SEO description",
    save: "Save category",
    create: "Create category",
    cancel: "Cancel",
    moveHint: "Changing the parent moves the category to the end of its new parent.",
  },
  delete: {
    trigger: "Delete category",
    title: (name: string) => `Delete “${name}”?`,
    emptyBody: "The category is empty and will be removed. This cannot be undone.",
    body: (products: number, children: number) =>
      `It still holds ${[products ? plural(products, "product") : null, children ? plural(children, "subcategory", "subcategories") : null]
        .filter(Boolean)
        .join(" and ")}. Choose where they move to. This cannot be undone.`,
    reassign: "Move contents to",
    confirm: "Delete category",
  },
  tags: {
    new: "New tag",
    newPlaceholder: "Tag name, e.g. Paratroopers",
    add: "Add tag",
    searchLabel: "Search tags",
    searchPlaceholder: "Search tags…",
    caption: "Tags",
    name: "Name",
    slug: "Slug",
    products: "Products",
    emptyTitle: "No tags yet",
    emptyBody: "Tags are free labels across categories, such as a unit, a maker or a theme.",
    emptySearch: "No tags match this search.",
    editLabel: (name: string) => `Edit tag ${name}`,
    bulkLabel: "Tag actions",
    selected: (n: number) => `${n} selected`,
    clear: "Clear",
    escHint: "Esc to clear",
    merge: "Merge",
    mergeTitle: (n: number) => `Merge ${plural(n, "tag")}`,
    mergeBody: "Every product with one of the selected tags gets the target tag. The other selected tags are deleted.",
    mergeTarget: "Keep this tag",
    mergeConfirm: "Merge tags",
    delete: "Delete",
    deleteTitle: (n: number) => `Delete ${plural(n, "tag")}?`,
    deleteBody: "The tags are removed from all products. This cannot be undone.",
    deleteConfirm: "Delete",
    editTitle: "Edit tag",
    description: "Description",
    regenerateSlug: "Generate a new slug from the name",
    save: "Save tag",
    deleteOne: "Delete tag",
    deleteOneTitle: (name: string) => `Delete the tag “${name}”?`,
    deleteOneBody: (n: number) => `It is removed from ${plural(n, "product")}. This cannot be undone.`,
  },
  result: {
    created: (title: string) => `Category “${title}” created.`,
    saved: "Category saved.",
    moved: "Category moved.",
    deleted: (products: number, children: number) =>
      products || children ? `Category deleted; moved ${plural(products, "product")} and ${plural(children, "subcategory", "subcategories")}.` : "Category deleted.",
    tagCreated: (name: string) => `Tag “${name}” added.`,
    tagSaved: "Tag saved.",
    tagsDeleted: (n: number) => `Deleted ${plural(n, "tag")}.`,
    merged: (deleted: number, linked: number) => `Merged ${plural(deleted, "tag")}; ${plural(linked, "product")} got the target tag.`,
    failed: "That did not work. Try again.",
    check: "Check the highlighted fields.",
    chooseTarget: "Choose the category that receives the contents.",
    chooseTag: "Choose the tag to keep.",
    nothingSelected: "Select at least one tag.",
  },
} as const;
