export const couponsCopy = {
  crumb: "Sales",
  title: "Coupons",
  add: "New coupon",
  views: { all: "All", active: "Active", scheduled: "Scheduled", ended: "Ended", inactive: "Inactive" },
  search: "Search code or description…",
  columns: { code: "Code", type: "Discount", usage: "Used", window: "Valid", status: "Status", given: "Discount given" },
  type: { PERCENT: "Percentage", FIXED: "Fixed amount", FREE_SHIPPING: "Free shipping" },
  unlimited: "∞",
  always: "Always",
  from: "From",
  until: "until",
  status: { active: "Active", scheduled: "Scheduled", ended: "Ended", inactive: "Inactive" },
  empty: { title: "No coupons yet", body: "Create a discount code customers can enter in their cart: a percentage, a fixed amount or free shipping." },
  form: {
    newTitle: "New coupon",
    editTitle: (code: string) => `Edit coupon ${code}`,
    description: "Codes are not case-sensitive. Coupons never apply to items bought at an agreed offer price.",
    code: "Code",
    codeHint: "2–40 letters, digits, - or _. Can't be changed once used.",
    note: "Internal description (optional)",
    type: "Type",
    percent: "Percentage off the subtotal",
    amount: "Amount off the subtotal",
    minSubtotal: "Minimum subtotal",
    minSubtotalHint: "0 = no minimum. Offer-priced items don't count.",
    startsAt: "Starts",
    endsAt: "Ends",
    windowHint: "Leave empty for no limit. Times are in the shop's time zone.",
    maxRedemptions: "Maximum uses in total",
    maxHint: "Empty = unlimited.",
    perEmail: "Uses per customer (email)",
    perEmailHint: "Empty = unlimited.",
    active: "Active",
    activeHint: "Inactive codes are refused at checkout.",
    save: "Save coupon",
    saved: "Coupon saved.",
    created: "Coupon created.",
  },
  deactivate: "Deactivate",
  deactivateTitle: "Deactivate this coupon?",
  deactivateBody: "Customers can no longer use the code. Orders that already used it keep their discount. You can activate it again later.",
  activate: "Activate",
  deactivated: "Coupon deactivated.",
  activated: "Coupon activated.",
  deleteLabel: "Delete",
  deleteTitle: "Delete this coupon?",
  deleteBody: "Only possible while it was never used.",
  deleted: "Coupon deleted.",
  edit: "Edit",
  redemptions: "Redemptions",
  redemptionCols: { date: "Date", order: "Order", email: "Customer", amount: "Discount", payment: "Payment", counts: "Counts" },
  noRedemptions: "Not used yet.",
  countsNo: "No — order unpaid past the retry window or canceled",
  error: { title: "Coupons could not be loaded", body: "Something went wrong while loading the coupons. Try again.", retry: "Try again" },
} as const;
