/* Screen copy for the order screens (English UI). */

export const ordersCopy = {
  crumb: "Sales",
  title: "Orders",
  boardLink: "Shipping board",
  listCaption: "Orders",
  views: {
    open: "Open",
    toShip: "To ship",
    shipped: "Shipped",
    failed: "Failed",
    archived: "Archived",
    all: "All",
  },
  search: { label: "Search orders", placeholder: "Order #, email or name…" },
  dateFilter: {
    legend: "Placed between",
    from: "From",
    to: "To",
    clear: "Clear dates",
  },
  filterChips: { search: "Search", from: "From", to: "To" },
  columns: {
    number: "Order",
    customer: "Customer",
    payment: "Payment",
    fulfillment: "Fulfillment",
    total: "Total",
    placed: "Placed",
  },
  items: (n: number) => `${n} ${n === 1 ? "item" : "items"}`,
  empty: {
    title: "No orders here",
    body: "Nothing matches this view and filters. Try another view or clear the filters.",
    noneYet: "No orders yet",
    noneYetBody: "Orders appear here as soon as a customer checks out.",
  },
  bulk: {
    archive: "Archive",
    title: (n: number) => `Archive ${n} ${n === 1 ? "order" : "orders"}?`,
    description:
      "Archived orders leave the working views but are kept with all payments and history. Orders are never deleted — you can restore them from the Archived view.",
    confirm: "Archive",
    done: (n: number) => `${n} ${n === 1 ? "order" : "orders"} archived.`,
    none: "Select at least one order.",
  },
  drawer: {
    openFull: "Open full order",
    packingSlip: "Packing slip",
    placed: "Placed",
    customer: "Customer",
    items: "Items",
    payment: "Payment",
    shipTo: "Ship to",
    pickup: "Pickup in store",
    notFound: "This order no longer exists or belongs to another shop.",
  },
  notFound: "Order not found. It may belong to another shop.",
  error: {
    title: "Orders couldn't be loaded",
    body: "Something went wrong while loading orders. Try again; if it keeps happening, check the server log.",
    retry: "Try again",
  },
};

export const orderCopy = {
  crumb: "Orders",
  title: (n: number) => `Order #${n}`,
  steps: "Order progress",
  stopped: "Stopped",
  archivedBanner: "This order is archived. It is hidden from the working views but kept with all its history.",
  oversold: {
    title: "Oversold — needs follow-up",
    body: "The customer paid, but there was less stock than ordered. Refund the difference or source another item.",
    line: (title: string, ordered: number, available: number) => `${title}: ordered ${ordered}, ${available} in stock`,
  },
  lines: {
    title: "Items",
    aside: "Prices fixed at checkout",
    caption: "Order lines",
    product: "Product",
    stockCode: "Stock code",
    qty: "Qty",
    unit: "Price",
    total: "Total",
    reconstructed: "Reconstructed price",
    reconstructedHint: "Imported from the old shop, which stored rounded euros. The exact price may differ by a few cents.",
    productGone: "product deleted",
  },
  totals: {
    subtotal: "Subtotal",
    discount: "Discount",
    offer: "Accepted offer",
    viewOffer: "View offer →",
    shipping: "Shipping",
    surcharge: "Payment surcharge",
    vat: "VAT (margin scheme)",
    vatValue: "n/a",
    total: "Total",
  },
  customer: {
    title: "Customer",
    guest: "Guest",
    registered: "Registered",
    nth: (n: number) => `${n} ${n === 1 ? "order" : "orders"}`,
    open: "View customer",
    noProfile: "No customer profile linked.",
    note: "Customer note",
  },
  addresses: {
    shipping: "Shipping address",
    billing: "Billing address",
    sameAsShipping: "Same as shipping",
    none: "No address",
    pickup: "Pickup in store",
  },
  payments: {
    title: "Payments",
    caption: "Payment attempts",
    provider: "Provider",
    method: "Method",
    status: "Status",
    amount: "Amount",
    reference: "Reference",
    date: "Date",
    none: "No payment attempts yet.",
    manual: "Manual",
    mollie: "Mollie",
  },
  timeline: { title: "Timeline", empty: "No events yet.", system: "system" },
  actions: {
    markPaid: "Mark as paid",
    markPaidTitle: "Mark this order as paid?",
    markPaidBody:
      "Use this for a bank transfer or cash payment you received yourself. It records a manual payment, books out the stock and queues the confirmation mail. This can't be undone here.",
    markPaidNote: "Note (optional)",
    markPaidNoteHint: "E.g. bank reference or “paid in cash at the fair”.",
    markPaidConfirm: "Mark as paid",
    markPaidDone: "Order marked as paid.",
    markPaidOversold: "Order marked as paid — but some items were oversold. See the warning on the order.",
    cancel: "Cancel order",
    cancelTitle: "Cancel this order?",
    cancelBody: "The order is set to canceled and its reserved items go back on sale. The order itself is kept.",
    cancelReason: "Reason (optional)",
    cancelConfirm: "Cancel order",
    cancelDone: "Order canceled.",
    archive: "Archive",
    archiveTitle: "Archive this order?",
    archiveBody: "It leaves the working views but is kept with all payments and history. You can restore it at any time.",
    archiveDone: "Order archived.",
    unarchive: "Restore",
    unarchiveTitle: "Restore this order?",
    unarchiveBody: "It returns to the working views.",
    unarchiveDone: "Order restored.",
    packingSlip: "Packing slip",
    invoice: "Invoice",
    more: "More actions",
  },
  note: {
    title: "Add note",
    label: "Internal note",
    hint: "Only visible to staff. Added to the timeline.",
    submit: "Add note",
    done: "Note added.",
    required: "Write a note first.",
  },
  fulfillment: {
    title: "Fulfillment",
    status: "Status",
    carrier: "Carrier",
    carrierPlaceholder: "PostNL, DHL, bpost…",
    trackingNumber: "Tracking code",
    trackingUrl: "Tracking link",
    trackingUrlHint: "Full https:// link to the carrier's tracking page.",
    submit: "Save fulfillment",
    done: "Fulfillment updated.",
    unpaid: "The order must be paid before it can be packed or shipped.",
    shippedAt: "Shipped",
    deliveredAt: "Delivered",
    trackLink: "Track parcel",
  },
  notFound: "This order no longer exists or belongs to another shop.",
};
