/* Sourcing screens copy (English). */

export const copy = {
  crumb: "Catalog",
  title: "Sourcing & provenance",
  tabs: {
    label: "Sourcing sections",
    records: "Purchase records",
    suppliers: "Suppliers",
    margin: "Margin report",
  },
  records: {
    caption: "Purchase records",
    new: "+ New purchase record",
    search: "Search invoice, notes or supplier…",
    supplierFilter: "Supplier",
    anySupplier: "All",
    date: "Date",
    supplier: "Supplier",
    invoice: "Invoice",
    products: "Products",
    totalCost: "Total cost",
    allocated: "Allocated",
    unallocated: "Unallocated",
    noSupplier: "No supplier",
    noTotal: "No total",
    balanced: "Fully allocated",
    empty: "No purchase records yet",
    emptyBody: "Record a purchase (an invoice or a lot), link the items you bought, and split the cost to see real margins.",
    emptyFiltered: "No purchase records match these filters",
    emptyFilteredBody: "Try another search or clear the filters.",
  },
  form: {
    newTitle: "New purchase record",
    editTitle: "Edit purchase record",
    newDescription: "One invoice or lot. You can link products after saving.",
    purchasedAt: "Purchase date",
    supplier: "Supplier",
    noSupplier: "— No supplier —",
    supplierHint: "Add suppliers on the Suppliers tab.",
    invoiceNumber: "Invoice number",
    totalCost: "Total cost",
    totalCostHint: "As invoiced, incl. costs you want to spread over the items. Leave empty if unknown.",
    notes: "Notes",
    create: "Create record",
    save: "Save changes",
    cancel: "Cancel",
    created: "Purchase record created.",
    saved: "Purchase record saved.",
    checkFields: "Check the highlighted fields.",
    dateRequired: "Enter the purchase date.",
  },
  detail: {
    crumb: "Sourcing",
    titleFallback: "Purchase record",
    edit: "Edit",
    delete: "Delete",
    deleteTitle: "Delete this purchase record?",
    deleteBody: "The linked products are unlinked but keep their purchase prices. This cannot be undone.",
    deleted: "Purchase record deleted.",
    summary: "Summary",
    notes: "Notes",
    products: "Linked products",
    productsCount: (n: number) => `${n} ${n === 1 ? "product" : "products"}`,
    link: "+ Link products",
    allocate: "Allocate cost",
    allocateTitle: "Split the total cost over the linked products?",
    allocateBody: "This overwrites the purchase price of every linked product. Sold lines without a cost get the new price too.",
    allocateMethod: "Split method",
    equal: "Equally",
    equalHint: "Every product gets the same share.",
    byPrice: "By selling price",
    byPriceHint: "Expensive items carry more of the cost.",
    allocateConfirm: "Allocate",
    allocated: (n: number) => `Cost allocated over ${n} ${n === 1 ? "product" : "products"}.`,
    needTotal: "Enter a total cost on the record first.",
    needProducts: "Link products first.",
    empty: "No products linked yet",
    emptyBody: "Link the items that came with this purchase to track their cost and margin.",
    stockCode: "No.",
    product: "Product",
    status: "Status",
    price: "Price",
    purchasePrice: "Purchase price",
    margin: "Margin",
    unlink: "Unlink",
    unlinkLabel: (title: string) => `Unlink ${title}`,
    unlinked: "Product unlinked.",
    savePrices: "Save purchase prices",
    savingPrices: "Saving…",
    pricesSaved: (n: number, backfilled: number) =>
      `${n} purchase ${n === 1 ? "price" : "prices"} saved${backfilled ? `, ${backfilled} sold ${backfilled === 1 ? "line" : "lines"} updated` : ""}.`,
    unsaved: (n: number) => `${n} unsaved ${n === 1 ? "change" : "changes"}`,
    priceLabel: (title: string) => `Purchase price for ${title}`,
    totals: "Total",
    remaining: "Unallocated",
    overAllocated: "Over-allocated",
  },
  picker: {
    title: "Link products",
    description: "Search the inventory and pick the items that belong to this purchase.",
    search: "Search title, SKU or number",
    placeholder: "e.g. helmet or 50231",
    results: "Search results",
    none: "No products found.",
    hint: "Type at least 2 characters.",
    selected: (n: number) => `${n} selected`,
    linkSelected: (n: number) => (n ? `Link ${n} ${n === 1 ? "product" : "products"}` : "Link products"),
    alreadyLinked: "Already linked",
    linked: (n: number) => `${n} ${n === 1 ? "product" : "products"} linked.`,
    linkedElsewhereNote: "A product can belong to one purchase record; linking moves it here.",
    searchFailed: "Search failed. Try again.",
  },
  suppliers: {
    caption: "Suppliers",
    new: "+ New supplier",
    search: "Search suppliers…",
    name: "Name",
    contact: "Contact",
    contactHint: "Person, email or phone.",
    notes: "Notes",
    records: "Purchase records",
    edit: "Edit",
    editLabel: (name: string) => `Edit ${name}`,
    delete: "Delete",
    deleteTitle: (name: string) => `Delete ${name}?`,
    deleteBody: "The supplier is removed permanently.",
    deleteBlocked: "Suppliers with purchase records cannot be deleted.",
    deleted: "Supplier deleted.",
    newTitle: "New supplier",
    editTitle: "Edit supplier",
    create: "Create supplier",
    save: "Save changes",
    created: "Supplier created.",
    saved: "Supplier saved.",
    duplicate: "A supplier with this name already exists.",
    nameRequired: "Enter a name.",
    inUse: "This supplier still has purchase records.",
    empty: "No suppliers yet",
    emptyBody: "Add the dealers, auctions and private sellers you buy from.",
    emptyFiltered: "No suppliers match your search",
    viewRecords: "View records",
  },
  margin: {
    title: "Margin report",
    from: "From",
    to: "To",
    groupBy: "Group by",
    groups: { category: "Category", supplier: "Supplier", month: "Month" },
    apply: "Update report",
    caption: (from: string, to: string) => `Margin from ${from} to ${to}`,
    revenue: "Revenue",
    cost: "Cost",
    margin: "Margin",
    marginPct: "Margin %",
    lines: "Lines",
    missing: "Missing cost",
    total: "Total",
    noCost: "—",
    empty: "No paid sales in this period",
    emptyBody: "Pick a wider date range.",
    missingHint: (n: number) =>
      `${n} sold ${n === 1 ? "line has" : "lines have"} no purchase price, so ${n === 1 ? "it is" : "they are"} left out of cost and margin.`,
    missingAction: "Fill purchase prices on the purchase records",
    explain:
      "Paid orders only, by payment date, excl. shipping. Margin % is computed over lines that have a purchase price.",
    invalidRange: "The end date must be on or after the start date.",
  },
  errors: {
    loadTitle: "Sourcing could not be loaded",
    loadBody: "Something went wrong while fetching the data. Try again in a moment.",
    retry: "Try again",
  },
} as const;
