export const redirectsCopy = {
  crumb: "Website",
  title: "Redirects",
  add: "New redirect",
  views: { all: "All", MANUAL: "Manual", LEGACY: "Imported" },
  search: "Search old or new path…",
  intro:
    "Send visitors and search engines from an old URL to a new page. A redirect only applies when the old URL doesn't exist (anymore): it never overrides a live page.",
  columns: { from: "Old path", to: "Redirects to", status: "Type", source: "Source", hits: "Hits", lastHit: "Last hit", created: "Added" },
  status: { 301: "Permanent", 302: "Temporary" },
  source: { MANUAL: "Manual", LEGACY: "Imported" },
  never: "Never",
  empty: { title: "No redirects", body: "Add a redirect when you rename or remove a page, category or product URL." },
  emptyFiltered: { title: "No matching redirects", body: "Try another search or filter." },
  form: {
    newTitle: "New redirect",
    editTitle: "Edit redirect",
    description: "The old path is matched case-insensitively, with or without a trailing slash.",
    from: "Old path",
    fromHint: "E.g. /old-page or /shop.php?code=123. A full URL of the old shop also works.",
    to: "Redirect to",
    toHint: "A path in this shop (/shop/category/medals) or a URL on one of the shop's own domains.",
    type: "Type",
    permanent: "Permanent (301)",
    temporary: "Temporary (302)",
    typeHint: "Use permanent unless the old URL will come back. Search engines move rankings only for permanent redirects.",
    save: "Save redirect",
    saved: "Redirect saved.",
    created: "Redirect added.",
  },
  edit: "Edit",
  test: "Test",
  testLabel: (path: string) => `Open ${path} in the shop`,
  deleteLabel: "Delete",
  deleteTitle: "Delete this redirect?",
  deleteBody: (from: string) => `${from} will show the "page not found" page again.`,
  deleted: "Redirect deleted.",
  legacyHint: "Imported from the old shop — can be deleted, not edited.",
  export: "Export CSV",
  import: {
    trigger: "Import CSV",
    title: "Import redirects",
    description: "One redirect per line: old path, new path and optionally 301 or 302. A header line is skipped. Existing redirects for the same old path are replaced.",
    file: "CSV file",
    paste: "Or paste lines",
    pasteHint: "/old-page,/pages/new-page,301",
    submit: "Import",
    nothing: "Choose a file or paste some lines.",
    done: (created: number, updated: number) => `Imported: ${created} added, ${updated} replaced.`,
    errors: (n: number) => `${n} ${n === 1 ? "line was" : "lines were"} skipped:`,
    line: (n: number) => `Line ${n}`,
  },
  error: { title: "Redirects could not be loaded", body: "Something went wrong while loading the redirects. Try again.", retry: "Try again" },
} as const;
