import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { offerCopy } from "./_copy";

export const offerCopyDe: CopyShape<typeof offerCopy> = {
  button: "Preisvorschlag machen",
  dialogTitle: "Preisvorschlag machen",
  intro: (price: string, min: string) =>
    `Angeboten für ${price}. Preisvorschläge ab ${min} werden berücksichtigt; wir antworten in der Regel innerhalb von 72 Stunden.`,
  name: "Ihr Name",
  email: "E-Mail-Adresse",
  amount: "Ihr Preisvorschlag",
  message: "Nachricht (optional)",
  submit: "Preisvorschlag senden",
  sending: "Wird gesendet…",
  cancel: "Abbrechen",
  close: "Schließen",
  sent: "Vielen Dank! Wir haben Ihren Preisvorschlag erhalten und Ihnen eine Bestätigung per E-Mail gesendet.",
  stillForSale: "Das Stück bleibt zum Verkauf, bis wir einen Preisvorschlag annehmen.",
  invalidAmount: "Geben Sie einen Betrag wie 85 oder 85,50 ein",
  error: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
  checkoutTitle: "Ihr vereinbarter Preis",
  checkoutMeta: "Ihr Preisvorschlag",
  agreed: "Vereinbarter Preis",
  listPrice: "Listenpreis",
  validUntil: (d: string) => `Dieser persönliche Preis gilt bis ${d}.`,
  buyNow: "Jetzt kaufen",
  buying: "Wird in den Warenkorb gelegt…",
  private: "Halten Sie diesen Link privat: Jeder mit diesem Link kann zu Ihrem Preis kaufen.",
  expired: "Dieser persönliche Preis ist abgelaufen. Kontaktieren Sie uns, wenn Sie weiterhin interessiert sind.",
  used: "Sie haben dieses Stück bereits zu Ihrem vereinbarten Preis bestellt.",
  sold: "Leider ist dieses Stück nicht mehr verfügbar.",
  closed: "Dieses Angebot ist nicht mehr gültig.",
  notFound: "Dieser Link ist ungültig. Möglicherweise wurde er durch einen neueren Link in einer späteren E-Mail ersetzt.",
  viewShop: "Zum Shop",
  counterTitle: "Unser Gegenangebot",
  yourOffer: "Ihr Preisvorschlag",
  ourProposal: "Unser Vorschlag",
  counterValid: (d: string) => `Gültig bis ${d}.`,
  accept: (amount: string) => `${amount} annehmen`,
  decline: "Nein, danke",
  declined: "Danke für Ihre Rückmeldung. Ihr Preisvorschlag wurde zurückgezogen.",
  counterExpired: "Dieses Gegenangebot ist abgelaufen.",
  counterAccepted: "Sie haben dieses Gegenangebot bereits angenommen — Ihren persönlichen Bestelllink finden Sie in Ihrer E-Mail.",
  counterClosed: "Dieses Gegenangebot ist nicht mehr offen.",
  errors: {
    checkFields: "Bitte prüfen Sie die markierten Felder",
    name: "Bitte geben Sie Ihren Namen ein",
    amount: "Bitte geben Sie einen Betrag ein",
    severalOffers: "Sie haben in letzter Zeit mehrere Preisvorschläge gemacht. Bitte versuchen Sie es später erneut.",
    notAllowed: "Für dieses Stück sind keine Preisvorschläge möglich",
    inSomeonesCart: "Jemand hat dieses Stück gerade im Warenkorb. Bitte versuchen Sie es später erneut.",
    atOrAbovePrice: "Ihr Preisvorschlag liegt beim oder über dem Preis — Sie können das Stück einfach kaufen",
    lowest: (amount: string) => `Der niedrigste Preisvorschlag, den wir berücksichtigen können, beträgt ${amount}`,
    duplicate: "Sie haben für dieses Stück bereits einen offenen Preisvorschlag. Wir melden uns in Kürze.",
    captcha: "Wir konnten nicht bestätigen, dass Sie ein Mensch sind. Bitte versuchen Sie es erneut.",
    offerLinkInvalid: "Dieser Link ist nicht mehr gültig",
    linkInvalid: "Dieser Link ist nicht mehr gültig",
    unknownChoice: "Unbekannte Auswahl",
    counterAnswered: "Auf dieses Gegenangebot wurde bereits geantwortet",
    counterExpired: "Dieses Gegenangebot ist abgelaufen",
    soldMeantime: "Leider wurde dieses Stück inzwischen verkauft",
  },
};
