import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { offerCopy } from "./_copy";

export const offerCopyNl: CopyShape<typeof offerCopy> = {
  button: "Doe een bod",
  dialogTitle: "Doe een bod",
  intro: (price: string, min: string) => `Vraagprijs ${price}. Biedingen vanaf ${min} nemen we in overweging; meestal reageren we binnen 72 uur.`,
  name: "Uw naam",
  email: "E-mailadres",
  amount: "Uw bod",
  message: "Bericht (optioneel)",
  submit: "Bod versturen",
  sending: "Versturen…",
  cancel: "Annuleren",
  close: "Sluiten",
  sent: "Hartelijk dank! We hebben uw bod ontvangen en een bevestiging naar uw e-mailadres gestuurd.",
  stillForSale: "Het stuk blijft te koop totdat we een bod accepteren.",
  invalidAmount: "Vul een bedrag in, bijvoorbeeld 85 of 85,50",
  error: "Er ging iets mis. Probeer het opnieuw.",
  checkoutTitle: "Uw afgesproken prijs",
  checkoutMeta: "Uw bod",
  agreed: "Afgesproken prijs",
  listPrice: "Vraagprijs",
  validUntil: (d: string) => `Deze persoonlijke prijs is geldig tot ${d}.`,
  buyNow: "Nu kopen",
  buying: "Toevoegen aan winkelwagen…",
  private: "Houd deze link privé: iedereen met deze link kan voor uw prijs kopen.",
  expired: "Deze persoonlijke prijs is verlopen. Neem contact met ons op als u nog interesse heeft.",
  used: "U heeft dit stuk al besteld voor uw afgesproken prijs.",
  sold: "Helaas — dit stuk is niet meer beschikbaar.",
  closed: "Dit bod is niet meer geldig.",
  notFound: "Deze link is niet geldig. Mogelijk is hij vervangen door een nieuwere link in een latere e-mail.",
  viewShop: "Bekijk de winkel",
  counterTitle: "Ons tegenbod",
  yourOffer: "Uw bod",
  ourProposal: "Ons voorstel",
  counterValid: (d: string) => `Geldig tot ${d}.`,
  accept: (amount: string) => `${amount} accepteren`,
  decline: "Nee, bedankt",
  declined: "Bedankt voor uw reactie. Uw bod is ingetrokken.",
  counterExpired: "Dit tegenbod is verlopen.",
  counterAccepted: "U heeft dit tegenbod al geaccepteerd — in uw e-mail vindt u uw persoonlijke link om af te rekenen.",
  counterClosed: "Dit tegenbod staat niet meer open.",
  errors: {
    checkFields: "Controleer de gemarkeerde velden",
    name: "Vul uw naam in",
    amount: "Vul een bedrag in",
    severalOffers: "U heeft onlangs meerdere biedingen gedaan. Probeer het later opnieuw.",
    notAllowed: "Op dit stuk kan niet worden geboden",
    inSomeonesCart: "Iemand heeft dit stuk op dit moment in de winkelwagen. Probeer het later opnieuw.",
    atOrAbovePrice: "Uw bod is gelijk aan of hoger dan de prijs — u kunt het stuk gewoon kopen",
    lowest: (amount: string) => `Het laagste bod dat we in overweging kunnen nemen is ${amount}`,
    duplicate: "U heeft al een openstaand bod op dit stuk. We nemen spoedig contact met u op.",
    captcha: "We konden niet vaststellen dat u een mens bent. Probeer het opnieuw.",
    offerLinkInvalid: "Deze link is niet meer geldig",
    linkInvalid: "Deze link is niet meer geldig",
    unknownChoice: "Onbekende keuze",
    counterAnswered: "Op dit tegenbod is al gereageerd",
    counterExpired: "Dit tegenbod is verlopen",
    soldMeantime: "Helaas — dit stuk is inmiddels verkocht",
  },
};
