/** English copy for the offer flow (multi-language later). */
export const offerCopy = {
  button: "Make an offer",
  dialogTitle: "Make an offer",
  intro: (price: string, min: string) => `Listed at ${price}. Offers from ${min} are considered; we usually answer within 72 hours.`,
  name: "Your name",
  email: "Email address",
  amount: "Your offer",
  message: "Message (optional)",
  submit: "Send offer",
  sending: "Sending…",
  cancel: "Cancel",
  close: "Close",
  sent: "Thank you! We received your offer and sent a confirmation to your email.",
  stillForSale: "The item stays for sale until we accept an offer.",
  invalidAmount: "Enter an amount like 85 or 85.50",
  error: "Something went wrong. Please try again.",
  // /offer/<token>
  checkoutTitle: "Your agreed price",
  checkoutMeta: "Your offer",
  agreed: "Agreed price",
  listPrice: "List price",
  validUntil: (d: string) => `This personal price is valid until ${d}.`,
  buyNow: "Buy now",
  buying: "Adding to cart…",
  private: "Keep this link private: anyone with it can buy at your price.",
  expired: "This personal price has expired. Contact us if you are still interested.",
  used: "You already ordered this item with your agreed price.",
  sold: "Sorry — this item is no longer available.",
  closed: "This offer is no longer valid.",
  notFound: "This offer link is not valid. It may have been replaced by a newer link in a later email.",
  viewShop: "Browse the shop",
  // /offer/counter/<token>
  counterTitle: "Our counter offer",
  yourOffer: "Your offer",
  ourProposal: "Our proposal",
  counterValid: (d: string) => `Valid until ${d}.`,
  accept: (amount: string) => `Accept ${amount}`,
  decline: "No thanks",
  declined: "Thanks for letting us know. Your offer has been withdrawn.",
  counterExpired: "This counter offer has expired.",
  counterAccepted: "You already accepted this counter offer — check your email for your personal checkout link.",
  counterClosed: "This counter offer is no longer open.",
} as const;
