/* Copy for the product import (Inventory → Import and the setup wizard). English; move to the i18n dictionary later. */

export const importCopy = {
  title: "Import products",
  crumbInventory: "Inventory",
  intro: "Import your existing catalogue. Nothing is published until you check the preview — imported items start as drafts unless you choose otherwise.",
  sourceLegend: "Import source",
  sources: {
    WOOCOMMERCE: { label: "WooCommerce", hint: "Products → Export → CSV. Photos are downloaded from your site." },
    SHOPIFY: { label: "Shopify", hint: "Products → Export → CSV for Excel or plain CSV. Photos from Shopify's CDN." },
  },
  file: {
    label: "Export file (CSV)",
    hint: (mb: number) => `The CSV file from the export, up to ${mb} MB.`,
    upload: "Upload and preview",
    uploading: "Reading file…",
    required: "Choose a CSV file first.",
    tooLarge: (mb: number) => `The file is larger than ${mb} MB.`,
    failed: "The file could not be uploaded. Try again.",
  },
  preview: {
    label: "Import preview",
    rowsRead: (n: number) => `${n} row${n === 1 ? "" : "s"} read`,
    another: "Choose another file",
    productsReady: "products ready",
    photos: "photos to download",
    categories: "categories mapped",
    categoriesNote: (existing: number, created: number) => `${existing} existing · ${created} new`,
    attention: "need attention",
    column: "CSV column",
    becomes: "Becomes",
    example: "Example",
    tagsFacets: "Facets (period / country …)",
    tagsPlain: "Plain tags",
    tagsHint: (matched: number, total: number) => `${matched} of ${total} tags match an existing facet value; the rest become plain tags.`,
    stockSplit: "Split into unique items",
    stockSingle: "Keep 1 item per product",
    stockHint: (n: number) => `${n} product${n === 1 ? " has" : "s have"} stock > 1 → split or keep 1`,
    uniqueItem: "Unique item (1)",
    publish: "Publish imported products immediately (otherwise they start as drafts)",
    publishHint: (n: number) => `${n} item${n === 1 ? "" : "s"} can go live: published in the old shop, priced and in stock. Variants and items without price or stock always start as drafts.`,
    images: "Download photos",
    imagesHint: "Photos are fetched in the background after the products are created.",
    facetMatches: "Tags matched to facets",
    warnings: (n: number) => `Warnings (${n})`,
    skipped: (n: number) => `Skipped rows (${n})`,
    ignored: (n: number) => `Columns not imported (${n})`,
    notes: "About this file",
    row: (n: number) => (n > 0 ? `Row ${n}` : "File"),
    more: (n: number) => `…and ${n} more`,
    skuConflicts: (n: number) => `${n} SKU${n === 1 ? " is" : "s are"} already used by other products — those items are imported without SKU.`,
    sample: "First products",
    start: (n: number) => `Import ${n} product${n === 1 ? "" : "s"} →`,
    starting: "Starting…",
  },
  progress: {
    label: "Import progress",
    products: "Creating products",
    images: "Downloading photos",
    of: (a: number, b: number) => `${a} of ${b}`,
    cancel: "Cancel import",
    canceling: "Canceling…",
    waiting: "Waiting for the background worker…",
    status: {
      UPLOADED: "Ready to import",
      RUNNING: "Creating products…",
      IMAGES: "Downloading photos…",
      DONE: "Import finished",
      FAILED: "Import failed",
      CANCELED: "Import canceled",
    },
  },
  result: {
    created: "items created",
    published: "published",
    drafts: "drafts",
    failed: "rows failed",
    photos: "photos added",
    photosFailed: "photos failed",
    existing: (n: number) => `${n} item${n === 1 ? "" : "s"} already existed from an earlier run and were not created again.`,
    view: "View imported products",
    another: "Import another file",
    retry: "Retry import",
    undo: "Delete imported drafts",
    undoTitle: "Delete the imported drafts?",
    undoBody: "Every item of this import that is still a draft is deleted, with its photos. Published or sold items are kept.",
    undoConfirm: "Delete drafts",
    undone: (deleted: number, kept: number) => `${deleted} draft${deleted === 1 ? "" : "s"} deleted${kept ? `, ${kept} kept` : ""}.`,
    failures: (n: number) => `Rows that failed (${n})`,
    imageFailures: (n: number) => `Photos that failed (${n})`,
    error: "What went wrong",
  },
  history: {
    title: "Recent imports",
    empty: "No imports yet.",
    open: "Open",
    columns: { date: "Date", file: "File", source: "Source", status: "Status", items: "Items" },
  },
  errors: {
    generic: "Something went wrong. Try again.",
    unauthenticated: "Your session has expired. Sign in again.",
    forbidden: "You do not have access to this shop.",
  },
};
