import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { cartCopy } from "./_copy";

export const cartCopyDe: CopyShape<typeof cartCopy> = {
  add: {
    add: "In den Warenkorb",
    adding: "Wird hinzugefügt…",
    added: "Zum Warenkorb hinzugefügt",
    inCart: "In Ihrem Warenkorb",
    viewCart: "Warenkorb ansehen",
    checkout: "Zur Kasse",
    unavailable: "Nicht verfügbar",
    reservedFor: "Für Sie reserviert",
    error: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
    rateLimited: "Zu viele Versuche. Bitte warten Sie einen Moment.",
    login: "Zum Kaufen anmelden",
  },
  countdown: {
    reservedFor: "Für Sie reserviert",
    expired: "Reservierung abgelaufen",
    srLabel: (mins: number) => `Noch etwa ${mins} ${mins === 1 ? "Minute" : "Minuten"} für Sie reserviert`,
  },
  cart: {
    title: "Ihr Warenkorb",
    metaTitle: "Warenkorb",
    emptyTitle: "Ihr Warenkorb ist leer",
    emptyText: "Jedes Stück ist ein Unikat — sobald Sie etwas hinzufügen, halten wir es einige Minuten für Sie zurück.",
    browse: "Zum Shop",
    remove: "Entfernen",
    removing: "Wird entfernt…",
    removeLabel: (title: string) => `${title} aus dem Warenkorb entfernen`,
    lapsed: "Nicht mehr reserviert",
    lapsedHint: "Es ist noch verfügbar — reservieren Sie es erneut.",
    reAdd: "Erneut hinzufügen",
    taken: "Jemand anderes hat dieses Stück im Warenkorb",
    takenHint: (mins: number) => `Es ist möglicherweise in etwa ${mins} Min. wieder verfügbar.`,
    unavailable: "Nicht mehr verfügbar",
    removeUnavailable: "Nicht verfügbare Stücke entfernen",
    subtotal: "Zwischensumme",
    shippingEstimate: "Voraussichtliche Versandkosten",
    shipTo: "Versand nach",
    calculating: "Wird berechnet…",
    pickupOnly: "Nur Abholung",
    free: "Kostenlos",
    from: "ab",
    noCountry: "Wählen Sie Ihr Land, um die Versandkosten zu sehen.",
    freeShippingProgress: (amount: string) => `Noch ${amount} bis zum kostenlosen Versand`,
    freeShippingReached: "Ihre Bestellung wird kostenlos versendet",
    minimumOrder: (amount: string) => `Mindestbestellwert nicht erreicht — es fehlen noch ${amount}`,
    checkout: "Zur Kasse",
    continueShopping: "Weiter einkaufen",
    uniqueNote: "Alle Stücke sind Unikate. Ihre Reservierung hält sie aus anderen Warenkörben fern, während Sie bestellen.",
    totalNote: "Inkl. MwSt., soweit anwendbar. Die endgültigen Versandkosten werden an der Kasse anhand Ihrer Adresse berechnet.",
    itemCount: (n: number) => (n === 1 ? "1 Stück" : `${n.toLocaleString("de-DE")} Stück`),
  },
  checkout: {
    title: "Kasse",
    notShippable: (country: string) => `Kann nicht nach ${country} versendet werden — entfernen Sie es oder wählen Sie Abholung.`,
    metaTitle: "Kasse",
    contact: "Kontakt",
    email: "E-Mail-Adresse",
    phone: "Telefon",
    phoneHint: "Nur für Rückfragen zur Lieferung.",
    loggedInAs: (email: string) => `Angemeldet als ${email}`,
    shippingAddress: "Lieferadresse",
    billingAddress: "Rechnungsadresse",
    billingSame: "Rechnungsadresse entspricht der Lieferadresse",
    firstName: "Vorname",
    lastName: "Nachname",
    company: "Firma (optional)",
    street: "Straße",
    houseNumber: "Nr.",
    line2: "Adresszusatz, Wohnung usw. (optional)",
    postalCode: "Postleitzahl",
    city: "Ort",
    region: "Bundesland / Region (optional)",
    country: "Land",
    chooseCountry: "Land wählen…",
    shippingMethod: "Versand",
    noOptions: "Wählen Sie Ihr Land, um die Versandoptionen zu sehen.",
    pickup: "Abholung",
    insurance: (price: string) => `Diese Sendung versichern (+${price})`,
    insuranceUpTo: (amount: string) => `versichert bis ${amount}`,
    payment: "Zahlungsart",
    paymentHostedChoice: "Die Zahlungsart wählen Sie auf der sicheren Zahlungsseite von Mollie.",
    paymentsNotConfigured: "Zahlungen sind für diesen Shop noch nicht eingerichtet.",
    paymentsNotConfiguredDev:
      "Zahlungen sind nicht eingerichtet. Entwicklungsmodus: Ihre Bestellung wird angelegt und Sie können die Zahlung auf der Bestellseite simulieren.",
    paymentsTestMode: "Testmodus — es wird kein echtes Geld abgebucht.",
    note: "Anmerkung für den Verkäufer (optional)",
    terms: "Ich akzeptiere die",
    termsLink: "Allgemeinen Geschäftsbedingungen",
    newsletter: "Ich möchte über Neuzugänge informiert werden (Newsletter)",
    ageConfirm: (age: number) => `Ich bestätige, dass ich mindestens ${age} Jahre alt bin`,
    ageHint: "Ihr Warenkorb enthält Stücke mit Altersbeschränkung.",
    loginRequiredSensitive:
      "Ihr Warenkorb enthält Stücke, die nur an registrierte Kunden verkauft werden. Bitte melden Sie sich an oder erstellen Sie ein Kundenkonto, um fortzufahren.",
    loginRequiredGuestOff: "Für Bestellungen in diesem Shop ist ein Kundenkonto erforderlich. Bitte melden Sie sich an oder erstellen Sie ein Kundenkonto.",
    login: "Anmelden",
    register: "Kundenkonto erstellen",
    haveAccount: "Sie haben ein Kundenkonto?",
    loginToSave: "Anmelden und schneller bestellen",
    summary: "Bestellübersicht",
    subtotal: "Zwischensumme",
    shipping: "Versand",
    insuranceLine: "Versicherung",
    surchargeLine: "Zahlungsartzuschlag",
    methodSurcharge: (label: string, rule: string) => `${label}: +${rule}`,
    total: "Gesamtsumme",
    placeOrder: "Zahlungspflichtig bestellen",
    placeOrderDev: "Bestellung aufgeben",
    placing: "Bestellung wird aufgegeben…",
    viewOrder: "Bestellung aufgegeben — Bestellung ansehen",
    secure: "Sie werden zur sicheren Zahlung zu Mollie weitergeleitet.",
    edit: "Warenkorb bearbeiten",
    emptyTitle: "Nichts zu bestellen",
    emptyText: "Ihr Warenkorb ist leer oder keines der Stücke kann derzeit gekauft werden.",
    backToCart: "Zurück zum Warenkorb",
    blocked: "Einige Stücke können derzeit nicht bestellt werden. Entfernen Sie sie aus Ihrem Warenkorb, um fortzufahren.",
    reReserve: "Erneut reservieren",
    holdNote: "Wir halten Ihre Stücke zurück, während Sie bestellen.",
    fixErrors: "Bitte prüfen Sie die markierten Felder.",
    unexpected: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
    rateLimited: "Zu viele Versuche. Bitte warten Sie einige Minuten und versuchen Sie es erneut.",
    currencyNote: (currency: string) => `Sie bezahlen in ${currency}.`,
    surchargeMax: (amount: string) => `max. ${amount}`,
  },
  coupon: {
    label: "Gutscheincode",
    placeholder: "Code eingeben",
    apply: "Einlösen",
    applying: "Wird eingelöst…",
    remove: "Entfernen",
    discount: "Rabatt",
    freeShipping: "Kostenloser Versand",
    applied: (code: string) => `Code ${code} eingelöst`,
    notApplied: (code: string, message: string) => `Code ${code}: ${message}`,
    offerNote: "Gutscheincodes gelten nicht für Stücke, die zu einem vereinbarten Preis aus einem Preisvorschlag gekauft werden.",
    rateLimited: "Zu viele Versuche. Bitte warten Sie einige Minuten.",
  },
  offerLine: {
    agreed: "Ihr vereinbarter Preis",
    listPrice: (price: string) => `Listenpreis ${price}`,
    expired: "Ihr vereinbarter Preis gilt nicht mehr — es wird der Listenpreis berechnet.",
  },
  reminder: {
    consent: "Erinnern Sie mich per E-Mail, wenn ich Stücke im Warenkorb lasse",
    hint: "Höchstens eine Erinnerung, nur für diesen Warenkorb. Nach 15 Minuten sind die Stücke nicht mehr reserviert.",
  },
  restore: {
    title: "Gespeicherten Warenkorb wiederherstellen",
    text: "Machen Sie dort weiter, wo Sie aufgehört haben. Die Stücke sind wieder für alle erhältlich, die Verfügbarkeit kann sich also geändert haben.",
    button: "Warenkorb wiederherstellen",
    restoring: "Wird wiederhergestellt…",
    invalid: "Dieser Warenkorb-Link ist abgelaufen oder nicht mehr gültig.",
    done: "Ihr Warenkorb wurde wiederhergestellt.",
  },
  order: {
    statusMetaTitle: "Bestellstatus",
    metaTitle: (n: number) => `Bestellung #${n}`,
    title: (n: number) => `Bestellung #${n}`,
    placedOn: (d: string) => `Aufgegeben am ${d}`,
    paid: "Wir haben Ihre Zahlung erhalten",
    paidText: (email: string) => `Vielen Dank! Eine Bestätigung ist unterwegs an ${email}.`,
    waiting: "Warten auf Zahlung",
    waitingText: "Wir haben noch keine Zahlungsbestätigung erhalten. Diese Seite aktualisiert sich automatisch.",
    continuePayment: "Weiter zur Zahlung",
    processing: "Zahlung wird verarbeitet",
    processingText:
      "Ihre Zahlung wird noch von der Bank oder dem Kartenanbieter bearbeitet. Wir benachrichtigen Sie per E-Mail, sobald sie bestätigt ist; diese Seite aktualisiert sich automatisch.",
    unpaid: "Zahlung nicht abgeschlossen",
    unpaidText: "Ihre Bestellung wurde gespeichert, aber noch nicht bezahlt.",
    payNow: "Jetzt bezahlen",
    failed: "Die Zahlung ist nicht durchgegangen",
    failedText: "Die Zahlung ist fehlgeschlagen, wurde abgebrochen oder ist abgelaufen. Es wurde kein Geld abgebucht.",
    tryAgain: "Erneut versuchen",
    retryBlocked: (titles: string) =>
      `Leider ${titles.includes(",") ? "sind" : "ist"} ${titles} nicht mehr verfügbar, daher kann diese Bestellung nicht mehr bezahlt werden.`,
    retryExpired: "Diese Bestellung ist zu alt, um sie zu bezahlen. Bitte geben Sie eine neue Bestellung auf.",
    canceled: "Diese Bestellung wurde storniert",
    canceledText: "Bei Fragen kontaktieren Sie uns bitte.",
    refunded: "Diese Bestellung wurde erstattet",
    refundedText: "Der Betrag wurde auf Ihre ursprüngliche Zahlungsart zurückerstattet.",
    items: "Artikel",
    subtotal: "Zwischensumme",
    shipping: "Versand",
    total: "Gesamtsumme",
    shipTo: "Lieferung an",
    pickup: "Abholung",
    backToShop: "Weiter einkaufen",
    notConfigured: "Online-Zahlungen sind für diesen Shop noch nicht eingerichtet. Bitte kontaktieren Sie uns, um Ihre Bestellung abzuschließen.",
    devTitle: "Nur in der Entwicklung",
    devText: "Es ist kein Mollie-Schlüssel eingerichtet. Simulieren Sie, was der Mollie-Webhook melden würde:",
    devPaid: "Bezahlt simulieren",
    devFailed: "Fehlschlag simulieren",
    devExpired: "Ablauf simulieren",
    refreshing: "Wird geprüft…",
    privacyNote: "Halten Sie diesen Link privat — jeder mit diesem Link kann den Status dieser Bestellung sehen.",
  },
  errors: {
    itemNotFound: "Dieses Stück wurde nicht gefunden",
    itemUnavailable: "Dieses Stück ist nicht mehr verfügbar",
    loginToBuy: "Melden Sie sich an, um dieses Stück zu kaufen",
    reservedByOther: (mins: number) => `Jemand anderes hat dieses Stück im Warenkorb — versuchen Sie es in ${mins} Min. erneut`,
    enterCode: "Bitte geben Sie einen Code ein",
    cartEmpty: "Ihr Warenkorb ist leer",
    checkFields: "Bitte prüfen Sie die markierten Felder",
    maxChars: (n: number) => `Höchstens ${n} Zeichen`,
    firstName: "Bitte geben Sie Ihren Vornamen ein",
    lastName: "Bitte geben Sie Ihren Nachnamen ein",
    street: "Bitte geben Sie Ihre Straße ein",
    city: "Bitte geben Sie Ihren Ort ein",
    postalCode: "Bitte geben Sie Ihre Postleitzahl ein",
    chooseCountry: "Bitte wählen Sie ein Land",
    email: "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    phone: "Bitte geben Sie Ihre Telefonnummer ein",
    phoneTooLong: "Die Telefonnummer ist zu lang",
    phoneInvalid: "Bitte geben Sie eine gültige Telefonnummer ein",
    chooseShipping: "Bitte wählen Sie eine Versandoption",
    chooseShippingForCountry: "Bitte wählen Sie eine der Versandoptionen für Ihr Land",
    acceptTerms: "Bitte akzeptieren Sie die Allgemeinen Geschäftsbedingungen",
    paymentsNotConfigured: "Zahlungen sind für diesen Shop noch nicht eingerichtet. Bitte kontaktieren Sie uns.",
    choosePaymentMethod: "Bitte wählen Sie eine Zahlungsart",
    paymentMethodUnavailable: "Diese Zahlungsart ist nicht verfügbar",
    noShipping: "Wir versenden nicht in dieses Land",
    overweight: "Ihre Bestellung ist zu schwer für den Versand in dieses Land — kontaktieren Sie uns für ein Angebot",
    loginSensitive: "Ihr Warenkorb enthält Stücke, für die ein Kundenkonto erforderlich ist. Bitte melden Sie sich an.",
    loginRequired: "Bitte melden Sie sich an, um zu bestellen.",
    age: (age: number) => `Bitte bestätigen Sie, dass Sie mindestens ${age} Jahre alt sind`,
    noLongerAvailable: (titles: string, many: boolean) =>
      `Nicht mehr verfügbar: ${titles}. Entfernen Sie ${many ? "diese Stücke" : "dieses Stück"} aus Ihrem Warenkorb, um fortzufahren.`,
    restricted: (country: string, titles: string, many: boolean) =>
      `Kann nicht nach ${country} versendet werden (örtliche Vorschriften): ${titles}. Entfernen Sie ${many ? "diese Stücke" : "dieses Stück"} aus Ihrem Warenkorb oder wählen Sie Abholung.`,
    couponRefused: (message: string, code: string) => `${message} (${code}). Entfernen Sie den Code in Ihrem Warenkorb, um fortzufahren.`,
    minimumNotReached: "Der Mindestbestellwert ist noch nicht erreicht",
    totalZero: "Der Gesamtbetrag Ihrer Bestellung muss größer als null sein",
    couponInvalid: "Dieser Code ist ungültig",
    couponInactive: "Dieser Code ist nicht mehr aktiv",
    couponNotYet: "Dieser Code ist noch nicht gültig",
    couponExpired: "Dieser Code ist abgelaufen",
    couponMinSubtotal: (amount: string) => `Für diesen Code ist eine Zwischensumme von mindestens ${amount} erforderlich`,
    couponUsedUp: "Dieser Code wurde bereits vollständig eingelöst",
    couponAlreadyUsed: "Sie haben diesen Code bereits verwendet",
    couponNotApplicable: "Dieser Code gilt nicht für die Stücke in Ihrem Warenkorb",
    orderNotFound: "Bestellung nicht gefunden",
    orderNotPayable: "Diese Bestellung kann nicht mehr bezahlt werden",
    orderTooOld: "Diese Bestellung ist zu alt, um sie zu bezahlen. Bitte geben Sie eine neue Bestellung auf.",
    paymentStartFailed: "Die Zahlung konnte nicht gestartet werden. Bitte versuchen Sie es gleich noch einmal.",
    retryUnavailable: (titles: string, many: boolean) =>
      `Leider ${many ? "sind" : "ist"} ${titles} nicht mehr verfügbar, daher kann diese Bestellung nicht bezahlt werden.`,
    rateLimitedShort: "Zu viele Versuche. Bitte warten Sie einen Moment.",
  },
};
