/** English copy for cart, checkout and order status (multi-language later). */
export const cartCopy = {
  add: {
    add: "Add to cart",
    adding: "Adding…",
    added: "Added to your cart",
    inCart: "In your cart",
    viewCart: "View cart",
    checkout: "Checkout",
    unavailable: "Not available",
    reservedFor: "Reserved for you",
    error: "Something went wrong. Please try again.",
    rateLimited: "Too many attempts. Please wait a moment.",
    login: "Log in to buy",
  },
  countdown: {
    reservedFor: "Reserved for you",
    expired: "Reservation expired",
    srLabel: (mins: number) => `Reserved for you for about ${mins} more minute${mins === 1 ? "" : "s"}`,
  },
  cart: {
    title: "Your cart",
    metaTitle: "Cart",
    emptyTitle: "Your cart is empty",
    emptyText: "Every item here is one of a kind — when you add something, we hold it for you for a few minutes.",
    browse: "Browse the shop",
    remove: "Remove",
    removing: "Removing…",
    removeLabel: (title: string) => `Remove ${title} from your cart`,
    lapsed: "No longer reserved",
    lapsedHint: "It's still available — reserve it again.",
    reAdd: "Re-add",
    taken: "Someone else has this in their cart",
    takenHint: (mins: number) => `It may become available again in about ${mins} min.`,
    unavailable: "No longer available",
    removeUnavailable: "Remove unavailable items",
    subtotal: "Subtotal",
    shippingEstimate: "Shipping estimate",
    shipTo: "Ship to",
    calculating: "Calculating…",
    pickupOnly: "Pickup only",
    free: "Free",
    from: "from",
    noCountry: "Choose your country to see shipping costs.",
    freeShippingProgress: (amount: string) => `Add ${amount} more for free shipping`,
    freeShippingReached: "You qualify for free shipping",
    minimumOrder: (amount: string) => `Minimum order not reached — add ${amount} more`,
    checkout: "Continue to checkout",
    continueShopping: "Continue shopping",
    uniqueNote: "Items are unique. Your reservation keeps them out of other carts while you check out.",
    totalNote: "Taxes included where applicable. Final shipping is calculated from your address at checkout.",
    itemCount: (n: number) => (n === 1 ? "1 item" : `${n} items`),
  },
  checkout: {
    title: "Checkout",
    notShippable: (country: string) => `Can't be shipped to ${country} — remove it or choose pickup.`,
    metaTitle: "Checkout",
    contact: "Contact",
    email: "Email address",
    phone: "Phone",
    phoneHint: "For delivery questions only.",
    loggedInAs: (email: string) => `Logged in as ${email}`,
    shippingAddress: "Shipping address",
    billingAddress: "Billing address",
    billingSame: "Billing address is the same as the shipping address",
    firstName: "First name",
    lastName: "Last name",
    company: "Company (optional)",
    street: "Street",
    houseNumber: "No.",
    line2: "Apartment, suite, etc. (optional)",
    postalCode: "Postal code",
    city: "City",
    region: "State / province (optional)",
    country: "Country",
    chooseCountry: "Choose a country…",
    shippingMethod: "Shipping",
    noOptions: "Enter your country to see the shipping options.",
    pickup: "Pickup",
    insurance: (price: string) => `Insure this shipment (+${price})`,
    insuranceUpTo: (amount: string) => `covered up to ${amount}`,
    payment: "Payment",
    paymentHostedChoice: "You'll choose how to pay on the secure Mollie payment page.",
    paymentsNotConfigured: "Payments are not configured for this shop yet.",
    paymentsNotConfiguredDev: "Payments are not configured. Development mode: your order will be created and you can simulate the payment on the order page.",
    paymentsTestMode: "Test mode — no real money is charged.",
    note: "Note for the seller (optional)",
    terms: "I accept the",
    termsLink: "terms and conditions",
    newsletter: "Keep me posted about new arrivals (newsletter)",
    ageConfirm: (age: number) => `I confirm that I am at least ${age} years old`,
    ageHint: "Your cart contains age-restricted items.",
    loginRequiredSensitive: "Your cart contains items that are only sold to registered customers. Please log in or create an account to continue.",
    loginRequiredGuestOff: "This shop requires an account to order. Please log in or create an account.",
    login: "Log in",
    register: "Create an account",
    haveAccount: "Have an account?",
    loginToSave: "Log in for faster checkout",
    summary: "Order summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    insuranceLine: "Insurance",
    total: "Total",
    placeOrder: "Place order and pay",
    placeOrderDev: "Place order",
    placing: "Placing order…",
    viewOrder: "Order placed — view your order",
    secure: "You'll be redirected to Mollie to pay securely.",
    edit: "Edit cart",
    emptyTitle: "Nothing to check out",
    emptyText: "Your cart is empty or none of its items can be bought right now.",
    backToCart: "Back to cart",
    blocked: "Some items can't be ordered right now. Remove them from your cart to continue.",
    reReserve: "Reserve again",
    holdNote: "We hold your items while you check out.",
    fixErrors: "Please check the highlighted fields.",
    unexpected: "Something went wrong. Please try again.",
    rateLimited: "Too many attempts. Please wait a few minutes and try again.",
    currencyNote: (currency: string) => `You pay in ${currency}.`,
  },
  coupon: {
    label: "Discount code",
    placeholder: "Enter code",
    apply: "Apply",
    applying: "Applying…",
    remove: "Remove",
    discount: "Discount",
    freeShipping: "Free shipping",
    applied: (code: string) => `Code ${code} applied`,
    notApplied: (code: string, message: string) => `Code ${code}: ${message}`,
    offerNote: "Discount codes don't apply to items bought at an agreed offer price.",
    rateLimited: "Too many attempts. Please wait a few minutes.",
  },
  offerLine: {
    agreed: "Your offer price",
    listPrice: (price: string) => `List price ${price}`,
    expired: "Your agreed offer price no longer applies — the list price is charged.",
  },
  reminder: {
    consent: "Remind me by email if I leave items in my cart",
    hint: "One reminder at most, only for this cart. Items are not reserved after 15 minutes.",
  },
  restore: {
    title: "Restore your saved cart",
    text: "Continue where you left off. Items are for sale to everyone again, so availability may have changed.",
    button: "Restore my cart",
    restoring: "Restoring…",
    invalid: "This cart link has expired or is no longer valid.",
    done: "Your cart has been restored.",
  },
  order: {
    metaTitle: (n: number) => `Order #${n}`,
    title: (n: number) => `Order #${n}`,
    placedOn: (d: string) => `Placed on ${d}`,
    paid: "We received your payment",
    paidText: (email: string) => `Thank you! A confirmation is on its way to ${email}.`,
    waiting: "Waiting for payment",
    waitingText: "We haven't received a payment confirmation yet. This page updates automatically.",
    continuePayment: "Continue to payment",
    processing: "Payment is being processed",
    processingText: "Your payment is pending at the bank or card issuer. We'll email you as soon as it's confirmed; this page updates automatically.",
    unpaid: "Payment not completed",
    unpaidText: "Your order is saved but has not been paid yet.",
    payNow: "Pay now",
    failed: "Payment didn't go through",
    failedText: "The payment failed, was canceled or expired. No money was taken.",
    tryAgain: "Try again",
    retryBlocked: (titles: string) => `Unfortunately ${titles} ${titles.includes(",") ? "are" : "is"} no longer available, so this order can't be paid anymore.`,
    retryExpired: "This order is too old to pay. Please place a new order.",
    canceled: "This order was canceled",
    canceledText: "Please contact us if you have questions.",
    refunded: "This order was refunded",
    refundedText: "The refund was sent to your original payment method.",
    items: "Items",
    subtotal: "Subtotal",
    shipping: "Shipping",
    total: "Total",
    shipTo: "Shipping to",
    pickup: "Pickup",
    backToShop: "Continue shopping",
    notConfigured: "Online payments are not configured for this shop yet. Please contact us to complete your order.",
    devTitle: "Development only",
    devText: "No Mollie key is configured. Simulate what the Mollie webhook would report:",
    devPaid: "Simulate paid",
    devFailed: "Simulate failed",
    devExpired: "Simulate expired",
    refreshing: "Checking…",
    privacyNote: "Keep this link private — anyone with it can see this order's status.",
  },
} as const;
