import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { cartCopy } from "./_copy";

export const cartCopyNl: CopyShape<typeof cartCopy> = {
  add: {
    add: "In winkelwagen",
    adding: "Toevoegen…",
    added: "Toegevoegd aan uw winkelwagen",
    inCart: "In uw winkelwagen",
    viewCart: "Bekijk winkelwagen",
    checkout: "Afrekenen",
    unavailable: "Niet beschikbaar",
    reservedFor: "Voor u gereserveerd",
    error: "Er ging iets mis. Probeer het opnieuw.",
    rateLimited: "Te veel pogingen. Wacht even.",
    login: "Log in om te kopen",
  },
  countdown: {
    reservedFor: "Voor u gereserveerd",
    expired: "Reservering verlopen",
    srLabel: (mins: number) => `Nog ongeveer ${mins} ${mins === 1 ? "minuut" : "minuten"} voor u gereserveerd`,
  },
  cart: {
    title: "Uw winkelwagen",
    metaTitle: "Winkelwagen",
    emptyTitle: "Uw winkelwagen is leeg",
    emptyText: "Elk stuk is uniek — zodra u iets toevoegt, houden we het een paar minuten voor u vast.",
    browse: "Bekijk de winkel",
    remove: "Verwijderen",
    removing: "Verwijderen…",
    removeLabel: (title: string) => `${title} uit uw winkelwagen verwijderen`,
    lapsed: "Niet meer gereserveerd",
    lapsedHint: "Het is nog beschikbaar — reserveer het opnieuw.",
    reAdd: "Opnieuw toevoegen",
    taken: "Iemand anders heeft dit in de winkelwagen",
    takenHint: (mins: number) => `Mogelijk over ongeveer ${mins} min weer beschikbaar.`,
    unavailable: "Niet meer beschikbaar",
    removeUnavailable: "Niet-beschikbare stukken verwijderen",
    subtotal: "Subtotaal",
    shippingEstimate: "Geschatte verzendkosten",
    shipTo: "Verzenden naar",
    calculating: "Berekenen…",
    pickupOnly: "Alleen afhalen",
    free: "Gratis",
    from: "vanaf",
    noCountry: "Kies uw land om de verzendkosten te zien.",
    freeShippingProgress: (amount: string) => `Nog ${amount} tot gratis verzending`,
    freeShippingReached: "U komt in aanmerking voor gratis verzending",
    minimumOrder: (amount: string) => `Minimumbedrag niet bereikt — voeg nog ${amount} toe`,
    checkout: "Verder naar afrekenen",
    continueShopping: "Verder winkelen",
    uniqueNote: "Alle stukken zijn uniek. Uw reservering houdt ze uit andere winkelwagens terwijl u afrekent.",
    totalNote: "Inclusief btw waar van toepassing. De definitieve verzendkosten worden bij het afrekenen berekend op basis van uw adres.",
    itemCount: (n: number) => (n === 1 ? "1 stuk" : `${n.toLocaleString("nl-NL")} stuks`),
  },
  checkout: {
    title: "Afrekenen",
    notShippable: (country: string) => `Kan niet naar ${country} worden verzonden — verwijder het of kies afhalen.`,
    metaTitle: "Afrekenen",
    contact: "Contactgegevens",
    email: "E-mailadres",
    phone: "Telefoon",
    phoneHint: "Alleen voor vragen over de bezorging.",
    loggedInAs: (email: string) => `Ingelogd als ${email}`,
    shippingAddress: "Verzendadres",
    billingAddress: "Factuuradres",
    billingSame: "Factuuradres is hetzelfde als het verzendadres",
    firstName: "Voornaam",
    lastName: "Achternaam",
    company: "Bedrijf (optioneel)",
    street: "Straat",
    houseNumber: "Nr.",
    line2: "Toevoeging, appartement, etc. (optioneel)",
    postalCode: "Postcode",
    city: "Plaats",
    region: "Provincie / staat (optioneel)",
    country: "Land",
    chooseCountry: "Kies een land…",
    shippingMethod: "Verzending",
    noOptions: "Kies uw land om de verzendopties te zien.",
    pickup: "Afhalen",
    insurance: (price: string) => `Deze zending verzekeren (+${price})`,
    insuranceUpTo: (amount: string) => `verzekerd tot ${amount}`,
    payment: "Betaalmethode",
    paymentHostedChoice: "U kiest uw betaalmethode op de beveiligde betaalpagina van Mollie.",
    paymentsNotConfigured: "Betalingen zijn voor deze winkel nog niet ingesteld.",
    paymentsNotConfiguredDev:
      "Betalingen zijn niet ingesteld. Ontwikkelmodus: uw bestelling wordt aangemaakt en u kunt de betaling op de bestelpagina simuleren.",
    paymentsTestMode: "Testmodus — er wordt geen echt geld afgeschreven.",
    note: "Opmerking voor de verkoper (optioneel)",
    terms: "Ik ga akkoord met de",
    termsLink: "algemene voorwaarden",
    newsletter: "Houd mij op de hoogte van nieuwe aanwinsten (nieuwsbrief)",
    ageConfirm: (age: number) => `Ik bevestig dat ik minimaal ${age} jaar oud ben`,
    ageHint: "Uw winkelwagen bevat stukken met een leeftijdsgrens.",
    loginRequiredSensitive:
      "Uw winkelwagen bevat stukken die alleen aan geregistreerde klanten worden verkocht. Log in of maak een account aan om verder te gaan.",
    loginRequiredGuestOff: "Voor bestellen in deze winkel is een account nodig. Log in of maak een account aan.",
    login: "Inloggen",
    register: "Account aanmaken",
    haveAccount: "Heeft u een account?",
    loginToSave: "Log in om sneller af te rekenen",
    summary: "Overzicht van uw bestelling",
    subtotal: "Subtotaal",
    shipping: "Verzending",
    insuranceLine: "Verzekering",
    surchargeLine: "Toeslag betaalmethode",
    methodSurcharge: (label: string, rule: string) => `${label}: +${rule}`,
    total: "Totaal",
    placeOrder: "Bestelling plaatsen en betalen",
    placeOrderDev: "Bestelling plaatsen",
    placing: "Bestelling plaatsen…",
    viewOrder: "Bestelling geplaatst — bekijk uw bestelling",
    secure: "U wordt doorgestuurd naar Mollie om veilig te betalen.",
    edit: "Winkelwagen wijzigen",
    emptyTitle: "Niets om af te rekenen",
    emptyText: "Uw winkelwagen is leeg of geen van de stukken kan op dit moment worden gekocht.",
    backToCart: "Terug naar winkelwagen",
    blocked: "Sommige stukken kunnen op dit moment niet worden besteld. Verwijder ze uit uw winkelwagen om verder te gaan.",
    reReserve: "Opnieuw reserveren",
    holdNote: "We houden uw stukken vast terwijl u afrekent.",
    fixErrors: "Controleer de gemarkeerde velden.",
    unexpected: "Er ging iets mis. Probeer het opnieuw.",
    rateLimited: "Te veel pogingen. Wacht een paar minuten en probeer het opnieuw.",
    currencyNote: (currency: string) => `U betaalt in ${currency}.`,
    surchargeMax: (amount: string) => `max. ${amount}`,
  },
  coupon: {
    label: "Kortingscode",
    placeholder: "Voer code in",
    apply: "Toepassen",
    applying: "Toepassen…",
    remove: "Verwijderen",
    discount: "Korting",
    freeShipping: "Gratis verzending",
    applied: (code: string) => `Code ${code} toegepast`,
    notApplied: (code: string, message: string) => `Code ${code}: ${message}`,
    offerNote: "Kortingscodes gelden niet voor stukken die u voor een afgesproken bodprijs koopt.",
    rateLimited: "Te veel pogingen. Wacht een paar minuten.",
  },
  offerLine: {
    agreed: "Uw bodprijs",
    listPrice: (price: string) => `Vraagprijs ${price}`,
    expired: "Uw afgesproken bodprijs geldt niet meer — de vraagprijs wordt berekend.",
  },
  reminder: {
    consent: "Stuur mij een herinnering per e-mail als ik stukken in mijn winkelwagen laat liggen",
    hint: "Hooguit één herinnering, alleen voor deze winkelwagen. Na 15 minuten zijn de stukken niet meer gereserveerd.",
  },
  restore: {
    title: "Uw opgeslagen winkelwagen herstellen",
    text: "Ga verder waar u was gebleven. De stukken zijn weer voor iedereen te koop, dus de beschikbaarheid kan veranderd zijn.",
    button: "Mijn winkelwagen herstellen",
    restoring: "Herstellen…",
    invalid: "Deze winkelwagenlink is verlopen of niet meer geldig.",
    done: "Uw winkelwagen is hersteld.",
  },
  order: {
    statusMetaTitle: "Status van uw bestelling",
    metaTitle: (n: number) => `Bestelling #${n}`,
    title: (n: number) => `Bestelling #${n}`,
    placedOn: (d: string) => `Geplaatst op ${d}`,
    paid: "We hebben uw betaling ontvangen",
    paidText: (email: string) => `Hartelijk dank! Er is een bevestiging onderweg naar ${email}.`,
    waiting: "Wachten op betaling",
    waitingText: "We hebben nog geen betalingsbevestiging ontvangen. Deze pagina wordt automatisch bijgewerkt.",
    continuePayment: "Verder naar betalen",
    processing: "Betaling wordt verwerkt",
    processingText:
      "Uw betaling wordt nog verwerkt door de bank of kaartuitgever. We mailen u zodra deze is bevestigd; deze pagina wordt automatisch bijgewerkt.",
    unpaid: "Betaling niet voltooid",
    unpaidText: "Uw bestelling is opgeslagen, maar nog niet betaald.",
    payNow: "Nu betalen",
    failed: "Betaling is niet gelukt",
    failedText: "De betaling is mislukt, geannuleerd of verlopen. Er is geen geld afgeschreven.",
    tryAgain: "Opnieuw proberen",
    retryBlocked: (titles: string) =>
      `Helaas ${titles.includes(",") ? "zijn" : "is"} ${titles} niet meer beschikbaar, dus deze bestelling kan niet meer worden betaald.`,
    retryExpired: "Deze bestelling is te oud om te betalen. Plaats een nieuwe bestelling.",
    canceled: "Deze bestelling is geannuleerd",
    canceledText: "Neem contact met ons op als u vragen heeft.",
    refunded: "Deze bestelling is terugbetaald",
    refundedText: "Het bedrag is teruggestort via uw oorspronkelijke betaalmethode.",
    items: "Stukken",
    subtotal: "Subtotaal",
    shipping: "Verzending",
    total: "Totaal",
    shipTo: "Verzenden naar",
    pickup: "Afhalen",
    backToShop: "Verder winkelen",
    notConfigured: "Online betalen is voor deze winkel nog niet ingesteld. Neem contact met ons op om uw bestelling af te ronden.",
    devTitle: "Alleen voor ontwikkeling",
    devText: "Er is geen Mollie-sleutel ingesteld. Simuleer wat de Mollie-webhook zou melden:",
    devPaid: "Betaald simuleren",
    devFailed: "Mislukt simuleren",
    devExpired: "Verlopen simuleren",
    refreshing: "Controleren…",
    privacyNote: "Houd deze link privé — iedereen met deze link kan de status van deze bestelling zien.",
  },
  errors: {
    itemNotFound: "Dit stuk is niet gevonden",
    itemUnavailable: "Dit stuk is niet meer beschikbaar",
    loginToBuy: "Log in om dit stuk te kopen",
    reservedByOther: (mins: number) => `Iemand anders heeft dit in de winkelwagen — probeer het over ${mins} min opnieuw`,
    enterCode: "Voer een code in",
    cartEmpty: "Uw winkelwagen is leeg",
    checkFields: "Controleer de gemarkeerde velden",
    maxChars: (n: number) => `Gebruik maximaal ${n} tekens`,
    firstName: "Vul uw voornaam in",
    lastName: "Vul uw achternaam in",
    street: "Vul uw straat in",
    city: "Vul uw plaats in",
    postalCode: "Vul uw postcode in",
    chooseCountry: "Kies een land",
    email: "Vul een geldig e-mailadres in",
    phone: "Vul uw telefoonnummer in",
    phoneTooLong: "Het telefoonnummer is te lang",
    phoneInvalid: "Vul een geldig telefoonnummer in",
    chooseShipping: "Kies een verzendoptie",
    chooseShippingForCountry: "Kies een van de verzendopties voor uw land",
    acceptTerms: "Ga akkoord met de algemene voorwaarden",
    paymentsNotConfigured: "Betalingen zijn voor deze winkel nog niet ingesteld. Neem contact met ons op.",
    choosePaymentMethod: "Kies een betaalmethode",
    paymentMethodUnavailable: "Deze betaalmethode is niet beschikbaar",
    noShipping: "We verzenden niet naar dit land",
    overweight: "Uw bestelling is te zwaar om naar dit land te verzenden — neem contact met ons op voor een offerte",
    loginSensitive: "Uw winkelwagen bevat stukken waarvoor een account nodig is. Log in.",
    loginRequired: "Log in om af te rekenen.",
    age: (age: number) => `Bevestig dat u minimaal ${age} jaar oud bent`,
    noLongerAvailable: (titles: string, many: boolean) =>
      `Niet meer beschikbaar: ${titles}. Verwijder ${many ? "deze stukken" : "dit stuk"} uit uw winkelwagen om verder te gaan.`,
    restricted: (country: string, titles: string, many: boolean) =>
      `Kan niet naar ${country} worden verzonden (lokale regelgeving): ${titles}. Verwijder ${many ? "deze stukken" : "dit stuk"} uit uw winkelwagen of kies afhalen.`,
    couponRefused: (message: string, code: string) => `${message} (${code}). Verwijder de code in uw winkelwagen om verder te gaan.`,
    minimumNotReached: "Het minimale bestelbedrag is nog niet bereikt",
    totalZero: "Het totaalbedrag van uw bestelling moet hoger zijn dan nul",
    couponInvalid: "Deze code is niet geldig",
    couponInactive: "Deze code is niet meer actief",
    couponNotYet: "Deze code is nog niet geldig",
    couponExpired: "Deze code is verlopen",
    couponMinSubtotal: (amount: string) => `Voor deze code is een subtotaal van minimaal ${amount} nodig`,
    couponUsedUp: "Deze code is volledig gebruikt",
    couponAlreadyUsed: "U heeft deze code al gebruikt",
    couponNotApplicable: "Deze code geldt niet voor de stukken in uw winkelwagen",
    orderNotFound: "Bestelling niet gevonden",
    orderNotPayable: "Deze bestelling kan niet meer worden betaald",
    orderTooOld: "Deze bestelling is te oud om te betalen. Plaats een nieuwe bestelling.",
    paymentStartFailed: "We konden de betaling niet starten. Probeer het zo meteen opnieuw.",
    retryUnavailable: (titles: string, many: boolean) =>
      `Helaas ${many ? "zijn" : "is"} ${titles} niet meer beschikbaar, dus deze bestelling kan niet worden betaald.`,
    rateLimitedShort: "Te veel pogingen. Wacht even.",
  },
};
