/* Leads ("Sell your collection") admin copy (English). */

export const copy = {
  crumb: "Sales",
  title: "Leads",
  caption: "Sell requests",
  views: { all: "All", NEW: "New", CONTACTED: "Contacted", BOUGHT: "Bought", DECLINED: "Declined" },
  search: "Search name, email or items…",
  cols: { received: "Received", seller: "Seller", items: "Items", photos: "Photos", status: "Status" },
  empty: "No sell requests yet",
  emptyBody: "Visitors can offer their items on the shop's “Sell your collection” page (/sell). New requests show up here and are mailed to you.",
  emptyFiltered: "No requests match these filters",
  emptyFilteredBody: "Try another status or clear the search.",
  drawer: {
    received: "Received",
    email: "Email",
    phone: "Phone",
    handledBy: "Last handled by",
    items: "Items offered",
    message: "Message",
    photos: (n: number) => (n ? `Photos (${n})` : "Photos"),
    noPhotos: "No photos were attached.",
    openPhoto: (n: number) => `Open photo ${n} in a new tab`,
    status: "Status",
    saveStatus: "Update status",
    note: "Internal note",
    noteHint: "Only visible to staff.",
    saveNote: "Save note",
    reply: "Reply by email",
    createPurchase: "Create purchase record",
    createPurchaseHint: "Opens Sourcing with the seller's name prefilled.",
    close: "Close",
    notFound: "This request no longer exists.",
  },
  saved: { status: "Status updated.", note: "Note saved." },
  errors: {
    loadTitle: "Leads could not be loaded",
    loadBody: "Something went wrong while loading the sell requests. Try again.",
    retry: "Try again",
    notFound: "This request no longer exists.",
    invalid: "Check the highlighted fields.",
    forbidden: "You do not have access to this shop.",
    unexpected: "Something went wrong. Try again.",
  },
} as const;
