/* Screen copy for the shipping board. */

export const boardCopy = {
  crumb: "Orders",
  title: "Shipping board",
  list: "Order list",
  intro: "Paid orders move from packing to shipped. Drag a card to another lane or use its buttons.",
  lanes: {
    awaiting: "Awaiting payment",
    toPack: "To pack",
    packed: "Packed",
    shipped: "Shipped",
  },
  shippedAside: (days: number) => `Last ${days} days`,
  more: (shown: number, total: number) => (total > shown ? `Showing ${shown} of ${total}` : null),
  empty: "Nothing here",
  dropHere: "Drop here",
  day: (n: number) => `day ${n}`,
  paid: (d: string) => `Paid ${d}`,
  shippedOn: (d: string) => `Shipped ${d}`,
  delivered: "Delivered",
  pickup: "Pickup",
  items: (n: number) => `${n} ${n === 1 ? "item" : "items"}`,
  select: (n: number) => `Select order #${n}`,
  selectLane: (lane: string) => `Select all in ${lane}`,
  selected: (n: number) => `${n} selected`,
  printSlips: (n: number) => `Print packing slips (${n})`,
  clear: "Clear",
  actions: {
    pack: "Mark packed",
    ship: "Mark shipped…",
    deliver: "Mark delivered",
    unpack: "Back to To pack",
    backToPacked: "Back to Packed",
    moveLabel: (n: number) => `Actions for order #${n}`,
  },
  moved: {
    PACKED: (n: number) => `#${n} marked as packed.`,
    UNFULFILLED: (n: number) => `#${n} moved back to To pack.`,
    DELIVERED: (n: number) => `#${n} marked as delivered.`,
    SHIPPED: (n: number) => `#${n} marked as shipped.`,
  },
  ship: {
    title: (n: number) => `Mark #${n} as shipped`,
    description: "Add the carrier and tracking code so the customer can follow the parcel.",
    pickupDescription: "This order is collected in person. Tracking is optional.",
    carrier: "Carrier",
    carrierOther: "Other carrier",
    carrierName: "Carrier name",
    none: "No carrier",
    trackingNumber: "Tracking code",
    trackingUrl: "Tracking link",
    trackingUrlHint: (auto: boolean) =>
      auto ? "Filled in from the carrier's tracking page. You can change it." : "Full https:// link to the carrier's tracking page (optional).",
    notify: "Email the customer",
    notifyHint: "Sends the “Your order is on its way” mail with the tracking link (once per shipment).",
    submit: "Mark shipped",
    cancel: "Cancel",
    done: (n: number, mailed: boolean) => `#${n} marked as shipped${mailed ? " — the customer gets an email." : "."}`,
  },
  notFound: "This order no longer exists or belongs to another shop.",
};
