export const fairsCopy = {
  crumb: "Sales",
  title: "Fairs",
  add: "New fair",
  columns: { name: "Fair", dates: "Dates", status: "Status", items: "Items", sold: "Sold", revenue: "Revenue" },
  status: { PREPARING: "Preparing", LIVE: "Live", ENDED: "Ended" },
  empty: {
    title: "No fairs yet",
    body: "Plan a fair, choose the items you take along, print QR labels and sell from your phone — also without a connection.",
  },
  form: {
    newTitle: "New fair",
    editTitle: "Edit fair",
    description: "Fair sales become normal orders: invoice, stock movement and certificate, same as webshop sales.",
    name: "Name",
    startsOn: "First day",
    endsOn: "Last day",
    endsOnHint: "Optional, for a fair of more than one day.",
    hide: "Hide the fair items from the webshop while the fair is live",
    hideHint: "They come back online automatically when you end the fair.",
    notes: "Notes (internal)",
    save: "Save fair",
    created: "Fair created.",
    saved: "Fair saved.",
  },
  steps: { prepare: "Prepare", live: "Live at the fair", end: "End & report" },
  items: {
    title: (n: number) => `Take to the fair · ${n} ${n === 1 ? "item" : "items"}`,
    cols: { item: "Item", list: "List", floor: "Floor", state: "" },
    floorHint: "Floor: suggested at list −15%, change per item. Empty = list price is the minimum.",
    remove: "Remove",
    removed: "Item taken off the fair.",
    floorSaved: "Floor saved.",
    sold: (price: string) => `Sold ${price}`,
    held: "Hidden in shop",
    heldElsewhere: "On another fair",
    notForSale: "Not for sale",
    empty: "No items yet. Search your inventory below and add what you take along.",
    add: "Add items",
    addTitle: "Add items to the fair",
    addDescription: "Only items that are for sale (active, in stock) can go on a fair.",
    search: "Search title, stock number or SKU…",
    addSelected: (n: number) => (n ? `Add ${n} ${n === 1 ? "item" : "items"}` : "Add items"),
    added: (n: number, skipped: number) => `${n} ${n === 1 ? "item" : "items"} added${skipped ? ` · ${skipped} skipped (not for sale or already on the fair)` : ""}.`,
    noResults: "No items for sale match this search.",
  },
  labels: {
    title: "QR labels",
    layout: "Label size",
    layouts: { a4: "A4 sheet, 3 × 8 labels (70 × 37 mm)", roll62: "Label printer 62 mm roll", tag: "Hang tags 50 × 30 mm" },
    price: "Print the price on the label",
    hint: "The QR opens the public product page for anyone who scans it; fair mode reads the stock number from it.",
    print: (n: number) => `Print ${n} ${n === 1 ? "label" : "labels"} (PDF)`,
  },
  live: {
    title: "Live",
    report: "Report",
    sold: "items sold",
    revenue: "revenue",
    split: (card: string, cash: string, invoice: string) => `card ${card} · cash ${cash} · invoice ${invoice}`,
    margin: "margin",
    marginUnknown: (n: number) => `${n} without purchase price`,
    vsList: "average vs. list",
    latest: "Latest sales",
    noSales: "No sales yet.",
    cash: (amount: string) => `Cash in the box should be ${amount} — count it before you close the day.`,
    openSell: "Open fair mode",
    sellHint: "Open fair mode on your phone or tablet while signed in. It keeps working offline and syncs when the connection is back.",
    start: "Start fair",
    startTitle: "Start the fair?",
    startBody: (hide: boolean) =>
      hide ? "The items go live in fair mode and are hidden in the webshop until you end the fair." : "The items go live in fair mode. They stay visible in the webshop.",
    started: "The fair is live.",
    end: (n: number) => `End fair · put ${n} unsold ${n === 1 ? "item" : "items"} back online`,
    endTitle: "End the fair?",
    endBody: "Unsold items are for sale in the webshop again right away. Sales still waiting on a phone can sync afterwards.",
    ended: "Fair ended. Unsold items are back online.",
    ordersNote: "Sold items become normal orders: invoice, stock movement, certificate — same as webshop sales.",
    unsold: (n: number) => `${n} unsold`,
  },
  edit: "Edit",
  deleteLabel: "Delete",
  deleteTitle: "Delete this fair?",
  deleteBody: "Only possible while it was never live. The items stay in your inventory.",
  notFound: "Fair not found",
  error: { title: "Fairs could not be loaded", body: "Something went wrong while loading the fairs. Try again.", retry: "Try again" },
} as const;
