/** Screen copy for the menus screen (English). */
export const copy = {
  crumb: "Website",
  title: "Menus",
  tabs: { HEADER: "Header", FOOTER: "Footer" },
  tabsLabel: "Menu",
  limits: {
    HEADER: (n: number, max: number, child: number) => `${n} of ${max} menu items used · up to ${child} sub-items per item.`,
    FOOTER: (n: number, max: number, child: number) => `${n} of ${max} columns used · up to ${child} links per column.`,
    full: {
      HEADER: "The header menu is full. Remove an item to add another.",
      FOOTER: "The footer has the maximum number of columns. Remove one to add another.",
    },
    childFull: (max: number) => `This item has the maximum of ${max} sub-items.`,
  },
  intro: {
    HEADER: "The main navigation at the top of the shop. Items with sub-items open a dropdown; every item needs a link.",
    FOOTER: "Columns at the bottom of the shop. A column can be a plain heading with links below it.",
  },
  addRoot: { HEADER: "Add menu item", FOOTER: "Add column" },
  addChild: { HEADER: "Add sub-item", FOOTER: "Add link" },
  edit: "Edit",
  delete: "Delete",
  moveUp: "Move up",
  moveDown: "Move down",
  deleteTitle: (label: string) => `Delete “${label}”?`,
  deleteBody: (children: number) =>
    children > 0
      ? `The item and its ${children} sub-item${children === 1 ? "" : "s"} are removed from the menu. Pages and categories are not affected.`
      : "The item is removed from the menu. Pages and categories are not affected.",
  deleted: "Menu item deleted.",
  saved: "Menu item saved.",
  added: "Menu item added.",
  emptyTitle: { HEADER: "The header menu is empty", FOOTER: "The footer has no columns" },
  emptyBody: { HEADER: "Add links to pages, categories or shop sections.", FOOTER: "Add a column, then links inside it." },
  noLink: "No link (heading)",
  target: {
    page: "Page",
    category: "Category",
    route: "Shop section",
    url: "Web address",
    none: "None",
    missingPage: "Page no longer exists",
    missingCategory: "Category no longer exists",
    draftPage: "Draft: hidden in the shop",
    inactiveCategory: "Inactive: hidden in the shop",
  },
  form: {
    newTitle: { HEADER: "New menu item", FOOTER: "New column" },
    newChildTitle: (parent: string) => `New link under “${parent}”`,
    editTitle: (label: string) => `Edit “${label}”`,
    label: "Label",
    labelHint: "Shown in the menu (max 50 characters).",
    linkTo: "Links to",
    page: "Page",
    category: "Category",
    route: "Shop section",
    url: "Web address",
    urlHint: "A shop path such as /shop, a full https:// URL or mailto:.",
    choosePage: "Choose a page…",
    chooseCategory: "Choose a category…",
    chooseRoute: "Choose a section…",
    save: "Save",
    add: "Add",
    saving: "Saving…",
    cancel: "Cancel",
    unsafeUrl: "Only http(s), mailto and relative links are allowed.",
    needsLink: "Choose where this item links to.",
  },
} as const;
