import type { StatusTone } from "@/components/admin/ui";

export const offersCopy = {
  crumb: "Sales",
  title: "Offers",
  views: { pending: "Pending", countered: "Countered", accepted: "Accepted", converted: "Bought", closed: "Closed", all: "All" },
  status: {
    PENDING: "Pending",
    COUNTERED: "Countered",
    ACCEPTED: "Accepted",
    CONVERTED: "Bought",
    REJECTED: "Rejected",
    EXPIRED: "Expired",
    WITHDRAWN: "Withdrawn",
  },
  search: "Search name, email, item or stock code…",
  columns: { item: "Item", customer: "Customer", offer: "Offer", price: "List price", pct: "% of price", status: "Status", received: "Received" },
  empty: { title: "No offers here", body: "Offers customers make on items that accept offers appear here. Turn offers on per product or for the whole shop in Settings → Catalog." },
  detail: {
    product: "Item",
    customer: "Customer",
    message: "Message",
    noMessage: "No message.",
    listPrice: "List price",
    offer: "Offer",
    counter: "Your counter offer",
    agreed: "Agreed price",
    cost: "Purchase price",
    minimum: "Minimum accepted",
    linkValid: "Link valid until",
    order: "Order",
    history: "History",
    others: "Other offers on this item",
    noOthers: "None.",
    unavailable: "This item is no longer for sale.",
    view: "View item",
  },
  actions: {
    accept: "Accept",
    acceptTitle: "Accept this offer?",
    acceptBody: (amount: string) => `The customer gets a personal link to buy the item for ${amount}, valid for 48 hours. The item stays for sale until they check out.`,
    counter: "Counter",
    counterTitle: "Make a counter offer",
    counterBody: "The customer can accept or decline your price for 72 hours.",
    counterAmount: "Your price",
    note: "Note to the customer (optional)",
    reject: "Reject",
    rejectTitle: "Reject this offer?",
    rejectBody: "The customer gets a polite email. This can't be undone.",
    accepted: "Offer accepted — the customer was emailed a checkout link.",
    countered: "Counter offer sent.",
    rejected: "Offer rejected.",
  },
  events: {
    "offer.accept": "Accepted",
    "offer.counter": "Counter offer sent",
    "offer.reject": "Rejected",
    "offer.counter.accept": "Customer accepted the counter offer",
    "offer.counter.decline": "Customer declined the counter offer",
  } as Record<string, string>,
  error: { title: "Offers could not be loaded", body: "Something went wrong while loading the offers. Try again.", retry: "Try again" },
} as const;

export const OFFER_STATUS_TONE: Record<keyof typeof offersCopy.status, StatusTone> = {
  PENDING: "warn",
  COUNTERED: "info",
  ACCEPTED: "ok",
  CONVERTED: "ok",
  REJECTED: "mute",
  EXPIRED: "mute",
  WITHDRAWN: "mute",
};
