import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { accountCopy } from "./_copy";
import { wishlistCopyDe } from "./_copy-wishlist.de";

export const accountCopyDe: CopyShape<typeof accountCopy> = {
  common: {
    email: "E-Mail-Adresse",
    password: "Passwort",
    name: "Vollständiger Name",
    phone: "Telefon (optional)",
    save: "Änderungen speichern",
    saving: "Wird gespeichert…",
    saved: "Gespeichert.",
    cancel: "Abbrechen",
    unexpected: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
    rateLimited: "Zu viele Versuche. Bitte warten Sie einige Minuten und versuchen Sie es erneut.",
    captcha: "Wir konnten nicht bestätigen, dass Sie ein Mensch sind. Bitte versuchen Sie es erneut.",
    required: "Dieses Feld ist erforderlich.",
    loading: "Wird geladen…",
  },
  login: {
    title: "Anmelden",
    intro: "Willkommen zurück. Melden Sie sich an, um Ihre Bestellungen, Adressen und Ihre Merkliste zu sehen.",
    submit: "Anmelden",
    submitting: "Anmeldung läuft…",
    forgot: "Passwort vergessen?",
    noAccount: "Neu hier?",
    createAccount: "Kundenkonto erstellen",
    resetDone: "Ihr Passwort wurde geändert. Sie können sich jetzt anmelden.",
    deleted: "Ihr Kundenkonto wurde gelöscht.",
    errors: {
      missing: "Bitte geben Sie Ihre E-Mail-Adresse und Ihr Passwort ein.",
      invalid_credentials: "E-Mail-Adresse oder Passwort ist falsch.",
      rate_limited: "Zu viele Anmeldeversuche. Bitte warten Sie 15 Minuten und versuchen Sie es erneut.",
      disabled: "Dieses Kundenkonto wurde deaktiviert. Bitte wenden Sie sich an den Shop.",
    },
  },
  twoFactor: {
    title: "Zwei-Schritt-Verifizierung",
    intro: "Geben Sie den 6-stelligen Code aus Ihrer Authenticator-App oder einen Ihrer Wiederherstellungscodes ein.",
    code: "Bestätigungscode",
    submit: "Bestätigen",
    submitting: "Wird geprüft…",
    restart: "Neu beginnen",
    errors: {
      missing: "Bitte geben Sie Ihren Bestätigungscode ein.",
      invalid_code: "Dieser Code ist ungültig. Bitte versuchen Sie es erneut.",
      rate_limited: "Zu viele Versuche. Bitte melden Sie sich erneut an.",
      no_pending_session: "Ihre Anmeldesitzung ist abgelaufen. Bitte melden Sie sich erneut an.",
    },
  },
  register: {
    title: "Kundenkonto erstellen",
    intro: "Verfolgen Sie Ihre Bestellungen, speichern Sie Adressen für einen schnelleren Checkout und führen Sie eine Merkliste.",
    submit: "Konto erstellen",
    submitting: "Konto wird erstellt…",
    passwordHint: (min: number) => `Mindestens ${min} Zeichen.`,
    newsletter: "Newsletter abonnieren (Sie erhalten eine E-Mail zur Bestätigung).",
    haveAccount: "Sie haben bereits ein Kundenkonto?",
    login: "Anmelden",
    privacy: "Wir verwenden Ihre Daten nur zur Abwicklung Ihrer Bestellungen und zur Führung Ihres Kundenkontos.",
    errors: {
      email_taken: "Mit dieser E-Mail-Adresse besteht bereits ein Kundenkonto. Melden Sie sich an oder setzen Sie Ihr Passwort zurück.",
      invalid: "Bitte prüfen Sie die markierten Felder.",
      rate_limited: "Zu viele Registrierungen von Ihrer Verbindung. Bitte versuchen Sie es später erneut.",
    },
  },
  forgot: {
    title: "Passwort vergessen?",
    intro: "Geben Sie die E-Mail-Adresse Ihres Kundenkontos ein. Wir senden Ihnen einen Link, mit dem Sie ein neues Passwort wählen können.",
    submit: "Link zum Zurücksetzen senden",
    submitting: "Wird gesendet…",
    sent: "Falls für diese Adresse ein Kundenkonto besteht, haben wir Ihnen einen Link zum Zurücksetzen Ihres Passworts gesendet. Der Link ist 30 Minuten gültig.",
    back: "Zurück zur Anmeldung",
    missing: "Bitte geben Sie Ihre E-Mail-Adresse ein.",
  },
  reset: {
    title: "Neues Passwort wählen",
    newPassword: "Neues Passwort",
    confirm: "Neues Passwort wiederholen",
    submit: "Neues Passwort festlegen",
    submitting: "Wird gespeichert…",
    mismatch: "Die Passwörter stimmen nicht überein.",
    invalidToken: "Dieser Link ist ungültig oder abgelaufen. Bitte fordern Sie einen neuen an.",
    requestNew: "Neuen Link anfordern",
    missingToken: "Für diese Seite benötigen Sie den Link aus der E-Mail zum Zurücksetzen Ihres Passworts.",
  },
  account: {
    title: "Mein Konto",
    nav: {
      label: "Kundenkonto",
      overview: "Übersicht",
      orders: "Bestellungen",
      addresses: "Adressen",
      wishlist: "Merkliste",
      alerts: "Benachrichtigungen",
      profile: "Profil & Passwort",
      privacy: "Newsletter & Datenschutz",
      logout: "Abmelden",
    },
    greeting: (name: string | null) => (name ? `Hallo, ${name}` : "Hallo"),
    recentOrders: "Letzte Bestellungen",
    allOrders: "Alle Bestellungen",
    noOrders: "Sie haben noch keine Bestellungen aufgegeben.",
    startShopping: "Zum Shop",
    defaultAddress: "Standard-Lieferadresse",
    noAddress: "Noch keine Adresse gespeichert.",
    manageAddresses: "Adressen verwalten",
    wishlistCount: (n: number) => (n === 1 ? "1 Artikel auf Ihrer Merkliste" : `${n.toLocaleString("de-DE")} Artikel auf Ihrer Merkliste`),
    viewWishlist: "Merkliste ansehen",
    unverified: "E-Mail-Adresse noch nicht bestätigt.",
  },
  orders: {
    title: "Bestellungen",
    number: "Bestellung",
    date: "Datum",
    status: "Status",
    total: "Summe",
    items: (n: number) => (n === 1 ? "1 Artikel" : `${n.toLocaleString("de-DE")} Artikel`),
    view: "Bestellung ansehen",
    empty: "Noch keine Bestellungen.",
    statuses: {
      canceled: "Storniert",
      payment_failed: "Zahlung fehlgeschlagen",
      payment_expired: "Zahlung abgelaufen",
      refunded: "Erstattet",
      partially_refunded: "Teilweise erstattet",
      awaiting_payment: "Zahlung ausstehend",
      delivered: "Zugestellt",
      shipped: "Versandt",
      packed: "Verpackt",
      processing: "Bezahlt — in Bearbeitung",
    },
  },
  addresses: {
    title: "Adressen",
    add: "Adresse hinzufügen",
    edit: "Adresse bearbeiten",
    newTitle: "Neue Adresse",
    editTitle: "Adresse bearbeiten",
    empty: "Sie haben noch keine Adressen gespeichert.",
    default: "Standard",
    makeDefault: "Als Standard festlegen",
    remove: "Löschen",
    removeConfirm: "Diese Adresse löschen?",
    shipping: "Lieferung",
    billing: "Rechnung",
    type: "Adresstyp",
    isDefault: "Als Standard für diesen Typ verwenden",
    limit: "Sie haben die maximale Anzahl gespeicherter Adressen erreicht.",
    notFound: "Diese Adresse existiert nicht mehr.",
    fields: {
      firstName: "Vorname",
      lastName: "Nachname",
      company: "Firma (optional)",
      street: "Straße",
      houseNumber: "Hausnummer",
      line2: "Adresszusatz, Wohnung usw. (optional)",
      postalCode: "Postleitzahl",
      city: "Ort",
      region: "Bundesland / Region (optional)",
      countryCode: "Land",
      phone: "Telefon (optional)",
    },
    save: "Adresse speichern",
    shipsTo: "Wir liefern nach",
    allCountries: "Alle Länder",
    back: "Zurück zu den Adressen",
  },
  profile: {
    title: "Profil & Passwort",
    details: "Ihre Daten",
    detailsSaved: "Ihre Daten wurden gespeichert.",
    emailTitle: "E-Mail-Adresse",
    emailIntro: "Mit dieser Adresse melden Sie sich an; an sie senden wir E-Mails zu Ihren Bestellungen.",
    newEmail: "Neue E-Mail-Adresse",
    currentPassword: "Aktuelles Passwort",
    changeEmail: "E-Mail-Adresse ändern",
    emailChanged: "Ihre E-Mail-Adresse wurde geändert.",
    emailErrors: {
      invalid_email: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
      invalid_password: "Ihr aktuelles Passwort ist falsch.",
      rate_limited: "Zu viele Versuche. Bitte warten Sie 15 Minuten.",
      email_taken: "Diese E-Mail-Adresse wird bereits von einem anderen Kundenkonto verwendet.",
      unchanged: "Das ist bereits Ihre E-Mail-Adresse.",
    },
    passwordTitle: "Passwort ändern",
    newPassword: "Neues Passwort",
    confirmPassword: "Neues Passwort wiederholen",
    changePassword: "Passwort ändern",
    passwordChanged: "Ihr Passwort wurde geändert. Andere Geräte wurden abgemeldet.",
    passwordErrors: {
      invalid_current_password: "Ihr aktuelles Passwort ist falsch.",
      invalid_password: "Bitte wählen Sie ein sichereres Passwort.",
      rate_limited: "Zu viele Versuche. Bitte warten Sie 15 Minuten.",
      mismatch: "Die neuen Passwörter stimmen nicht überein.",
    },
  },
  privacy: {
    title: "Newsletter & Datenschutz",
    newsletterTitle: "Newsletter",
    newsletterDisabled: "Dieser Shop versendet derzeit keinen Newsletter.",
    status: {
      active: "Sie haben den Newsletter abonniert.",
      pending: "Fast geschafft — bitte prüfen Sie Ihr Postfach und bestätigen Sie Ihr Abonnement.",
      unsubscribed: "Sie haben den Newsletter nicht abonniert.",
      none: "Sie haben den Newsletter nicht abonniert.",
    },
    subscribe: "Abonnieren",
    unsubscribe: "Abbestellen",
    resend: "Bestätigungs-E-Mail erneut senden",
    subscribedPending: "Wir haben Ihnen eine E-Mail gesendet. Klicken Sie auf die Schaltfläche darin, um Ihr Abonnement zu bestätigen.",
    unsubscribed: "Sie haben den Newsletter abbestellt.",
    newsletterUnavailable: "Der Newsletter ist derzeit nicht verfügbar.",
    deleteTitle: "Kundenkonto löschen",
    deleteIntro:
      "Beim Löschen Ihres Kundenkontos werden Ihr Profil, Ihre gespeicherten Adressen, Ihre Merkliste und Ihr Newsletter-Abonnement entfernt. Ihre Bestellungen bleiben (anonymisiert) erhalten, da wir gesetzlich verpflichtet sind, unsere Buchhaltung 7 Jahre aufzubewahren.",
    deleteButton: "Mein Kundenkonto löschen",
    deleteDialogTitle: "Ihr Kundenkonto löschen?",
    deleteDialogBody: "Dies kann nicht rückgängig gemacht werden. Geben Sie zur Bestätigung Ihr Passwort ein.",
    deleteConfirm: "Ja, mein Kundenkonto löschen",
    deleteErrors: {
      invalid_password: "Ihr Passwort ist falsch.",
      rate_limited: "Zu viele Versuche. Bitte warten Sie 15 Minuten.",
    },
  },
  wishlist: wishlistCopyDe,
  menu: {
    login: "Anmelden",
    register: "Konto erstellen",
    account: "Mein Konto",
    openMenu: "Kontomenü",
    signedInAs: "Angemeldet als",
  },
  newsletter: {
    title: "Newsletter",
    confirmTitle: "Abonnement bestätigen",
    confirmIntro: "Klicken Sie auf die Schaltfläche unten, um zu bestätigen, dass Sie unseren Newsletter erhalten möchten.",
    confirmButton: "Abonnement bestätigen",
    confirming: "Wird bestätigt…",
    missingToken: "Für diese Seite benötigen Sie den Link aus Ihrer Bestätigungs-E-Mail.",
    status: {
      confirmed: { title: "Sie sind angemeldet", body: "Vielen Dank für Ihre Bestätigung. Sie erhalten unseren nächsten Newsletter." },
      expired: { title: "Link abgelaufen", body: "Dieser Bestätigungslink ist abgelaufen. Bitte melden Sie sich erneut an, um einen neuen zu erhalten." },
      invalid: {
        title: "Link ungültig",
        body: "Dieser Bestätigungslink ist ungültig oder wurde bereits verwendet. Wenn Sie bereits bestätigt haben, sind Sie angemeldet.",
      },
      unsubscribed: { title: "Sie sind abgemeldet", body: "Sie erhalten unseren Newsletter nicht mehr." },
      unknown: { title: "Newsletter", body: "Melden Sie sich in der Fußzeile jeder Seite an, um unseren Newsletter zu erhalten." },
    },
    backHome: "Zurück zum Shop",
  },
};
