/** English copy for customer accounts, auth pages, wishlist and newsletter pages (multi-language later). */
export const accountCopy = {
  common: {
    email: "Email address",
    password: "Password",
    name: "Full name",
    phone: "Phone (optional)",
    save: "Save changes",
    saving: "Saving…",
    saved: "Saved.",
    cancel: "Cancel",
    unexpected: "Something went wrong. Please try again.",
    rateLimited: "Too many attempts. Please wait a few minutes and try again.",
    required: "This field is required.",
    loading: "Loading…",
  },
  login: {
    title: "Log in",
    intro: "Welcome back. Log in to see your orders, addresses and wishlist.",
    submit: "Log in",
    submitting: "Logging in…",
    forgot: "Forgot your password?",
    noAccount: "New here?",
    createAccount: "Create an account",
    resetDone: "Your password has been changed. You can log in now.",
    deleted: "Your account has been deleted.",
    errors: {
      missing: "Enter your email address and password.",
      invalid_credentials: "Incorrect email address or password.",
      rate_limited: "Too many login attempts. Please wait 15 minutes and try again.",
      disabled: "This account has been disabled. Please contact the shop.",
    },
  },
  twoFactor: {
    title: "Two-step verification",
    intro: "Enter the 6-digit code from your authenticator app, or one of your recovery codes.",
    code: "Verification code",
    submit: "Verify",
    submitting: "Verifying…",
    restart: "Start over",
    errors: {
      missing: "Enter your verification code.",
      invalid_code: "That code is not valid. Try again.",
      rate_limited: "Too many attempts. Please log in again.",
      no_pending_session: "Your login session expired. Please log in again.",
    },
  },
  register: {
    title: "Create an account",
    intro: "Track your orders, save addresses for a faster checkout and keep a wishlist.",
    submit: "Create account",
    submitting: "Creating account…",
    passwordHint: (min: number) => `At least ${min} characters.`,
    newsletter: "Send me the newsletter (you will get an email to confirm).",
    haveAccount: "Already have an account?",
    login: "Log in",
    privacy: "We only use your details to process your orders and run your account.",
    errors: {
      email_taken: "An account with this email address already exists. Log in or reset your password.",
      invalid: "Please check the highlighted fields.",
      rate_limited: "Too many sign-ups from your connection. Please try again later.",
    },
  },
  forgot: {
    title: "Forgot your password?",
    intro: "Enter the email address of your account and we will send you a link to choose a new password.",
    submit: "Send reset link",
    submitting: "Sending…",
    sent: "If an account exists for that address, we have sent a link to reset your password. The link is valid for 30 minutes.",
    back: "Back to log in",
    missing: "Enter your email address.",
  },
  reset: {
    title: "Choose a new password",
    newPassword: "New password",
    confirm: "Repeat new password",
    submit: "Set new password",
    submitting: "Saving…",
    mismatch: "The passwords do not match.",
    invalidToken: "This reset link is invalid or has expired. Request a new one.",
    requestNew: "Request a new link",
    missingToken: "This page needs the link from your password reset email.",
  },
  account: {
    title: "My account",
    nav: {
      label: "Account",
      overview: "Overview",
      orders: "Orders",
      addresses: "Addresses",
      wishlist: "Wishlist",
      profile: "Profile & password",
      privacy: "Newsletter & privacy",
      logout: "Log out",
    },
    greeting: (name: string | null) => (name ? `Hello, ${name}` : "Hello"),
    recentOrders: "Recent orders",
    allOrders: "All orders",
    noOrders: "You have not placed any orders yet.",
    startShopping: "Browse the shop",
    defaultAddress: "Default shipping address",
    noAddress: "No address saved yet.",
    manageAddresses: "Manage addresses",
    wishlistCount: (n: number) => (n === 1 ? "1 item on your wishlist" : `${n} items on your wishlist`),
    viewWishlist: "View wishlist",
    unverified: "Email address not verified yet.",
  },
  orders: {
    title: "Orders",
    number: "Order",
    date: "Date",
    status: "Status",
    total: "Total",
    items: (n: number) => (n === 1 ? "1 item" : `${n} items`),
    view: "View order",
    empty: "No orders yet.",
  },
  addresses: {
    title: "Addresses",
    add: "Add address",
    edit: "Edit address",
    newTitle: "New address",
    editTitle: "Edit address",
    empty: "You have no saved addresses yet.",
    default: "Default",
    makeDefault: "Make default",
    remove: "Delete",
    removeConfirm: "Delete this address?",
    shipping: "Shipping",
    billing: "Billing",
    type: "Address type",
    isDefault: "Use as default for this type",
    limit: "You have reached the maximum number of saved addresses.",
    notFound: "This address no longer exists.",
    fields: {
      firstName: "First name",
      lastName: "Last name",
      company: "Company (optional)",
      street: "Street",
      houseNumber: "House number",
      line2: "Apartment, suite, etc. (optional)",
      postalCode: "Postal code",
      city: "City",
      region: "State / province (optional)",
      countryCode: "Country",
      phone: "Phone (optional)",
    },
    save: "Save address",
    shipsTo: "We ship to",
    allCountries: "All countries",
    back: "Back to addresses",
  },
  profile: {
    title: "Profile & password",
    details: "Your details",
    detailsSaved: "Your details have been saved.",
    emailTitle: "Email address",
    emailIntro: "This is the address you log in with and where we send order emails.",
    newEmail: "New email address",
    currentPassword: "Current password",
    changeEmail: "Change email",
    emailChanged: "Your email address has been changed.",
    emailErrors: {
      invalid_email: "Enter a valid email address.",
      invalid_password: "Your current password is incorrect.",
      rate_limited: "Too many attempts. Please wait 15 minutes.",
      email_taken: "Another account already uses this email address.",
      unchanged: "That is already your email address.",
    },
    passwordTitle: "Change password",
    newPassword: "New password",
    confirmPassword: "Repeat new password",
    changePassword: "Change password",
    passwordChanged: "Your password has been changed. Other devices have been logged out.",
    passwordErrors: {
      invalid_current_password: "Your current password is incorrect.",
      invalid_password: "Choose a stronger password.",
      rate_limited: "Too many attempts. Please wait 15 minutes.",
      mismatch: "The new passwords do not match.",
    },
  },
  privacy: {
    title: "Newsletter & privacy",
    newsletterTitle: "Newsletter",
    newsletterDisabled: "This shop does not send a newsletter at the moment.",
    status: {
      active: "You are subscribed to the newsletter.",
      pending: "Almost done — check your inbox and confirm your subscription.",
      unsubscribed: "You are not subscribed to the newsletter.",
      none: "You are not subscribed to the newsletter.",
    },
    subscribe: "Subscribe",
    unsubscribe: "Unsubscribe",
    resend: "Send the confirmation email again",
    subscribedPending: "We have sent you an email. Click the button in it to confirm your subscription.",
    unsubscribed: "You have been unsubscribed.",
    newsletterUnavailable: "The newsletter is not available right now.",
    deleteTitle: "Delete account",
    deleteIntro:
      "Deleting your account removes your profile, saved addresses, wishlist and newsletter subscription. Orders you placed are kept (anonymized) because we are legally required to keep our bookkeeping for 7 years.",
    deleteButton: "Delete my account",
    deleteDialogTitle: "Delete your account?",
    deleteDialogBody: "This cannot be undone. Enter your password to confirm.",
    deleteConfirm: "Yes, delete my account",
    deleteErrors: {
      invalid_password: "Your password is incorrect.",
      rate_limited: "Too many attempts. Please wait 15 minutes.",
    },
  },
  wishlist: {
    title: "Wishlist",
    intro: "Items you saved. Every item is unique — once it is sold, it is gone.",
    empty: "Your wishlist is empty.",
    emptyHint: "Tap the heart on any item to save it here.",
    browse: "Browse the shop",
    add: "Add to wishlist",
    remove: "Remove from wishlist",
    saved: "Saved",
    save: "Save",
    loginToSave: "Log in to save items to your wishlist",
    available: "Available",
    reserved: "Reserved",
    sold: "Sold",
    addedOn: "Saved on",
    error: "Could not update your wishlist. Please try again.",
  },
  menu: {
    login: "Log in",
    register: "Create account",
    account: "My account",
    openMenu: "Account menu",
    signedInAs: "Signed in as",
  },
  newsletter: {
    title: "Newsletter",
    confirmTitle: "Confirm your subscription",
    confirmIntro: "Click the button below to confirm that you want to receive our newsletter.",
    confirmButton: "Confirm subscription",
    confirming: "Confirming…",
    missingToken: "This page needs the link from your confirmation email.",
    status: {
      confirmed: { title: "You are subscribed", body: "Thank you for confirming. You will receive our next newsletter." },
      expired: { title: "Link expired", body: "This confirmation link has expired. Please sign up again to receive a new one." },
      invalid: {
        title: "Link not valid",
        body: "This confirmation link is invalid or has already been used. If you already confirmed, you are subscribed.",
      },
      unsubscribed: { title: "You are unsubscribed", body: "You will no longer receive our newsletter." },
      unknown: { title: "Newsletter", body: "Sign up in the footer of any page to receive our newsletter." },
    },
    backHome: "Back to the shop",
  },
} as const;
