import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { accountCopy } from "./_copy";
import { wishlistCopyNl } from "./_copy-wishlist.nl";

export const accountCopyNl: CopyShape<typeof accountCopy> = {
  common: {
    email: "E-mailadres",
    password: "Wachtwoord",
    name: "Volledige naam",
    phone: "Telefoon (optioneel)",
    save: "Wijzigingen opslaan",
    saving: "Opslaan…",
    saved: "Opgeslagen.",
    cancel: "Annuleren",
    unexpected: "Er ging iets mis. Probeer het opnieuw.",
    rateLimited: "Te veel pogingen. Wacht een paar minuten en probeer het opnieuw.",
    captcha: "We konden niet vaststellen dat u een mens bent. Probeer het opnieuw.",
    required: "Dit veld is verplicht.",
    loading: "Laden…",
  },
  login: {
    title: "Inloggen",
    intro: "Welkom terug. Log in om uw bestellingen, adressen en verlanglijst te bekijken.",
    submit: "Inloggen",
    submitting: "Inloggen…",
    forgot: "Wachtwoord vergeten?",
    noAccount: "Nieuw hier?",
    createAccount: "Account aanmaken",
    resetDone: "Uw wachtwoord is gewijzigd. U kunt nu inloggen.",
    deleted: "Uw account is verwijderd.",
    errors: {
      missing: "Vul uw e-mailadres en wachtwoord in.",
      invalid_credentials: "Onjuist e-mailadres of wachtwoord.",
      rate_limited: "Te veel inlogpogingen. Wacht 15 minuten en probeer het opnieuw.",
      disabled: "Dit account is uitgeschakeld. Neem contact op met de shop.",
    },
  },
  twoFactor: {
    title: "Verificatie in twee stappen",
    intro: "Vul de 6-cijferige code uit uw authenticator-app in, of een van uw herstelcodes.",
    code: "Verificatiecode",
    submit: "Verifiëren",
    submitting: "Verifiëren…",
    restart: "Opnieuw beginnen",
    errors: {
      missing: "Vul uw verificatiecode in.",
      invalid_code: "Die code is niet geldig. Probeer het opnieuw.",
      rate_limited: "Te veel pogingen. Log opnieuw in.",
      no_pending_session: "Uw inlogsessie is verlopen. Log opnieuw in.",
    },
  },
  register: {
    title: "Account aanmaken",
    intro: "Volg uw bestellingen, bewaar adressen voor sneller afrekenen en houd een verlanglijst bij.",
    submit: "Account aanmaken",
    submitting: "Account aanmaken…",
    passwordHint: (min: number) => `Minimaal ${min} tekens.`,
    newsletter: "Stuur mij de nieuwsbrief (u ontvangt een e-mail ter bevestiging).",
    haveAccount: "Heeft u al een account?",
    login: "Inloggen",
    privacy: "We gebruiken uw gegevens alleen om uw bestellingen te verwerken en uw account te beheren.",
    errors: {
      email_taken: "Er bestaat al een account met dit e-mailadres. Log in of stel uw wachtwoord opnieuw in.",
      invalid: "Controleer de gemarkeerde velden.",
      rate_limited: "Te veel registraties vanaf uw verbinding. Probeer het later opnieuw.",
    },
  },
  forgot: {
    title: "Wachtwoord vergeten?",
    intro: "Vul het e-mailadres van uw account in en we sturen u een link om een nieuw wachtwoord te kiezen.",
    submit: "Herstellink versturen",
    submitting: "Versturen…",
    sent: "Als er een account bestaat voor dit adres, hebben we een link gestuurd om uw wachtwoord opnieuw in te stellen. De link is 30 minuten geldig.",
    back: "Terug naar inloggen",
    missing: "Vul uw e-mailadres in.",
  },
  reset: {
    title: "Kies een nieuw wachtwoord",
    newPassword: "Nieuw wachtwoord",
    confirm: "Herhaal nieuw wachtwoord",
    submit: "Nieuw wachtwoord instellen",
    submitting: "Opslaan…",
    mismatch: "De wachtwoorden komen niet overeen.",
    invalidToken: "Deze herstellink is ongeldig of verlopen. Vraag een nieuwe aan.",
    requestNew: "Nieuwe link aanvragen",
    missingToken: "Voor deze pagina heeft u de link uit de e-mail voor het herstellen van uw wachtwoord nodig.",
  },
  account: {
    title: "Mijn account",
    nav: {
      label: "Account",
      overview: "Overzicht",
      orders: "Bestellingen",
      addresses: "Adressen",
      wishlist: "Verlanglijst",
      alerts: "Meldingen",
      profile: "Profiel & wachtwoord",
      privacy: "Nieuwsbrief & privacy",
      logout: "Uitloggen",
    },
    greeting: (name: string | null) => (name ? `Hallo, ${name}` : "Hallo"),
    recentOrders: "Recente bestellingen",
    allOrders: "Alle bestellingen",
    noOrders: "U heeft nog geen bestellingen geplaatst.",
    startShopping: "Bekijk de shop",
    defaultAddress: "Standaard verzendadres",
    noAddress: "Nog geen adres opgeslagen.",
    manageAddresses: "Adressen beheren",
    wishlistCount: (n: number) => (n === 1 ? "1 item op uw verlanglijst" : `${n.toLocaleString("nl-NL")} items op uw verlanglijst`),
    viewWishlist: "Verlanglijst bekijken",
    unverified: "E-mailadres nog niet bevestigd.",
  },
  orders: {
    title: "Bestellingen",
    number: "Bestelling",
    date: "Datum",
    status: "Status",
    total: "Totaal",
    items: (n: number) => (n === 1 ? "1 item" : `${n.toLocaleString("nl-NL")} items`),
    view: "Bestelling bekijken",
    empty: "Nog geen bestellingen.",
    statuses: {
      canceled: "Geannuleerd",
      payment_failed: "Betaling mislukt",
      payment_expired: "Betaling verlopen",
      refunded: "Terugbetaald",
      partially_refunded: "Deels terugbetaald",
      awaiting_payment: "Wacht op betaling",
      delivered: "Bezorgd",
      shipped: "Verzonden",
      packed: "Ingepakt",
      processing: "Betaald — in behandeling",
    },
  },
  addresses: {
    title: "Adressen",
    add: "Adres toevoegen",
    edit: "Adres bewerken",
    newTitle: "Nieuw adres",
    editTitle: "Adres bewerken",
    empty: "U heeft nog geen opgeslagen adressen.",
    default: "Standaard",
    makeDefault: "Als standaard instellen",
    remove: "Verwijderen",
    removeConfirm: "Dit adres verwijderen?",
    shipping: "Verzending",
    billing: "Facturering",
    type: "Soort adres",
    isDefault: "Als standaard gebruiken voor dit soort",
    limit: "U heeft het maximale aantal opgeslagen adressen bereikt.",
    notFound: "Dit adres bestaat niet meer.",
    fields: {
      firstName: "Voornaam",
      lastName: "Achternaam",
      company: "Bedrijf (optioneel)",
      street: "Straat",
      houseNumber: "Huisnummer",
      line2: "Toevoeging, appartement, enz. (optioneel)",
      postalCode: "Postcode",
      city: "Plaats",
      region: "Provincie / staat (optioneel)",
      countryCode: "Land",
      phone: "Telefoon (optioneel)",
    },
    save: "Adres opslaan",
    shipsTo: "We verzenden naar",
    allCountries: "Alle landen",
    back: "Terug naar adressen",
  },
  profile: {
    title: "Profiel & wachtwoord",
    details: "Uw gegevens",
    detailsSaved: "Uw gegevens zijn opgeslagen.",
    emailTitle: "E-mailadres",
    emailIntro: "Met dit adres logt u in en hierheen sturen we e-mails over uw bestellingen.",
    newEmail: "Nieuw e-mailadres",
    currentPassword: "Huidig wachtwoord",
    changeEmail: "E-mailadres wijzigen",
    emailChanged: "Uw e-mailadres is gewijzigd.",
    emailErrors: {
      invalid_email: "Vul een geldig e-mailadres in.",
      invalid_password: "Uw huidige wachtwoord is onjuist.",
      rate_limited: "Te veel pogingen. Wacht 15 minuten.",
      email_taken: "Een ander account gebruikt dit e-mailadres al.",
      unchanged: "Dat is al uw e-mailadres.",
    },
    passwordTitle: "Wachtwoord wijzigen",
    newPassword: "Nieuw wachtwoord",
    confirmPassword: "Herhaal nieuw wachtwoord",
    changePassword: "Wachtwoord wijzigen",
    passwordChanged: "Uw wachtwoord is gewijzigd. Andere apparaten zijn uitgelogd.",
    passwordErrors: {
      invalid_current_password: "Uw huidige wachtwoord is onjuist.",
      invalid_password: "Kies een sterker wachtwoord.",
      rate_limited: "Te veel pogingen. Wacht 15 minuten.",
      mismatch: "De nieuwe wachtwoorden komen niet overeen.",
    },
  },
  privacy: {
    title: "Nieuwsbrief & privacy",
    newsletterTitle: "Nieuwsbrief",
    newsletterDisabled: "Deze shop verstuurt op dit moment geen nieuwsbrief.",
    status: {
      active: "U bent ingeschreven voor de nieuwsbrief.",
      pending: "Bijna klaar — kijk in uw inbox en bevestig uw inschrijving.",
      unsubscribed: "U bent niet ingeschreven voor de nieuwsbrief.",
      none: "U bent niet ingeschreven voor de nieuwsbrief.",
    },
    subscribe: "Inschrijven",
    unsubscribe: "Uitschrijven",
    resend: "Bevestigingsmail opnieuw versturen",
    subscribedPending: "We hebben u een e-mail gestuurd. Klik op de knop in die e-mail om uw inschrijving te bevestigen.",
    unsubscribed: "U bent uitgeschreven.",
    newsletterUnavailable: "De nieuwsbrief is op dit moment niet beschikbaar.",
    deleteTitle: "Account verwijderen",
    deleteIntro:
      "Als u uw account verwijdert, worden uw profiel, opgeslagen adressen, verlanglijst en nieuwsbriefinschrijving gewist. Uw geplaatste bestellingen blijven (geanonimiseerd) bewaard, omdat we wettelijk verplicht zijn onze boekhouding 7 jaar te bewaren.",
    deleteButton: "Mijn account verwijderen",
    deleteDialogTitle: "Uw account verwijderen?",
    deleteDialogBody: "Dit kan niet ongedaan worden gemaakt. Vul uw wachtwoord in om te bevestigen.",
    deleteConfirm: "Ja, verwijder mijn account",
    deleteErrors: {
      invalid_password: "Uw wachtwoord is onjuist.",
      rate_limited: "Te veel pogingen. Wacht 15 minuten.",
    },
  },
  wishlist: wishlistCopyNl,
  menu: {
    login: "Inloggen",
    register: "Account aanmaken",
    account: "Mijn account",
    openMenu: "Accountmenu",
    signedInAs: "Ingelogd als",
  },
  newsletter: {
    title: "Nieuwsbrief",
    confirmTitle: "Bevestig uw inschrijving",
    confirmIntro: "Klik op de knop hieronder om te bevestigen dat u onze nieuwsbrief wilt ontvangen.",
    confirmButton: "Inschrijving bevestigen",
    confirming: "Bevestigen…",
    missingToken: "Voor deze pagina heeft u de link uit uw bevestigingsmail nodig.",
    status: {
      confirmed: { title: "U bent ingeschreven", body: "Bedankt voor uw bevestiging. U ontvangt onze volgende nieuwsbrief." },
      expired: { title: "Link verlopen", body: "Deze bevestigingslink is verlopen. Schrijf u opnieuw in om een nieuwe te ontvangen." },
      invalid: {
        title: "Link niet geldig",
        body: "Deze bevestigingslink is ongeldig of al gebruikt. Als u al heeft bevestigd, bent u ingeschreven.",
      },
      unsubscribed: { title: "U bent uitgeschreven", body: "U ontvangt onze nieuwsbrief niet meer." },
      unknown: { title: "Nieuwsbrief", body: "Schrijf u in via de voettekst van elke pagina om onze nieuwsbrief te ontvangen." },
    },
    backHome: "Terug naar de shop",
  },
};
