import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { layoutCopy } from "./_copy";

export const layoutCopyDe: CopyShape<typeof layoutCopy> = {
  skipToContent: "Zum Inhalt springen",
  header: {
    homeLabel: "Startseite",
    mainNav: "Hauptmenü",
    openMenu: "Menü öffnen",
    closeMenu: "Menü schließen",
    menu: "Menü",
    search: "Suchen",
    searchPlaceholder: "Im Shop suchen…",
    searchLabel: "Artikel suchen",
    account: "Kundenkonto",
    wishlist: "Merkliste",
    cart: "Warenkorb",
    cartCount: (n: number) => (n === 1 ? "1 Artikel im Warenkorb" : `${n} Artikel im Warenkorb`),
    wishlistCount: (n: number) => (n === 1 ? "1 gemerkter Artikel" : `${n} gemerkte Artikel`),
    shop: "Shop",
  },
  miniCart: {
    label: "Warenkorb-Vorschau",
    title: (n: number) => (n === 1 ? "1 Artikel in Ihrem Warenkorb" : `${n} Artikel in Ihrem Warenkorb`),
    reserved: (min: number) => (min <= 1 ? "Reserviert für <1 Min." : `Reserviert für ${min} Min.`),
    empty: "Ihr Warenkorb ist leer",
    emptyHint: "Jedes Stück ist ein Unikat — legen Sie es in den Warenkorb, bevor es jemand anderes tut.",
    browse: "Zum Shop",
    taken: "Von jemand anderem reserviert",
    unavailable: "Nicht mehr verfügbar",
    more: (n: number) => `+ ${n} weitere in Ihrem Warenkorb`,
    subtotal: "Zwischensumme",
    viewCart: "Warenkorb ansehen",
    checkout: "Zur Kasse",
  },
  footer: {
    navLabel: "Fußzeile",
    newsletterTitle: "Newsletter",
    newsletterText: "Neuzugänge und Geschichten aus der Sammlung, direkt in Ihr Postfach.",
    contact: "Kontakt",
    poweredBy: "Betrieben mit",
    soldArchive: "Archiv",
    legal: "Rechtliches",
    rights: "Alle Rechte vorbehalten.",
  },
  newsletter: {
    emailLabel: "E-Mail-Adresse",
    placeholder: "sie@beispiel.de",
    submit: "Abonnieren",
    submitting: "Wird abonniert…",
    success: "Vielen Dank! Bitte prüfen Sie Ihr Postfach, um Ihr Abonnement zu bestätigen.",
    invalid: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    unavailable: "Die Anmeldung ist derzeit nicht möglich. Bitte versuchen Sie es später erneut.",
    tooMany: "Zu viele Versuche. Bitte versuchen Sie es später erneut.",
    captcha: "Wir konnten nicht bestätigen, dass Sie ein Mensch sind. Bitte versuchen Sie es erneut.",
    honeypot: "Dieses Feld bitte leer lassen",
  },
  openingSoon: {
    eyebrow: "Bald geöffnet",
    body: "Wir bereiten unseren Shop gerade vor. Bitte schauen Sie bald wieder vorbei.",
    notify: "Hinterlassen Sie Ihre E-Mail-Adresse, und wir benachrichtigen Sie, sobald wir öffnen.",
    questions: "Fragen?",
  },
  ageGate: {
    title: (age: number) => `Sind Sie ${age} Jahre oder älter?`,
    body: (shop: string, age: number) =>
      `${shop} verkauft Artikel, die ausschließlich für Erwachsene bestimmt sind. Bitte bestätigen Sie, dass Sie mindestens ${age} Jahre alt sind, um fortzufahren.`,
    confirm: (age: number) => `Ja, ich bin ${age} Jahre oder älter`,
    leave: "Nein, verlassen",
    denied: (age: number) => `Leider müssen Sie mindestens ${age} Jahre alt sein, um diesen Shop zu besuchen.`,
  },
};
