import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { layoutCopy } from "./_copy";

export const layoutCopyNl: CopyShape<typeof layoutCopy> = {
  skipToContent: "Naar de inhoud",
  header: {
    homeLabel: "home",
    mainNav: "Hoofdmenu",
    openMenu: "Menu openen",
    closeMenu: "Menu sluiten",
    menu: "Menu",
    search: "Zoeken",
    searchPlaceholder: "Zoek in de shop…",
    searchLabel: "Producten zoeken",
    account: "Account",
    wishlist: "Verlanglijst",
    cart: "Winkelwagen",
    cartCount: (n: number) => (n === 1 ? "1 item in winkelwagen" : `${n} items in winkelwagen`),
    wishlistCount: (n: number) => (n === 1 ? "1 bewaard item" : `${n} bewaarde items`),
    shop: "Shop",
  },
  miniCart: {
    label: "Voorbeeld winkelwagen",
    title: (n: number) => (n === 1 ? "1 item in uw winkelwagen" : `${n} items in uw winkelwagen`),
    reserved: (min: number) => (min <= 1 ? "Gereserveerd voor <1 min" : `Gereserveerd voor ${min} min`),
    empty: "Uw winkelwagen is leeg",
    emptyHint: "Elk stuk is uniek — voeg het toe voordat een ander het doet.",
    browse: "Bekijk de shop",
    taken: "Gereserveerd door iemand anders",
    unavailable: "Niet meer beschikbaar",
    more: (n: number) => `+ nog ${n} in uw winkelwagen`,
    subtotal: "Subtotaal",
    viewCart: "Bekijk winkelwagen",
    checkout: "Afrekenen",
  },
  footer: {
    navLabel: "Voettekst",
    newsletterTitle: "Nieuwsbrief",
    newsletterText: "Nieuwe aanwinsten en verhalen uit de collectie, direct in uw inbox.",
    contact: "Contact",
    poweredBy: "Mogelijk gemaakt door",
    soldArchive: "Archief (verkocht)",
    legal: "Juridisch",
    rights: "Alle rechten voorbehouden.",
  },
  newsletter: {
    emailLabel: "E-mailadres",
    placeholder: "u@voorbeeld.nl",
    submit: "Aanmelden",
    submitting: "Bezig met aanmelden…",
    success: "Bedankt! Controleer uw inbox om uw aanmelding te bevestigen.",
    invalid: "Vul een geldig e-mailadres in.",
    unavailable: "Aanmelden is op dit moment niet mogelijk. Probeer het later opnieuw.",
    tooMany: "Te veel pogingen. Probeer het later opnieuw.",
    captcha: "We konden niet vaststellen dat u een mens bent. Probeer het opnieuw.",
    honeypot: "Laat dit veld leeg",
  },
  openingSoon: {
    eyebrow: "Binnenkort geopend",
    body: "We zijn onze shop aan het voorbereiden. Kom snel terug.",
    notify: "Laat uw e-mailadres achter, dan laten we u weten wanneer we opengaan.",
    questions: "Vragen?",
  },
  ageGate: {
    title: (age: number) => `Bent u ${age} jaar of ouder?`,
    body: (shop: string, age: number) =>
      `${shop} verkoopt artikelen die uitsluitend bedoeld zijn voor volwassenen. Bevestig dat u minstens ${age} jaar oud bent om verder te gaan.`,
    confirm: (age: number) => `Ja, ik ben ${age} jaar of ouder`,
    leave: "Nee, verlaten",
    denied: (age: number) => `Sorry, u moet ${age} jaar of ouder zijn om deze shop te bezoeken.`,
  },
};
