// GENERATED by scripts/fonts/sync-shop-fonts.ts (npm run fonts:sync) — do not edit by hand.
// Files live in public/fonts/shop/ (content-hashed names, served immutable).

export type ShopFontFace = { subset: "latin" | "latin-ext"; style: string; weight: string; unicodeRange: string; src: string };
export type ShopFontFallback = { font: string; ascent: string; descent: string; lineGap: string; sizeAdjust: string };

export const SHOP_FONT_FACES = {
  "Inter": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/inter-latin-ext-normal-100-900.a28eb6d3cc.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/inter-latin-normal-100-900.c940764593.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "90.44%",
      "descent": "22.52%",
      "lineGap": "0.00%",
      "sizeAdjust": "107.12%"
    }
  },
  "Roboto": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/roboto-latin-ext-normal-100-900.cdd53dc557.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/roboto-latin-normal-100-900.0a44e0bb6b.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "92.98%",
      "descent": "24.47%",
      "lineGap": "0.00%",
      "sizeAdjust": "99.78%"
    }
  },
  "Open Sans": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "300 800",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/open-sans-latin-ext-normal-300-800.2d4c25a2a2.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "300 800",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/open-sans-latin-normal-300-800.441af0def9.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "101.65%",
      "descent": "27.86%",
      "lineGap": "0.00%",
      "sizeAdjust": "105.15%"
    }
  },
  "Lato": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/lato-latin-ext-normal-400.b85c84c655.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/lato-latin-normal-400.d4ae5188a6.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/lato-latin-ext-normal-700.78e850d569.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/lato-latin-normal-700.7a7ce1a34f.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "101.03%",
      "descent": "21.80%",
      "lineGap": "0.00%",
      "sizeAdjust": "97.69%"
    }
  },
  "Montserrat": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/montserrat-latin-ext-normal-100-900.920711de9a.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/montserrat-latin-normal-100-900.6438d7b8ea.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "85.79%",
      "descent": "22.25%",
      "lineGap": "0.00%",
      "sizeAdjust": "112.83%"
    }
  },
  "Oswald": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "200 700",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/oswald-latin-ext-normal-200-700.387bb9ea91.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "200 700",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/oswald-latin-normal-200-700.c36937da4c.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "146.51%",
      "descent": "35.49%",
      "lineGap": "0.00%",
      "sizeAdjust": "81.43%"
    }
  },
  "Bebas Neue": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/bebas-neue-latin-ext-normal-400.a724a4b6a8.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/bebas-neue-latin-normal-400.441b026df2.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "117.32%",
      "descent": "39.11%",
      "lineGap": "0.00%",
      "sizeAdjust": "76.72%"
    }
  },
  "IBM Plex Sans": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 700",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/ibm-plex-sans-latin-ext-normal-100-700.ae1d854fef.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 700",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/ibm-plex-sans-latin-normal-100-700.056e4e2459.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "101.32%",
      "descent": "27.18%",
      "lineGap": "0.00%",
      "sizeAdjust": "101.17%"
    }
  },
  "IBM Plex Serif": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/ibm-plex-serif-latin-ext-normal-400.836fd31988.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/ibm-plex-serif-latin-normal-400.9fbb32c4c0.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "600",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/ibm-plex-serif-latin-ext-normal-600.af27611d0c.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "600",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/ibm-plex-serif-latin-normal-600.d8bf89a58f.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "700",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/ibm-plex-serif-latin-ext-normal-700.c0d6feef8e.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "700",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/ibm-plex-serif-latin-normal-700.8d256fda8c.woff2"
      }
    ],
    "fallback": {
      "font": "Times New Roman",
      "ascent": "88.04%",
      "descent": "23.62%",
      "lineGap": "0.00%",
      "sizeAdjust": "116.43%"
    }
  },
  "Merriweather": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "300 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/merriweather-latin-ext-normal-300-900.f66e5c1890.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "300 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/merriweather-latin-normal-300-900.af1be39e2f.woff2"
      }
    ],
    "fallback": {
      "font": "Times New Roman",
      "ascent": "80.59%",
      "descent": "22.36%",
      "lineGap": "0.00%",
      "sizeAdjust": "122.09%"
    }
  },
  "Playfair Display": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/playfair-display-latin-ext-normal-400-900.5628567856.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/playfair-display-latin-normal-400-900.5d91eb5d52.woff2"
      }
    ],
    "fallback": {
      "font": "Times New Roman",
      "ascent": "97.25%",
      "descent": "22.56%",
      "lineGap": "0.00%",
      "sizeAdjust": "111.26%"
    }
  },
  "Libre Baskerville": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 700",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/libre-baskerville-latin-ext-normal-400-700.1b43b44b58.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 700",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/libre-baskerville-latin-normal-400-700.b62b98ef69.woff2"
      }
    ],
    "fallback": {
      "font": "Times New Roman",
      "ascent": "76.22%",
      "descent": "21.22%",
      "lineGap": "0.00%",
      "sizeAdjust": "127.26%"
    }
  },
  "EB Garamond": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400 800",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/eb-garamond-latin-ext-normal-400-800.c2fa6862b0.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400 800",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/eb-garamond-latin-normal-400-800.68fd4b247d.woff2"
      }
    ],
    "fallback": {
      "font": "Times New Roman",
      "ascent": "106.26%",
      "descent": "31.44%",
      "lineGap": "0.00%",
      "sizeAdjust": "94.77%"
    }
  },
  "Cormorant Garamond": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "300 700",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/cormorant-garamond-latin-ext-normal-300-700.9dc38267bd.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "300 700",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/cormorant-garamond-latin-normal-300-700.5d618c462b.woff2"
      }
    ],
    "fallback": {
      "font": "Times New Roman",
      "ascent": "95.27%",
      "descent": "29.59%",
      "lineGap": "0.00%",
      "sizeAdjust": "96.98%"
    }
  },
  "Source Serif 4": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "200 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/source-serif-4-latin-ext-normal-200-900.231f594ad8.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "200 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/source-serif-4-latin-normal-200-900.8e38e3fbd7.woff2"
      }
    ],
    "fallback": {
      "font": "Times New Roman",
      "ascent": "87.87%",
      "descent": "28.41%",
      "lineGap": "0.00%",
      "sizeAdjust": "117.91%"
    }
  },
  "Special Elite": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/special-elite-latin-ext-normal-400.491120b4e1.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/special-elite-latin-normal-400.3cf0677184.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "60.00%",
      "descent": "25.33%",
      "lineGap": "0.00%",
      "sizeAdjust": "117.20%"
    }
  },
  "Hanken Grotesk": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/hanken-grotesk-latin-ext-normal-100-900.a1376a5637.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/hanken-grotesk-latin-normal-100-900.1f21c6eaa0.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "99.07%",
      "descent": "30.02%",
      "lineGap": "0.00%",
      "sizeAdjust": "100.94%"
    }
  },
  "Instrument Serif": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "400",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/instrument-serif-latin-ext-italic-400.a04fc7ed18.woff2"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "400",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/instrument-serif-latin-italic-400.6ee678c33f.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/instrument-serif-latin-ext-normal-400.a8c4bd7cd7.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/instrument-serif-latin-normal-400.60c06664b5.woff2"
      }
    ],
    "fallback": {
      "font": "Times New Roman",
      "ascent": "117.94%",
      "descent": "36.93%",
      "lineGap": "0.00%",
      "sizeAdjust": "83.94%"
    }
  },
  "Newsreader": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "italic",
        "weight": "200 800",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/newsreader-latin-ext-italic-200-800.0a65822f4b.woff2"
      },
      {
        "subset": "latin",
        "style": "italic",
        "weight": "200 800",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/newsreader-latin-italic-200-800.19a83cc7ce.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "200 800",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/newsreader-latin-ext-normal-200-800.fe52554ab1.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "200 800",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/newsreader-latin-normal-200-800.2a69ec1c0f.woff2"
      }
    ],
    "fallback": {
      "font": "Times New Roman",
      "ascent": "69.68%",
      "descent": "25.12%",
      "lineGap": "0.00%",
      "sizeAdjust": "105.48%"
    }
  },
  "Archivo": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/archivo-latin-ext-normal-100-900.a999e009fd.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/archivo-latin-normal-100-900.7150c0ec5a.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "88.96%",
      "descent": "21.28%",
      "lineGap": "0.00%",
      "sizeAdjust": "98.70%"
    }
  },
  "Work Sans": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/work-sans-latin-ext-normal-100-900.fe0af300ce.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/work-sans-latin-normal-100-900.72cd8f6784.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "83.09%",
      "descent": "21.71%",
      "lineGap": "0.00%",
      "sizeAdjust": "111.93%"
    }
  },
  "Libre Caslon Display": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/libre-caslon-display-latin-ext-normal-400.d08b4179b0.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/libre-caslon-display-latin-normal-400.d7157ad185.woff2"
      }
    ],
    "fallback": {
      "font": "Times New Roman",
      "ascent": "105.36%",
      "descent": "28.89%",
      "lineGap": "0.00%",
      "sizeAdjust": "92.06%"
    }
  },
  "Big Shoulders": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/big-shoulders-latin-ext-normal-100-900.87283d1618.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "100 900",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/big-shoulders-latin-normal-100-900.5faff1f81e.woff2"
      }
    ],
    "fallback": null
  },
  "IBM Plex Mono": {
    "faces": [
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/ibm-plex-mono-latin-ext-normal-400.f1050dc531.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "400",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/ibm-plex-mono-latin-normal-400.c36f509c0a.woff2"
      },
      {
        "subset": "latin-ext",
        "style": "normal",
        "weight": "500",
        "unicodeRange": "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C4, U+2113, U+2C60-2C7F, U+A720-A7FF",
        "src": "/fonts/shop/ibm-plex-mono-latin-ext-normal-500.77f03e26f9.woff2"
      },
      {
        "subset": "latin",
        "style": "normal",
        "weight": "500",
        "unicodeRange": "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        "src": "/fonts/shop/ibm-plex-mono-latin-normal-500.a76f53ca66.woff2"
      }
    ],
    "fallback": {
      "font": "Arial",
      "ascent": "76.16%",
      "descent": "20.43%",
      "lineGap": "0.00%",
      "sizeAdjust": "134.59%"
    }
  }
} as const satisfies Record<string, { faces: readonly ShopFontFace[]; fallback: ShopFontFallback | null }>;
