import { SHOP_THEMES, type FONT_ALLOWLIST, type Settings } from "@/server/settings/schema";
import { shopThemeVars } from "@/server/storefront/theme";
import { fontFaceCss } from "@/lib/font-face-css";
import { SHOP_FONT_FACES } from "./font-faces.generated";

/*
 * Self-hosted storefront fonts (appearance.headingFont / textFont, FONT_ALLOWLIST, plus the theme's
 * accent and mono faces).
 *
 * Performance (docs/perf/round2.md): next/font put the @font-face rules of all 24 allowlisted families
 * into one render-blocking stylesheet on every shop page and could not preload per tenant. The files
 * now live in public/fonts/shop/ (woff2, latin + latin-ext, content-hashed names, served immutable;
 * generated by scripts/fonts/sync-fonts.ts with next/font's own helpers and fallback metrics).
 * The shop layout inlines @font-face rules for ONLY the 2–4 families the tenant's theme uses
 * (`shopFontFaceCss(shopFontsInUse(…))`, a few hundred bytes) and preloads the latin file of the body
 * and heading face (`shopFontPreloads`). `font-display: swap` with size-adjusted local fallbacks
 * ("QM Inter Fallback" = Arial with Inter's metrics) keeps text visible without layout shift.
 * The theme-builder preview loads other families on demand (ThemePreviewBridge, `shopFontTables`).
 */
type FontName = (typeof FONT_ALLOWLIST)[number];
type ShopTheme = (typeof SHOP_THEMES)[number];
/** Every family with self-hosted files: the allowlist plus the theme-owned mono face. */
export type ShopFaceFamily = keyof typeof SHOP_FONT_FACES;

const MONO: ShopFaceFamily = "IBM Plex Mono";

/** Accent (emphasis) family per theme preset. */
const THEME_ACCENT: Record<ShopTheme, FontName> = {
  gallery: "Instrument Serif",
  archive: "Newsreader",
  // Emphasis in Field Kit headings stays in the display face (accent colour instead of italics; see shop.css).
  fieldkit: "Big Shoulders",
  vault: "Libre Caslon Display",
};

/** `--shop-heading-weight` per theme (shop.css) — which heading face to preload. */
const THEME_HEADING_WEIGHT: Record<ShopTheme, number> = { gallery: 600, archive: 400, fieldkit: 800, vault: 400 };

const SERIF = new Set<FontName>(["Instrument Serif", "Newsreader", "Libre Caslon Display", "IBM Plex Serif", "Merriweather", "Playfair Display", "Libre Baskerville", "EB Garamond", "Cormorant Garamond", "Source Serif 4"]);

function hasFaces(name: string): name is ShopFaceFamily {
  return Object.hasOwn(SHOP_FONT_FACES, name);
}

/** Our own family names (prefixed so a locally installed copy of the font is never picked up instead). */
function ownFamilies(name: ShopFaceFamily): string {
  return SHOP_FONT_FACES[name].fallback ? `"QM ${name}", "QM ${name} Fallback"` : `"QM ${name}"`;
}

/** CSS font-family value for an allowlisted font, with a sensible generic fallback. */
export function shopFontFamily(name: FontName): string {
  const own = hasFaces(name) ? `${ownFamilies(name)}, ` : "";
  if (name === "Big Shoulders") return `${own}Impact, 'Arial Narrow', sans-serif`;
  return `${own}${SERIF.has(name) ? "Georgia, serif" : "system-ui, -apple-system, 'Segoe UI', sans-serif"}`;
}

/** Font roles a theme preset fixes (accent serif + mono), as CSS font-family values. */
export function shopThemeFontFamilies(theme: ShopTheme): { accent: string; mono: string } {
  return {
    accent: shopFontFamily(THEME_ACCENT[theme]),
    mono: `${ownFamilies(MONO)}, ui-monospace, SFMono-Regular, Menlo, monospace`,
  };
}

type AppearanceStyleInput = Pick<Settings<"appearance">, "theme" | "colors" | "headingFont" | "textFont" | "corners" | "buttonShape" | "density">;

/** Inline CSS variables for `.shop-root` from (live or draft) appearance settings. */
export function shopAppearanceStyle(appearance: AppearanceStyleInput): Record<`--${string}`, string> {
  const themeFonts = shopThemeFontFamilies(appearance.theme);
  return shopThemeVars({
    colors: appearance.colors,
    headingFontFamily: shopFontFamily(appearance.headingFont),
    textFontFamily: shopFontFamily(appearance.textFont),
    accentFontFamily: themeFonts.accent,
    monoFontFamily: themeFonts.mono,
    corners: appearance.corners,
    buttonShape: appearance.buttonShape,
    density: appearance.density,
  });
}

type FontsInput = Pick<Settings<"appearance">, "theme" | "headingFont" | "textFont">;

/** The families a shop with this appearance can render (heading, body, theme accent, mono). */
export function shopFontsInUse(appearance: FontsInput): ShopFaceFamily[] {
  const names = [appearance.headingFont, appearance.textFont, THEME_ACCENT[appearance.theme], MONO];
  return [...new Set(names)].filter(hasFaces);
}

/** @font-face rules (files + size-adjusted fallback) for the given families. */
export function shopFontFaceCss(families: readonly ShopFaceFamily[]): string {
  return families.map((name) => fontFaceCss(`QM ${name}`, SHOP_FONT_FACES[name])).join("");
}

function covers(weight: string, wanted: number): boolean {
  const [min, max = min] = weight.split(/\s+/).map(Number);
  return wanted >= min && wanted <= max;
}

/** The latin, upright file that renders `name` at `weight` (closest weight when none covers it). */
function latinFile(name: ShopFaceFamily, weight: number): string | undefined {
  const faces = SHOP_FONT_FACES[name].faces.filter((f) => f.subset === "latin" && f.style === "normal");
  const exact = faces.find((f) => covers(f.weight, weight));
  if (exact) return exact.src;
  return [...faces].sort((a, b) => Math.abs(Number(a.weight.split(" ")[0]) - weight) - Math.abs(Number(b.weight.split(" ")[0]) - weight))[0]?.src;
}

/**
 * Font files worth a `<link rel=preload>`: the latin body face (regular) and heading face (theme
 * heading weight). One or two files, usually 20–50 kB each; latin-ext/accent/mono load on use.
 */
export function shopFontPreloads(appearance: FontsInput): string[] {
  const files = [
    hasFaces(appearance.textFont) ? latinFile(appearance.textFont, 400) : undefined,
    hasFaces(appearance.headingFont) ? latinFile(appearance.headingFont, THEME_HEADING_WEIGHT[appearance.theme]) : undefined,
  ];
  return [...new Set(files.filter((f): f is string => !!f))];
}

/** Font tables for the theme-preview bridge (client side recomputes the vars on every builder change). */
export function shopFontTables(): {
  fonts: Record<FontName, string>;
  themes: Record<ShopTheme, { accent: string; mono: string; accentFont: FontName }>;
  faceCss: Record<string, string>;
} {
  const names = Object.keys(SHOP_FONT_FACES) as ShopFaceFamily[];
  const fonts = Object.fromEntries(names.filter((n) => n !== MONO).map((n) => [n, shopFontFamily(n as FontName)])) as Record<FontName, string>;
  const themes = Object.fromEntries(SHOP_THEMES.map((t) => [t, { ...shopThemeFontFamilies(t), accentFont: THEME_ACCENT[t] }])) as Record<
    ShopTheme,
    { accent: string; mono: string; accentFont: FontName }
  >;
  const faceCss = Object.fromEntries(names.map((n) => [n, shopFontFaceCss([n])]));
  return { fonts, themes, faceCss };
}
