import { fieldCopy } from "./_copy-field";

/** English copy for smart search (header combobox, results page, photo search, "looks like this"). */
export const searchCopy = {
  field: fieldCopy,
  panel: {
    label: "Suggestions",
    understood: "Understood as",
    filters: "Categories & filters",
    items: "Items",
    seeAll: (n: number, capped: boolean) => (n === 0 ? "Search for this" : `See all ${n.toLocaleString("en-IE")}${capped ? "+" : ""} ${n === 1 ? "result" : "results"}`),
    loading: "Searching…",
    none: "No direct matches — press Enter to search anyway.",
    itemsCount: (n: number) => `${n} ${n === 1 ? "item" : "items"}`,
    status: (n: number) => (n === 0 ? "No suggestions" : `${n} ${n === 1 ? "suggestion" : "suggestions"} available. Use the up and down arrows to browse.`),
    stockCode: (n: number) => `No. ${n}`,
    sold: "Sold",
  },
  results: {
    eyebrow: "Search",
    searchedFor: "We searched for",
    with: "with",
    searchedFilters: "We searched for",
    onlyFilters: "We listed items with",
    remove: (label: string) => `Remove filter ${label}`,
    literal: "Search the words literally instead",
    literalOn: (q: string) => `Searched literally for “${q}”.`,
    interpret: "Let the search understand the words",
    relaxed: "Nothing matched every filter we understood, so we searched the words instead.",
    bestFirst: "best matches first",
    nearTitle: "Close, but not all filters match",
    nearBody: (label: string, n: number) => `${n === 1 ? "This item matches" : "These items match"} everything except “${label}”.`,
    nearAll: (n: number) => `Show all ${n} without this filter`,
    zeroTitle: (q: string) => `Nothing found for “${q}”`,
    didYouMean: "Did you mean",
    tryWithout: "Try without",
    browse: "Browse a category",
    wholeShop: "Search the whole shop",
    tips: "Check the spelling, use fewer words, or search by stock number (e.g. 50212).",
  },
  photo: {
    title: "Search by photo",
    close: "Close",
    intro: "Find items that look like your photo.",
    drop: "Drop a photo here",
    paste: "or paste one (Ctrl+V / ⌘V)",
    choose: "Choose photo",
    take: "Take photo",
    privacy: "Your photo is not stored.",
    matched: "Matched on shape and colour.",
    busy: "Looking for similar items…",
    mostSimilar: "Most similar",
    looksLike: (what: string) => `Looks like: ${what}`,
    count: (n: number) => `${n} ${n === 1 ? "item" : "items"}`,
    retake: "New photo",
    addWords: "Add words…",
    wordsLabel: "Describe it (optional)",
    wordsPlaceholder: "e.g. with eagle, under 500",
    refine: "Refine",
    none: "Nothing in the shop looks like this photo.",
    unavailableTitle: "Photo search is not available right now",
    unavailableBody: "Describe what you are looking for instead:",
    textSearch: "Search",
    failed: "Something went wrong. Please try another photo.",
    notImage: "That file is not a photo we can read. Try a JPEG, PNG or WebP image.",
    tooLarge: "The photo is too large (max 10 MB).",
    match: { very_close: "Very close", close: "Close", similar: "Similar" } as Record<string, string>,
    preview: "Your photo",
  },
  similar: {
    title: "Looks like this",
    intro: "Items that look or read alike.",
  },
} as const;
