import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { searchCopy } from "./_copy";
import { fieldCopyDe } from "./_copy-field.de";

const n = (v: number) => v.toLocaleString("de-DE");

export const searchCopyDe: CopyShape<typeof searchCopy> = {
  field: fieldCopyDe,
  panel: {
    label: "Vorschläge",
    understood: "Verstanden als",
    filters: "Kategorien & Filter",
    items: "Artikel",
    seeAll: (count: number, capped: boolean) => (count === 0 ? "Danach suchen" : count === 1 ? "1 Ergebnis ansehen" : `Alle ${n(count)}${capped ? "+" : ""} Ergebnisse ansehen`),
    loading: "Suche läuft…",
    none: "Keine direkten Treffer — drücken Sie Enter, um trotzdem zu suchen.",
    itemsCount: (count: number) => `${count} Artikel`,
    status: (count: number) => (count === 0 ? "Keine Vorschläge" : `${count} ${count === 1 ? "Vorschlag" : "Vorschläge"} verfügbar. Mit den Pfeiltasten nach oben und unten blättern.`),
    stockCode: (no: number) => `Nr. ${no}`,
    sold: "Verkauft",
  },
  results: {
    eyebrow: "Suche",
    searchedFor: "Wir haben gesucht nach",
    with: "mit",
    searchedFilters: "Wir haben gesucht nach",
    onlyFilters: "Wir zeigen Artikel mit",
    remove: (label: string) => `Filter ${label} entfernen`,
    literal: "Stattdessen wörtlich nach den Begriffen suchen",
    literalOn: (q: string) => `Wörtlich gesucht nach „${q}“.`,
    interpret: "Begriffe von der Suche deuten lassen",
    relaxed: "Nichts passte zu allen erkannten Filtern, daher haben wir nach den Begriffen gesucht.",
    bestFirst: "beste Treffer zuerst",
    nearTitle: "Knapp daneben: nicht alle Filter passen",
    nearBody: (label: string, count: number) => `${count === 1 ? "Dieser Artikel passt" : "Diese Artikel passen"} zu allem außer „${label}“.`,
    nearAll: (count: number) => `Alle ${count} ohne diesen Filter anzeigen`,
    zeroTitle: (q: string) => `Nichts gefunden für „${q}“`,
    didYouMean: "Meinten Sie",
    tryWithout: "Versuchen Sie es ohne",
    browse: "Kategorie durchstöbern",
    wholeShop: "Im ganzen Shop suchen",
    tips: "Prüfen Sie die Schreibweise, verwenden Sie weniger Begriffe oder suchen Sie nach der Artikelnummer (z. B. 50212).",
  },
  photo: {
    title: "Mit Foto suchen",
    close: "Schließen",
    intro: "Finden Sie Artikel, die Ihrem Foto ähneln.",
    drop: "Foto hierher ziehen",
    paste: "oder einfügen (Strg+V / ⌘V)",
    choose: "Foto auswählen",
    take: "Foto aufnehmen",
    privacy: "Ihr Foto wird nicht gespeichert.",
    matched: "Abgeglichen nach Form und Farbe.",
    busy: "Ähnliche Artikel werden gesucht…",
    mostSimilar: "Am ähnlichsten",
    looksLike: (what: string) => `Sieht aus wie: ${what}`,
    count: (count: number) => `${count} Artikel`,
    retake: "Neues Foto",
    addWords: "Begriffe hinzufügen…",
    wordsLabel: "Beschreibung (optional)",
    wordsPlaceholder: "z. B. mit Adler, unter 500",
    refine: "Verfeinern",
    none: "Nichts im Shop sieht diesem Foto ähnlich.",
    unavailableTitle: "Die Fotosuche ist derzeit nicht verfügbar",
    unavailableBody: "Beschreiben Sie stattdessen, wonach Sie suchen:",
    textSearch: "Suchen",
    failed: "Etwas ist schiefgelaufen. Bitte versuchen Sie ein anderes Foto.",
    notImage: "Diese Datei ist kein lesbares Foto. Versuchen Sie ein JPEG-, PNG- oder WebP-Bild.",
    tooLarge: "Das Foto ist zu groß (max. 10 MB).",
    match: { very_close: "Sehr ähnlich", close: "Ähnlich", similar: "Verwandt" },
    preview: "Ihr Foto",
  },
  similar: {
    title: "Ähnliche Stücke",
    intro: "Artikel, die ähnlich aussehen oder ähnlich beschrieben sind.",
  },
};
