import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { searchCopy } from "./_copy";
import { fieldCopyNl } from "./_copy-field.nl";

const n = (v: number) => v.toLocaleString("nl-NL");

export const searchCopyNl: CopyShape<typeof searchCopy> = {
  field: fieldCopyNl,
  panel: {
    label: "Suggesties",
    understood: "Begrepen als",
    filters: "Categorieën & filters",
    items: "Items",
    seeAll: (count: number, capped: boolean) => (count === 0 ? "Hierop zoeken" : count === 1 ? "Bekijk 1 resultaat" : `Bekijk alle ${n(count)}${capped ? "+" : ""} resultaten`),
    loading: "Bezig met zoeken…",
    none: "Geen directe treffers — druk op Enter om toch te zoeken.",
    itemsCount: (count: number) => `${count} ${count === 1 ? "item" : "items"}`,
    status: (count: number) => (count === 0 ? "Geen suggesties" : `${count} ${count === 1 ? "suggestie" : "suggesties"} beschikbaar. Gebruik de pijltjestoetsen omhoog en omlaag om te bladeren.`),
    stockCode: (no: number) => `Nr. ${no}`,
    sold: "Verkocht",
  },
  results: {
    eyebrow: "Zoeken",
    searchedFor: "We zochten naar",
    with: "met",
    searchedFilters: "We zochten naar",
    onlyFilters: "We toonden items met",
    remove: (label: string) => `Filter ${label} verwijderen`,
    literal: "Zoek in plaats daarvan letterlijk op de woorden",
    literalOn: (q: string) => `Letterlijk gezocht naar “${q}”.`,
    interpret: "Laat de zoekfunctie de woorden interpreteren",
    relaxed: "Niets voldeed aan alle filters die we herkenden, dus we hebben op de woorden gezocht.",
    bestFirst: "beste treffers eerst",
    nearTitle: "Bijna, maar niet alle filters komen overeen",
    nearBody: (label: string, count: number) => `${count === 1 ? "Dit item voldoet" : "Deze items voldoen"} aan alles behalve “${label}”.`,
    nearAll: (count: number) => `Toon alle ${count} zonder dit filter`,
    zeroTitle: (q: string) => `Niets gevonden voor “${q}”`,
    didYouMean: "Bedoelde u",
    tryWithout: "Probeer zonder",
    browse: "Bekijk een categorie",
    wholeShop: "Zoek in de hele shop",
    tips: "Controleer de spelling, gebruik minder woorden of zoek op voorraadnummer (bijv. 50212).",
  },
  photo: {
    title: "Zoeken met foto",
    close: "Sluiten",
    intro: "Vind items die op uw foto lijken.",
    drop: "Sleep hier een foto naartoe",
    paste: "of plak er een (Ctrl+V / ⌘V)",
    choose: "Kies foto",
    take: "Maak foto",
    privacy: "Uw foto wordt niet opgeslagen.",
    matched: "Vergeleken op vorm en kleur.",
    busy: "Op zoek naar vergelijkbare items…",
    mostSimilar: "Meest vergelijkbaar",
    looksLike: (what: string) => `Lijkt op: ${what}`,
    count: (count: number) => `${count} ${count === 1 ? "item" : "items"}`,
    retake: "Nieuwe foto",
    addWords: "Woorden toevoegen…",
    wordsLabel: "Beschrijf het (optioneel)",
    wordsPlaceholder: "bijv. met adelaar, onder 500",
    refine: "Verfijnen",
    none: "Niets in de shop lijkt op deze foto.",
    unavailableTitle: "Zoeken met foto is op dit moment niet beschikbaar",
    unavailableBody: "Beschrijf in plaats daarvan wat u zoekt:",
    textSearch: "Zoeken",
    failed: "Er ging iets mis. Probeer een andere foto.",
    notImage: "Dit bestand is geen foto die we kunnen lezen. Probeer een JPEG-, PNG- of WebP-afbeelding.",
    tooLarge: "De foto is te groot (max. 10 MB).",
    match: { very_close: "Zeer dichtbij", close: "Dichtbij", similar: "Vergelijkbaar" },
    preview: "Uw foto",
  },
  similar: {
    title: "Lijkt hierop",
    intro: "Items die er hetzelfde uitzien of vergelijkbaar zijn beschreven.",
  },
};
