/** Screen copy for the CMS pages screens (English). */
export const copy = {
  crumb: "Website",
  title: "Pages",
  list: {
    caption: "Content pages",
    newPage: "New page",
    ensureSystem: "Create missing system pages",
    ensureSystemHint: (n: number) =>
      n === 1 ? "1 system page is missing. Shops need it for the storefront." : `${n} system pages are missing. Shops need them for the storefront.`,
    ensureSystemDone: (keys: string[]) => (keys.length ? `Created ${keys.length} system page${keys.length === 1 ? "" : "s"} as drafts.` : "All system pages already exist."),
    search: "Search title or slug…",
    views: { all: "All", published: "Published", drafts: "Drafts", system: "System pages" },
    columns: { title: "Page", role: "Role", status: "Status", blocks: "Blocks", updated: "Updated", actions: "Actions" },
    published: "Published",
    draft: "Draft",
    duplicate: "Duplicate",
    duplicated: "Page duplicated as a draft.",
    edit: "Edit",
    delete: "Delete",
    deleteTitle: (title: string) => `Delete “${title}”?`,
    deleteBody: "The page and all its blocks are deleted. Menu items that link to it are removed. This cannot be undone.",
    deleted: "Page deleted.",
    systemProtected: "System pages cannot be deleted. Assign the role to another page first if you want to replace it.",
    emptyTitle: "No pages yet",
    emptyBody: "Create the system pages (home, terms, privacy, contact, about) to get started, or add your own page.",
    noMatchTitle: "No pages match",
    noMatchBody: "Try another search or view.",
  },
  create: {
    title: "New page",
    description: "The page starts empty and as a draft. Add blocks in the editor.",
    fieldTitle: "Title",
    fieldSlug: "Slug",
    slugHint: "Leave empty to derive it from the title. The page is served at /slug.",
    submit: "Create page",
    pending: "Creating…",
  },
  roles: {
    HOME: "Home",
    TERMS: "Terms",
    PRIVACY: "Privacy",
    CONTACT: "Contact",
    ABOUT: "About",
  } as Record<string, string>,
  editor: {
    crumb: "Pages",
    settings: "Page settings",
    fieldTitle: "Title",
    fieldSlug: "Slug",
    slugHint: "Lowercase letters, digits and dashes. The page is served at /slug.",
    homeSlugHint: "The home page is always served at /.",
    seoTitle: "SEO title",
    seoTitleHint: "Shown in search results and the browser tab. Leave empty to use the title.",
    seoDescription: "SEO description",
    seoDescriptionHint: "One or two sentences for search results (max 500 characters).",
    published: "Published",
    publishedHint: "Drafts are not visible in the shop.",
    role: "System role",
    roleHint: "Give this page a fixed role in the shop. The page that held the role becomes a regular page.",
    roleNone: "Regular page",
    roleLocked: (role: string) => `This is the ${role} page. A system page keeps its role; assign it to another page to replace this one.`,
    save: "Save settings",
    saving: "Saving…",
    saved: "Page settings saved.",
    view: "View in shop",
    deletePage: "Delete page",
    blocks: "Blocks",
    blocksEmptyTitle: "This page has no blocks yet",
    blocksEmptyBody: "Add a block to start building the page.",
    addBlock: "Add block",
    addBelow: "Add block below",
    preview: "Preview",
    previewNote: "Simplified preview. The shop renders the final design.",
    previewEmpty: "Nothing to preview yet.",
    hiddenTag: "Hidden",
  },
  block: {
    visible: "Visible in shop",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove",
    removeTitle: (label: string) => `Remove the ${label} block?`,
    removeBody: "The block and its content are removed from this page. This cannot be undone.",
    removed: "Block removed.",
    edit: "Edit",
    close: "Close editor",
    save: "Save block",
    saving: "Saving…",
    saved: "Block saved.",
    discard: "Discard changes",
    unsaved: "Unsaved changes",
    invalidTitle: "This block has content that is no longer valid",
    invalidBody: "It is skipped in the shop until it is fixed. Correct the fields below and save.",
    fixFields: "Fix the highlighted fields before saving.",
    heroFirst: "The hero block always stays first.",
  },
  picker: {
    title: "Add a block",
    description: "Pick a block type. It is added with example content you can edit.",
    groups: { text: "Text", media: "Media", shop: "Shop", engagement: "Engagement" } as Record<string, string>,
    heroTaken: "This page already has a hero block (max one, always first).",
    needsNewsletter: "Requires the newsletter module, which is not enabled for this shop.",
    added: (label: string) => `${label} block added.`,
    iconLabel: "Icon",
  },
  fields: {
    title: "Title",
    subtitle: "Subtitle",
    markdown: "Text",
    markdownHint: "Supports **bold**, *italic*, [links](/shop), # headings, - lists and > quotes.",
    markdownPreview: "Text preview",
    quote: "Quote",
    author: "Author",
    text: "Text",
    buttonLabel: "Button label",
    href: "Link",
    hrefHint: "A shop path such as /shop, a full https:// URL or mailto:.",
    image: "Image",
    images: "Images",
    imagePosition: "Image position",
    left: "Left",
    right: "Right",
    cta: "Button",
    ctaToggle: "Show a button",
    link: "Link",
    linkToggle: "Add a link",
    linkLabel: "Label",
    product: "Product",
    categories: "Categories",
    categoriesHint: "Leave all unchecked to show every active top-level category.",
    count: "Number of items",
    countHint: "1 to 24 of the newest active products.",
    unsafeUrl: "Only http(s), mailto and relative links are allowed.",
    faqHint: (n: number, max: number) => `${n} of ${max} questions. Visitors see them as an expandable list; search engines and AI assistants read them as FAQ data.`,
    faqQuestion: (i: number) => `Question ${i}`,
    faqAnswer: "Answer",
    faqAnswerHint: (n: number, max: number) => `${n}/${max}. Markdown: **bold**, *italic*, [links](/shop), - lists.`,
    faqAdd: "Add question",
    faqRemove: (i: number) => `Remove question ${i}`,
    faqMoveUp: (i: number) => `Move question ${i} up`,
    faqMoveDown: (i: number) => `Move question ${i} down`,
  },
  image: {
    choose: "Choose image",
    add: "Add image",
    replace: "Replace",
    remove: "Remove",
    moveLeft: "Move left",
    moveRight: "Move right",
    none: "No image",
    drawerTitle: "Choose an image",
    drawerDescription: "There is no media library yet: pick a product photo, upload an image for this page, or enter a storage key.",
    tabProducts: "Product photos",
    tabUpload: "Upload",
    tabKey: "Storage key",
    search: "Search products by title or stock code",
    searching: "Searching…",
    noResults: "No product photos found.",
    uploadLabel: "Image file",
    uploadHint: "JPEG, PNG, WebP or AVIF, up to 25 MB.",
    uploadSubmit: "Upload and use",
    uploading: "Uploading…",
    tooLarge: "This file is larger than 25 MB. Resize it first.",
    keyLabel: "Storage key",
    keyHint: "For example {shop}/content/{page}/{image}.jpg. It must belong to this shop.",
    keySubmit: "Use this key",
    invalidKey: "Invalid image key.",
    count: (n: number, max: number) => `${n} of ${max}`,
  },
  product: {
    choose: "Choose product",
    change: "Change product",
    clear: "Remove product",
    none: "No product chosen",
    missing: "The chosen product no longer exists.",
    drawerTitle: "Choose a product",
    search: "Search title, SKU or stock code",
    noResults: "No products found.",
    select: "Select",
  },
} as const;
