export const sellCopy = {
  brand: "Fair mode",
  back: "Back to the fair",
  net: {
    synced: "Online · all synced",
    syncing: (n: number) => `Online · syncing ${n} ${n === 1 ? "sale" : "sales"}…`,
    offline: (n: number) => (n ? `Offline · ${n} ${n === 1 ? "sale" : "sales"} waiting to sync` : "Offline · using the saved item list"),
    auth: "Signed out · sign in again to sync",
    signIn: "Sign in",
  },
  today: (n: number, amount: string) => `Today: ${n} sold · ${amount}`,
  notLive: { PREPARING: "This fair hasn't started yet. Start it on the fair page first.", ENDED: "This fair has ended. Queued sales still sync." },
  scan: {
    point: "Point at the QR label on the item",
    noCamera: "Camera scanning isn't available in this browser — type the stock number instead.",
    cameraError: "The camera could not be started. Allow camera access, or type the stock number.",
    typeLabel: "Or type the stock number",
    find: "Find",
    notOnFair: (code: number) => `No. ${code} is not on this fair.`,
    alreadySold: (code: number) => `No. ${code} is already sold.`,
    unavailable: (code: number) => `No. ${code} is not for sale right now.`,
    invalid: "Enter a stock number.",
    onTable: (n: number) => `On the table (${n} ${n === 1 ? "item" : "items"})`,
    hidden: "Hidden in the webshop while the fair runs · back online automatically when you end the fair",
    hiddenSoon: "Hidden in the webshop once you start the fair",
    visible: "Also visible in the webshop while the fair runs",
    ended: "The fair has ended · unsold items are back in the webshop",
  },
  item: {
    listed: (list: string, bought: string | null) => (bought ? `Listed ${list} · bought ${bought}` : `Listed ${list}`),
    price: "Fair price",
    floor: (floor: string, margin: string | null) => (margin ? `Floor you set: ${floor} · margin at this price ${margin}` : `Floor you set: ${floor}`),
    belowFloor: "Below your floor.",
    override: "Sell below the floor anyway",
    paidWith: "Paid with",
    methodHint: "Take the payment on your own card reader or in cash, then confirm here.",
    invoiceHint: "The order stays unpaid until you mark it paid in Orders; the invoice follows then.",
    email: "Buyer e-mail (optional, for the order confirmation and invoice)",
    confirm: (amount: string) => `Paid ${amount} — mark as sold`,
    confirmInvoice: (amount: string) => `Sell on invoice for ${amount}`,
    cancel: "Cancel",
    invalidPrice: "Enter a valid price.",
  },
  sold: {
    title: (code: number) => `Sold — No. ${code}`,
    synced: (n: number) => `Recorded as order #${n}. Removed from the webshop.`,
    queued: "Saved on this device. It syncs as soon as there is a connection.",
    next: "Sell the next item",
  },
  rejected: {
    title: "Needs attention",
    dismiss: "Dismiss",
  },
} as const;
