import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { catalogCopy } from "./_copy";
import { nachLand } from "@/lib/i18n/de-grammar";

export const catalogCopyDe: CopyShape<typeof catalogCopy> = {
  shop: {
    title: "Shop",
    metaTitle: "Alle Artikel im Angebot",
    metaDescription: (shop: string) => `Alle Artikel im Angebot bei ${shop}: Einzelstücke, jedes mit eigener Bestandsnummer, Fotos und Beschreibung.`,
    searchTitle: (q: string) => `Suche: „${q}“`,
  },
  category: {
    metaTitle: (category: string) => `${category} kaufen`,
    metaDescription: (category: string, shop: string) => `${category} bei ${shop} kaufen. Jeder Artikel ist ein Einzelstück, einzeln fotografiert und beschrieben.`,
  },
  facet: {
    title: (value: string) => value,
    intro: (facet: string, value: string) => `Alle Artikel im Angebot mit ${facet} „${value}“.`,
    metaTitle: (facet: string, value: string) => `${value} (${facet}) — Artikel im Angebot`,
    metaDescription: (facet: string, value: string, shop: string) => `${facet}: ${value} — Artikel im Angebot bei ${shop}. Jeder Artikel ist ein Einzelstück, einzeln fotografiert und beschrieben.`,
  },
  archive: {
    title: "Archiv",
    intro: "Stücke, die durch unsere Hände gegangen sind — mit Fotos, Markierungen und Zustand. Nutzen Sie sie als Referenz und lassen Sie sich benachrichtigen, sobald ein ähnliches Stück eintrifft.",
    metaDescription: (shop: string) => `Referenzarchiv der von ${shop} bereits verkauften Artikel: Fotos, Markierungen und Zustand.`,
    categoryTitle: (category: string) => `Verkauft: ${category}`,
    categoryMetaDescription: (category: string, shop: string) => `${category}, bereits verkauft von ${shop} — ein Referenzarchiv mit Fotos, Markierungen und Zustand.`,
    alertTitle: "Suchen Sie so ein Stück?",
    alertBody: "Speichern Sie diese Suche, und wir benachrichtigen Sie, sobald ein ähnliches Stück eingestellt wird.",
    alertButton: "Bei ähnlichen Stücken benachrichtigen",
  },
  filters: {
    heading: "Filter",
    open: "Filter",
    close: "Filter schließen",
    showResults: (n: number) => `${n} ${n === 1 ? "Ergebnis" : "Ergebnisse"} anzeigen`,
    categories: "Kategorien",
    allCategories: "Alle Kategorien",
    price: "Preis",
    priceMin: "Min.",
    priceMax: "Max.",
    applyPrice: "Anwenden",
    clearAll: "Alle entfernen",
    active: "Aktive Filter",
    remove: (label: string) => `Filter entfernen: ${label}`,
    search: (q: string) => `„${q}“`,
    priceRange: (min: string | null, max: string | null) => (min && max ? `${min} – ${max}` : min ? `Ab ${min}` : `Bis ${max}`),
    tags: "Tags",
    showMore: "Mehr anzeigen",
  },
  toolbar: {
    results: (n: number) => `${n.toLocaleString("de-DE")} Artikel`,
    sort: "Sortieren nach",
    sorts: {
      newest: "Neueste",
      oldest: "Älteste",
      price_asc: "Preis: aufsteigend",
      price_desc: "Preis: absteigend",
      featured: "Empfohlen",
      updated: "Zuletzt aktualisiert",
      relevance: "Beste Übereinstimmung",
    },
    archiveNewest: "Zuletzt verkauft",
    apply: "Anwenden",
    view: "Ansicht",
    grid: "Rasteransicht",
    list: "Listenansicht",
  },
  search: { label: "Im Shop suchen", placeholder: "Titel, Beschreibung oder Nummer suchen", submit: "Suchen" },
  empty: {
    title: "Keine Artikel gefunden",
    filtered: "Keine Treffer für diese Filter. Entfernen Sie einen Filter oder setzen Sie alle zurück.",
    none: "Hier gibt es derzeit keine Artikel. Schauen Sie bald wieder vorbei.",
    archiveNone: "Noch keine verkauften Artikel im Archiv.",
    back: "Zurück zum Shop",
  },
  loadMore: "Mehr laden",
  showing: (shown: number, total: number) => `${shown} von ${total} angezeigt`,
  pagedTitle: (title: string, page: number) => `${title} – Seite ${page}`,
  product: {
    stockCode: (n: number) => `Nr. ${n}`,
    status: { available: "Verfügbar", reserved: "Reserviert", sold: "Verkauft" },
    reservedHint: "Jemand hat diesen Artikel im Warenkorb. Wird der Kauf nicht abgeschlossen, ist er wieder verfügbar.",
    soldHint: "Dieser Artikel wurde verkauft. Er bleibt hier als Referenz.",
    soldIn: (month: string) => `Verkauft ${month}`,
    soldBadge: (month: string) => `Verkauft · ${month}`,
    soldFor: "Verkauft für",
    want: {
      title: "Suchen Sie so ein Stück?",
      similar: (n: number) => `${n} ${n === 1 ? "ähnliches Stück" : "ähnliche Stücke"} jetzt im Angebot`,
      next: "Wir benachrichtigen Sie, sobald das nächste eintrifft.",
      nextAfter: "wir benachrichtigen Sie, sobald das nächste eintrifft.",
      alert: "Bei ähnlichem Stück benachrichtigen",
      alertTitle: "Bei ähnlichem Stück benachrichtigen",
      alertIntro: "Dieses Stück ist vergeben, aber ähnliche kommen herein. Wir schreiben Ihnen, sobald eines eingestellt wird.",
      see: (n: number) => (n === 1 ? "Das ähnliche Stück im Angebot ansehen" : `Die ${n} ähnlichen Stücke im Angebot ansehen`),
    },
    priceHidden: "Verkauft",
    sale: "Sale",
    specifications: "Details",
    description: "Beschreibung",
    tags: "Tags",
    shippingFrom: (country: string, price: string) => `Versand ${nachLand(country)} ab ${price}`,
    shippingFree: (country: string) => `Kostenloser Versand ${nachLand(country)}`,
    shippingPickupOnly: (country: string) => `Keine Lieferung nach ${country}; Abholung möglich`,
    shippingNone: (country: string) => `Derzeit kein Versand ${nachLand(country)}`,
    notifyTitle: "Zu spät?",
    notifyBody: "Erhalten Sie eine E-Mail, sobald ein ähnlicher Artikel eintrifft.",
    related: "Das könnte Ihnen auch gefallen",
    noShipping: (country: string) => `Kein Versand ${nachLand(country)} möglich. Die dortigen Vorschriften erlauben den Versand dieses Artikels nicht.`,
    geoBlurred: "Fotos dieses Artikels werden in Ihrem Land nicht angezeigt.",
    restrictedNotice:
      "Dieser Artikel zeigt historische Symbole. Er wird ausschließlich zu historischen und Bildungszwecken angeboten und stellt keinerlei Befürwortung dar.",
    ageRestricted: (age: number) => `Altersbeschränkter Artikel: Sie müssen mindestens ${age} Jahre alt sein, um ihn zu kaufen.`,
    lockedTitle: "Melden Sie sich an, um diesen Artikel zu sehen",
    lockedBody: "Dieser Artikel ist nur für angemeldete Kunden sichtbar.",
    lockedCta: "Anmelden",
    lockedRegister: "Kundenkonto erstellen",
  },
  gallery: {
    label: "Produktfotos",
    open: (n: number, total: number) => `Foto ${n} von ${total} öffnen`,
    thumb: (n: number) => `Foto ${n} anzeigen`,
    prev: "Vorheriges Foto",
    next: "Nächstes Foto",
    close: "Schließen",
    zoomIn: "Vergrößern",
    zoomOut: "Verkleinern",
    reset: "Zoom zurücksetzen",
    counter: (n: number, total: number) => `${n} / ${total}`,
    hint: "Scrollen, zwei Finger spreizen oder doppelklicken zum Zoomen. Ziehen zum Verschieben.",
    noPhoto: "Noch kein Foto",
  },
};
