import type { CopyShape } from "@/lib/i18n/shop-copy";
import type { catalogCopy } from "./_copy";

export const catalogCopyNl: CopyShape<typeof catalogCopy> = {
  shop: {
    title: "Winkel",
    metaTitle: "Alle items te koop",
    metaDescription: (shop: string) => `Bekijk alle items die te koop zijn bij ${shop}: unieke stukken, elk met een eigen voorraadnummer, foto's en beschrijving.`,
    searchTitle: (q: string) => `Zoeken: “${q}”`,
  },
  category: {
    metaTitle: (category: string) => `${category} te koop`,
    metaDescription: (category: string, shop: string) => `${category} te koop bij ${shop}. Elk item is uniek en afzonderlijk gefotografeerd en beschreven.`,
  },
  facet: {
    title: (value: string) => value,
    intro: (facet: string, value: string) => `Alle items te koop met ${facet.toLowerCase()} “${value}”.`,
    metaTitle: (facet: string, value: string) => `${value} (${facet.toLowerCase()}) — items te koop`,
    metaDescription: (facet: string, value: string, shop: string) => `${facet}: ${value} — items te koop bij ${shop}. Elk item is uniek en afzonderlijk gefotografeerd en beschreven.`,
  },
  archive: {
    title: "Archief (verkocht)",
    intro: "Stukken die door onze handen zijn gegaan — met foto's, markeringen en staat. Gebruik ze als referentie en ontvang een melding zodra een vergelijkbaar stuk binnenkomt.",
    metaDescription: (shop: string) => `Referentiearchief van items die eerder door ${shop} zijn verkocht: foto's, markeringen en staat.`,
    categoryTitle: (category: string) => `Verkocht: ${category.toLowerCase()}`,
    categoryMetaDescription: (category: string, shop: string) => `${category} eerder verkocht door ${shop} — een referentiearchief met foto's, markeringen en staat.`,
    alertTitle: "Op zoek naar zo'n stuk?",
    alertBody: "Bewaar deze zoekopdracht en wij laten het u weten zodra een vergelijkbaar stuk online komt.",
    alertButton: "Meld vergelijkbare stukken",
  },
  filters: {
    heading: "Filters",
    open: "Filters",
    close: "Filters sluiten",
    showResults: (n: number) => `Toon ${n} ${n === 1 ? "resultaat" : "resultaten"}`,
    categories: "Categorieën",
    allCategories: "Alle categorieën",
    price: "Prijs",
    priceMin: "Min",
    priceMax: "Max",
    applyPrice: "Toepassen",
    clearAll: "Alles wissen",
    active: "Actieve filters",
    remove: (label: string) => `Filter verwijderen: ${label}`,
    search: (q: string) => `“${q}”`,
    priceRange: (min: string | null, max: string | null) => (min && max ? `${min} – ${max}` : min ? `Vanaf ${min}` : `Tot ${max}`),
    tags: "Tags",
    showMore: "Toon meer",
  },
  toolbar: {
    results: (n: number) => `${n.toLocaleString("nl-NL")} ${n === 1 ? "item" : "items"}`,
    sort: "Sorteren op",
    sorts: {
      newest: "Nieuwste",
      oldest: "Oudste",
      price_asc: "Prijs: laag naar hoog",
      price_desc: "Prijs: hoog naar laag",
      featured: "Uitgelicht",
      updated: "Recent bijgewerkt",
      relevance: "Beste match",
    },
    archiveNewest: "Recent verkocht",
    apply: "Toepassen",
    view: "Weergave",
    grid: "Rasterweergave",
    list: "Lijstweergave",
  },
  search: { label: "Zoeken in de winkel", placeholder: "Zoek op titel, beschrijving of nummer", submit: "Zoeken" },
  empty: {
    title: "Geen items gevonden",
    filtered: "Niets komt overeen met deze filters. Verwijder er een of wis ze allemaal.",
    none: "Er zijn hier op dit moment geen items. Kom binnenkort terug.",
    archiveNone: "Nog geen verkochte items in het archief.",
    back: "Terug naar de winkel",
  },
  loadMore: "Meer laden",
  showing: (shown: number, total: number) => `${shown} van ${total} getoond`,
  pagedTitle: (title: string, page: number) => `${title} – pagina ${page}`,
  product: {
    stockCode: (n: number) => `Nr. ${n}`,
    status: { available: "Te koop", reserved: "Gereserveerd", sold: "Verkocht" },
    reservedHint: "Iemand heeft dit item in de winkelwagen. Als diegene niet afrekent, komt het weer beschikbaar.",
    soldHint: "Dit item is verkocht. Het blijft hier staan als referentie.",
    soldIn: (month: string) => `Verkocht ${month}`,
    soldBadge: (month: string) => `Verkocht · ${month}`,
    soldFor: "Verkocht voor",
    want: {
      title: "Ook zo'n stuk gezocht?",
      similar: (n: number) => `${n} ${n === 1 ? "vergelijkbaar stuk" : "vergelijkbare stukken"} nu te koop`,
      next: "Wij laten het u weten zodra het volgende binnenkomt.",
      nextAfter: "wij laten het u weten zodra het volgende binnenkomt.",
      alert: "Meld mij een vergelijkbaar stuk",
      alertTitle: "Meld mij een vergelijkbaar stuk",
      alertIntro: "Dit stuk is weg, maar er komen vergelijkbare binnen. Wij mailen u zodra er een online staat.",
      see: (n: number) => (n === 1 ? "Bekijk het vergelijkbare stuk dat te koop is" : `Bekijk de ${n} vergelijkbare stukken die te koop zijn`),
    },
    priceHidden: "Verkocht",
    sale: "Sale",
    specifications: "Details",
    description: "Beschrijving",
    tags: "Tags",
    shippingFrom: (country: string, price: string) => `Verzending naar ${country} vanaf ${price}`,
    shippingFree: (country: string) => `Gratis verzending naar ${country}`,
    shippingPickupOnly: (country: string) => `Geen bezorging naar ${country}; afhalen mogelijk`,
    shippingNone: (country: string) => `Momenteel geen verzending naar ${country}`,
    notifyTitle: "Te laat?",
    notifyBody: "Ontvang een e-mail zodra een vergelijkbaar item binnenkomt.",
    related: "Misschien ook interessant",
    noShipping: (country: string) => `Kan niet naar ${country} worden verzonden. De lokale regelgeving staat verzending van dit item daarheen niet toe.`,
    geoBlurred: "Foto's van dit item worden in uw land niet getoond.",
    restrictedNotice:
      "Dit item toont historische symbolen. Het wordt uitsluitend aangeboden voor historische en educatieve doeleinden en drukt geen enkele instemming uit.",
    ageRestricted: (age: number) => `Item met leeftijdsgrens: u moet ${age} jaar of ouder zijn om het te kopen.`,
    lockedTitle: "Log in om dit item te bekijken",
    lockedBody: "Dit item is alleen zichtbaar voor ingelogde klanten.",
    lockedCta: "Inloggen",
    lockedRegister: "Account aanmaken",
  },
  gallery: {
    label: "Productfoto's",
    open: (n: number, total: number) => `Open foto ${n} van ${total}`,
    thumb: (n: number) => `Toon foto ${n}`,
    prev: "Vorige foto",
    next: "Volgende foto",
    close: "Sluiten",
    zoomIn: "Inzoomen",
    zoomOut: "Uitzoomen",
    reset: "Zoom herstellen",
    counter: (n: number, total: number) => `${n} / ${total}`,
    hint: "Scrol, knijp of dubbelklik om te zoomen. Sleep om te verschuiven.",
    noPhoto: "Nog geen foto",
  },
};
