/** English copy for the catalog, product page and archive (multi-language later: same shape per locale). */
export const catalogCopy = {
  shop: {
    title: "Shop",
    metaDescription: (shop: string) => `Browse original items for sale at ${shop}.`,
    searchTitle: (q: string) => `Search: “${q}”`,
  },
  archive: {
    title: "Sold archive",
    intro: "A reference archive of items that have found a new home.",
    metaDescription: (shop: string) => `Reference archive of items previously sold by ${shop}.`,
  },
  filters: {
    heading: "Filters",
    open: "Filters",
    close: "Close filters",
    showResults: (n: number) => `Show ${n} ${n === 1 ? "result" : "results"}`,
    categories: "Categories",
    allCategories: "All categories",
    price: "Price",
    priceMin: "Min",
    priceMax: "Max",
    applyPrice: "Apply",
    clearAll: "Clear all",
    active: "Active filters",
    remove: (label: string) => `Remove filter: ${label}`,
    search: (q: string) => `“${q}”`,
    priceRange: (min: string | null, max: string | null) => (min && max ? `${min} – ${max}` : min ? `From ${min}` : `Up to ${max}`),
    groups: { period: "Period", country: "Country", branch: "Branch", other: "More" } as Record<string, string>,
    showMore: "Show more",
  },
  toolbar: {
    results: (n: number) => `${n.toLocaleString("en-IE")} ${n === 1 ? "item" : "items"}`,
    sort: "Sort by",
    sorts: {
      newest: "Newest",
      oldest: "Oldest",
      price_asc: "Price: low to high",
      price_desc: "Price: high to low",
      featured: "Featured",
      updated: "Recently updated",
    } as Record<string, string>,
    archiveNewest: "Recently sold",
    apply: "Apply",
    view: "Layout",
    grid: "Grid view",
    list: "List view",
  },
  search: { label: "Search the shop", placeholder: "Search title, description or number", submit: "Search" },
  empty: {
    title: "No items found",
    filtered: "Nothing matches these filters. Try removing one or clearing them all.",
    none: "There are no items here right now. Please check back soon.",
    archiveNone: "No sold items in the archive yet.",
    back: "Back to the shop",
  },
  loadMore: "Load more",
  showing: (shown: number, total: number) => `Showing ${shown} of ${total}`,
  product: {
    stockCode: (n: number) => `#${n}`,
    status: { available: "For sale", reserved: "Reserved", sold: "Sold" } as Record<string, string>,
    reservedHint: "Someone has this item in their cart. If they do not check out, it becomes available again.",
    soldHint: "This item has been sold. It stays here as a reference.",
    priceHidden: "Sold",
    sale: "Sale",
    specifications: "Details",
    description: "Description",
    tags: "Tags",
    shippingFrom: (country: string, price: string) => `Shipping to ${country} from ${price}`,
    shippingFree: (country: string) => `Free shipping to ${country}`,
    shippingPickupOnly: (country: string) => `No delivery to ${country}; pickup available`,
    shippingNone: (country: string) => `Currently no shipping to ${country}`,
    provenanceTitle: "Provenance",
    provenanceBody: "Provenance details and a certificate of authenticity will appear here.",
    notifyTitle: "Too late?",
    notifyBody: "Get an e-mail when a similar item comes in.",
    notifyCta: "Notify me",
    notifyComingSoon: "Coming soon",
    related: "You may also like",
    restrictedNotice:
      "This item shows historical symbols. It is offered for historical and educational purposes only and does not express any endorsement.",
    ageRestricted: (age: number) => `Age-restricted item: you must be ${age} or older to buy it.`,
    lockedTitle: "Log in to view this item",
    lockedBody: "This item is only visible to signed-in customers.",
    lockedCta: "Log in",
    lockedRegister: "Create an account",
  },
  gallery: {
    label: "Product photos",
    open: (n: number, total: number) => `Open photo ${n} of ${total}`,
    thumb: (n: number) => `Show photo ${n}`,
    prev: "Previous photo",
    next: "Next photo",
    close: "Close",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    reset: "Reset zoom",
    counter: (n: number, total: number) => `${n} / ${total}`,
    hint: "Scroll, pinch or double-click to zoom. Drag to pan.",
    noPhoto: "No photo yet",
  },
} as const;
