/* Screen copy for the provenance card on the product editor (English UI). */

export const provenanceCardCopy = {
  title: "Provenance & authenticity",
  provenance: {
    label: "Provenance",
    hint: "Public on the product page. Collection history, where and how the item was found, earlier owners. Markdown: **bold**, *italic*, lists, [links](https://…).",
    guaranteed: "Lifetime authenticity guarantee",
    guaranteedHint: "Shows the guarantee on the product page and on certificates issued from now on.",
    save: "Save provenance",
    saving: "Saving…",
    saved: "Provenance saved.",
  },
  documents: {
    heading: "Documents",
    empty: "No documents yet. Add letters, photos of collection labels, a deactivation certificate or historic invoices.",
    file: "File",
    fileHint: "PDF (max 20 MB) or JPEG / PNG / WebP image (max 25 MB). Images are re-encoded and stripped of metadata.",
    title: "Title",
    titleHint: "Optional — defaults to the file name.",
    kind: "Type",
    isPublic: "Show on product page",
    upload: "Add document",
    uploading: "Uploading…",
    uploaded: "Document added.",
    chooseFile: "Choose a file to upload.",
    tooLarge: (mb: number) => `File is larger than ${mb} MB.`,
    unsupported: "Only PDF, JPEG, PNG and WebP files are accepted.",
    open: "Open",
    public: "Public",
    private: "Private",
    madePublic: "Document is now shown on the product page.",
    madePrivate: "Document is now private.",
    delete: "Delete",
    deleteTitle: "Delete this document?",
    deleteBody: (title: string) => `“${title}” is removed permanently.`,
    deleted: "Document deleted.",
    kinds: {
      PROVENANCE: "Provenance",
      DEACTIVATION_CERT: "Deactivation certificate",
      INVOICE_HISTORIC: "Historic invoice",
      OTHER: "Other",
    },
  },
  certificates: {
    heading: "Certificates of authenticity",
    empty: "No certificate issued yet.",
    notAllowed: "Certificates can be issued once the item is for sale, reserved or sold.",
    issue: "Issue certificate",
    issueTitle: "Issue a certificate of authenticity?",
    issueBody:
      "The certificate records the item's current title, specifications, provenance and cover photo. It gets a public verification code and QR code. One valid certificate per item.",
    issued: (code: string) => `Certificate ${code} issued.`,
    pdf: "PDF",
    verify: "Verify page",
    valid: "Valid",
    cardAside: "Certificate issued",
    revoked: "Revoked",
    revoke: "Revoke",
    revokeTitle: "Revoke this certificate?",
    revokeBody: (code: string) => `Verification of ${code} will show “revoked” from now on. This cannot be undone.`,
    reason: "Reason",
    reasonHint: "Internal; never shown publicly.",
    revokedOk: (code: string) => `Certificate ${code} revoked.`,
    issuedBy: (email: string) => `by ${email}`,
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    unauthenticated: "Your session has expired. Sign in again.",
    forbidden: "You do not have access to this product.",
    checkFields: "Check the highlighted fields.",
  },
} as const;
