/* Screen copy for /admin/inventory (English; move to the i18n dictionary when it gets an inventory key). */

export const copy = {
  crumb: "Catalog",
  title: "Inventory",
  newProduct: "New product",
  importProducts: "Import",
  caption: "Products",
  loading: "Loading inventory",
  views: {
    forSale: "For sale",
    error: {
    title: "This page could not be loaded",
    body: "Something went wrong while loading inventory data. Try again; if it keeps happening, reload the page.",
    retry: "Try again",
  },
  inCart: "In cart",
    draft: "Draft",
    sold: "Sold",
    archived: "Archived",
    noPhoto: "No photo",
    all: "All",
  },
  stats: {
    label: "Stock summary",
    forSale: "for sale",
    reserved: "in carts now",
    value: "Value",
    atPrice: "at price",
    atCost: "at cost",
    withoutCost: (n: number) => `${n} without purchase price`,
  },
  search: { label: "Search products", placeholder: "Search title, stock code, SKU…" },
  filters: {
    category: "Category",
    uncategorised: "Uncategorised",
    tag: "Tag",
    purchase: "Purchase",
    importJob: "Import",
    search: "Search",
    priceMin: "Min price",
    priceMax: "Max price",
    priceFrom: "Price from",
    priceTo: "to",
    apply: "Apply",
  },
  columns: {
    product: "Product",
    stockCode: "Stock code",
    status: "Status",
    quantity: "Qty",
    purchasePrice: "Cost",
    price: "Price",
    margin: "Margin",
    published: "Published",
  },
  error: {
    title: "This page could not be loaded",
    body: "Something went wrong while loading inventory data. Try again; if it keeps happening, reload the page.",
    retry: "Try again",
  },
  inCart: "In cart",
  cartExpired: "Cart expired",
  noCategory: "No category",
  empty: {
    title: "No products here",
    filtered: "No products match these filters. Try another view or clear the filters.",
    none: "Add your first product to start building the inventory.",
    view: "Nothing in this view right now.",
  },
  bulk: {
    label: "Bulk actions",
    selected: (n: number) => `${n} selected`,
    clear: "Clear",
    escHint: "Esc to clear",
    status: "Change status",
    statusTitle: (n: number) => `Change the status of ${n} product${n === 1 ? "" : "s"}`,
    statusField: "New status",
    statusHelp: "All or nothing: if one product cannot get the new status, nothing changes.",
    statusBlocked: (n: number) => `${n} of the selected products cannot be put up for sale:`,
    statusApply: "Change status",
    category: "Set category",
    categoryTitle: (n: number) => `Move ${n} product${n === 1 ? "" : "s"} to a category`,
    categoryField: "Category",
    categoryNone: "No category",
    categoryApply: "Move",
    price: "Adjust price",
    priceTitle: (n: number) => `Adjust the price of ${n} product${n === 1 ? "" : "s"}`,
    priceField: "Change",
    priceHint: "Use a negative number to lower prices, e.g. -10. Rounded to whole cents.",
    priceExample: "Example",
    priceApply: "Adjust prices",
    bump: "Bump to top",
    bumpTitle: (n: number) => `Bump ${n} product${n === 1 ? "" : "s"} to the top`,
    bumpBody: "Sets the published date to now, so the products show first in the shop.",
    bumpApply: "Bump to top",
    archive: "Archive",
    archiveTitle: (n: number) => `Archive ${n} product${n === 1 ? "" : "s"}?`,
    archiveBody: "Archived products disappear from the shop and release any cart reservation. You can restore them later by changing the status.",
    archiveApply: "Archive",
  },
  result: {
    status: (n: number) => (n === 0 ? "No changes: the products already had this status." : `Status changed for ${n} product${n === 1 ? "" : "s"}.`),
    category: (n: number) => `Moved ${n} product${n === 1 ? "" : "s"}.`,
    price: (n: number) => `Prices adjusted for ${n} product${n === 1 ? "" : "s"}.`,
    bump: (n: number) => `Bumped ${n} product${n === 1 ? "" : "s"} to the top.`,
    archive: (n: number) => `Archived ${n} product${n === 1 ? "" : "s"}.`,
    failed: "That did not work. Try again.",
    noSelection: "Select at least one product.",
    badPercent: "Enter a percentage between -99.99 and 1000.",
    badStatus: "Choose a status.",
  },
} as const;
