/* Screen copy for /admin/facets (facet taxonomy: facets, value trees, tags → facet). */

const plural = (n: number, one: string, many = `${one}s`) => `${n} ${n === 1 ? one : many}`;

export const copy = {
  crumb: "Catalog",
  title: "Facets",
  loading: "Loading facets",
  tabs: { label: "Facets", values: "Values", convert: "Convert tags" },
  error: {
    title: "This page could not be loaded",
    body: "Something went wrong while loading the facets. Try again; if it keeps happening, reload the page.",
    retry: "Try again",
  },
  empty: {
    title: "No facets yet",
    body: "Facets classify items by period, country, branch, unit, type and maker. Customers filter the shop by them. Start with the standard set and adjust it.",
    seed: "Add standard facets",
    seeding: "Adding…",
  },
  facets: {
    new: "New facet",
    listLabel: "Facets",
    hidden: "Not a filter",
    summary: (values: number, products: number) => `${plural(values, "value")} · ${plural(products, "product")}`,
    edit: "Edit",
    editLabel: (name: string) => `Edit facet ${name}`,
    moveUp: (name: string) => `Move ${name} up`,
    moveDown: (name: string) => `Move ${name} down`,
    addStandard: "Add missing standard facets",
  },
  values: {
    heading: (facet: string) => `Values of ${facet}`,
    new: "New value",
    addChild: "Add child",
    addChildLabel: (name: string) => `Add a value under ${name}`,
    edit: "Edit",
    editLabel: (name: string) => `Edit ${name}`,
    moveUp: (name: string) => `Move ${name} up`,
    moveDown: (name: string) => `Move ${name} down`,
    products: (n: number) => plural(n, "product"),
    viewInShop: "View in shop",
    emptyTitle: "No values yet",
    emptyBody: "Add values such as “WW2” or “Germany”. Values can be nested: Army › Heer — choosing Army in the shop also shows Heer items.",
    legacy: (id: number) => `legacy tag #${id}`,
  },
  facetForm: {
    createTitle: "New facet",
    editTitle: "Edit facet",
    name: "Name",
    kind: "Kind",
    kindHint: "Used for the product page summary (period, country and branch come first).",
    slug: "Slug",
    slugHint: "Used in shop URLs (/shop?f=slug.value). Leave empty to generate it from the name.",
    regenerateSlug: "Regenerate slug from the name",
    isFilterable: "Show as a filter in the shop",
    save: "Save facet",
    create: "Create facet",
    cancel: "Cancel",
    delete: "Delete facet",
    deleteTitle: (name: string) => `Delete “${name}”?`,
    deleteBody: (values: number, products: number) =>
      `This removes ${plural(values, "value")} and their links to ${plural(products, "product")}. Products themselves are not changed.`,
    deleteConfirm: "Delete facet",
  },
  valueForm: {
    createTitle: "New value",
    editTitle: "Edit value",
    name: "Name",
    parent: "Parent",
    root: "None (top level)",
    slug: "Slug",
    slugHint: "Leave empty to generate it from the name.",
    regenerateSlug: "Regenerate slug from the name",
    save: "Save value",
    create: "Create value",
    cancel: "Cancel",
    delete: "Delete",
    deleteTitle: (name: string) => `Delete “${name}”?`,
    deleteBody: (products: number, children: number) =>
      `Its links to ${plural(products, "product")} are removed${children ? `; ${plural(children, "child value")} move up one level` : ""}.`,
    deleteConfirm: "Delete value",
    merge: "Merge into…",
    mergeTitle: (name: string) => `Merge “${name}” into another value`,
    mergeBody: "Its products get the target value, its children move under the target, then this value is deleted.",
    mergeTarget: "Target value",
    mergeConfirm: "Merge",
  },
  convert: {
    heading: "Convert tags to a facet",
    intro:
      "Turns tags into values of a facet: a value with the same name is reused or created, every product of the tag gets the value, and the tag can be deleted afterwards. Old tag links (/shop?tag=…) redirect to the facet filter.",
    tags: "Tags",
    search: "Filter tags…",
    selected: (n: number) => `${n} selected`,
    noTags: "There are no tags.",
    noMatch: "No tag matches.",
    facet: "Target facet",
    parent: "Under value",
    root: "Top level",
    deleteTags: "Delete the tags afterwards",
    deleteTagsHint: "Recommended: the facet replaces them in the shop filters.",
    submit: "Convert",
    pending: "Converting…",
    needTags: "Select at least one tag.",
    needFacet: "Choose a facet.",
    products: (n: number) => plural(n, "product"),
  },
  result: {
    check: "Check the highlighted fields.",
    failed: "That did not work. Try again.",
    facetSaved: "Facet saved.",
    facetCreated: (name: string) => `Facet “${name}” created.`,
    facetDeleted: "Facet deleted.",
    valueSaved: "Value saved.",
    valueCreated: (name: string) => `Value “${name}” created.`,
    valueDeleted: "Value deleted.",
    merged: "Values merged.",
    moved: "Order saved.",
    seeded: (facets: number, values: number) =>
      facets || values ? `Added ${plural(facets, "facet")} and ${plural(values, "value")}.` : "The standard facets are already there.",
    converted: (created: number, reused: number, linked: number, deleted: number) =>
      `${plural(created, "value")} created, ${reused} reused, ${plural(linked, "product link")} added${deleted ? `, ${plural(deleted, "tag")} deleted` : ""}.`,
  },
};
