/* English UI copy of the Quartermaster network pages (docs/network.md). */
export const networkCopy = {
  brand: "Quartermaster",
  brandTag: "Network",
  navLabel: "Network",
  nav: { search: "Search", dealers: "Dealers", forDealers: "For dealers" },
  title: "Original militaria from trusted dealers — one search.",
  metaTitle: "Quartermaster network — original militaria from trusted dealers",
  metaDescription: "Search the stock of independent militaria dealers at once. You buy directly from the dealer, in their own shop.",
  searchLabel: "Search all dealers",
  searchPlaceholder: "Helmet, Feldbluse, Iron Cross…",
  searchButton: "Search",
  stats: (dealers: number, pieces: number) =>
    `${dealers} ${dealers === 1 ? "dealer" : "dealers"} · ${pieces.toLocaleString("en-GB")} ${pieces === 1 ? "piece" : "pieces"} for sale · updated every few minutes`,
  filters: {
    label: "Filters",
    dealer: "Dealer",
    ships: (country: string) => `Ships to ${country}`,
    shipsHint: "Shipping cost shown in the dealer's shop",
    period: "Period",
    country: "Country of origin",
    apply: "Apply filters",
    clear: "Clear filters",
  },
  trust: "You buy directly from the dealer, in their own shop. Every dealer in the network runs a Quartermaster shop.",
  resultsLabel: "Results",
  count: (n: number, dealers: number) => `${n.toLocaleString("en-GB")} ${n === 1 ? "piece" : "pieces"} at ${dealers} ${dealers === 1 ? "dealer" : "dealers"}`,
  countCapped: "500+ pieces",
  searchedFor: (text: string) => `for “${text}”`,
  sort: { label: "Sort", relevance: "Best match", newest: "Newest first" },
  none: "Nothing found. Try fewer words or other filters.",
  empty: "No dealers have joined the network yet.",
  stockCode: (n: number) => `No. ${n}`,
  viewInShop: "View in the dealer's shop →",
  noImage: "No photo",
  prev: "Previous",
  next: "Next",
  pageOf: (page: number, pages: number) => `Page ${page} of ${pages}`,
  photo: {
    button: "Search by photo",
    title: "Search by photo",
    choose: "Choose a photo",
    hint: "A photo of a piece you are looking for. It is only used for this search and never stored.",
    searching: "Searching…",
    results: (n: number) => `${n} ${n === 1 ? "piece looks" : "pieces look"} alike`,
    none: "Nothing in the network looks like this photo.",
    close: "Close",
    error: "Photo search is not available right now.",
  },
  band: {
    title: "Dealer? Your stock, in front of every collector on the network.",
    body: "One switch in your Quartermaster admin. Buyers check out in your own shop, with your prices and your terms.",
    cta: "Join the network",
  },
  dealers: {
    title: "Dealers in the network",
    metaDescription: "Independent militaria dealers whose stock you can search in the Quartermaster network.",
    pieces: (n: number) => `${n.toLocaleString("en-GB")} ${n === 1 ? "piece" : "pieces"}`,
    visit: "Visit shop →",
    all: "All dealers →",
    search: (name: string) => `Search ${name}`,
  },
} as const;
