/* Screen copy for the customer screens (English UI). */

export const customersCopy = {
  crumb: "Sales",
  title: "Customers",
  caption: "Customers",
  search: {
    label: "Search customers",
    placeholder: "Name, email or phone…",
    chip: "Search",
  },
  paidSuffix: (n: number) => ` (${n} paid)`,
  sort: {
    label: "Sort by",
    lastOrder: "Last order",
    name: "Name",
    created: "Newest",
    revenue: "Paid revenue",
  },
  columns: {
    name: "Name",
    email: "Email",
    type: "Account",
    orders: "Orders",
    revenue: "Paid revenue",
    lastOrder: "Last order",
  },
  registered: "Registered",
  guest: "Guest",
  anonymized: "Anonymized",
  noName: "(no name)",
  empty: {
    title: "No customers found",
    body: "Nothing matches this search. Try a different name or email.",
    noneYet: "No customers yet",
    noneYetBody: "Customers are created automatically when someone checks out or registers.",
  },
  error: {
    title: "Customers couldn't be loaded",
    body: "Something went wrong while loading customers. Try again; if it keeps happening, check the server log.",
    retry: "Try again",
  },
};

export const customerCopy = {
  crumb: "Customers",
  anonymizedBanner: "This customer has been anonymized. Personal data is gone; orders and amounts are kept for the bookkeeping.",
  stats: {
    orders: "Orders",
    paidOrders: "Paid orders",
    revenue: "Paid revenue",
    revenueNote: "incl. shipping, paid orders only",
    lastOrder: "Last order",
    since: "Customer since",
    wishlist: "Wishlist items",
  },
  profile: {
    title: "Profile",
    firstName: "First name",
    lastName: "Last name",
    email: "Email",
    emailLocked: "This is the customer's login. They can change it from their account.",
    phone: "Phone",
    notes: "Internal notes",
    notesHint: "Only visible to staff.",
    save: "Save profile",
    saved: "Customer saved.",
  },
  addresses: {
    title: "Address book",
    none: "No saved addresses.",
    default: "Default",
    shipping: "Shipping",
    billing: "Billing",
  },
  orders: {
    title: "Orders",
    caption: "Customer orders",
    number: "Order",
    placed: "Placed",
    payment: "Payment",
    fulfillment: "Fulfillment",
    total: "Total",
    archived: "archived",
    none: "No orders yet.",
  },
  anonymize: {
    title: "Anonymize customer",
    intro: "Use this for a GDPR erasure request (“right to be forgotten”).",
    trigger: "Anonymize…",
    dialogTitle: "Anonymize this customer permanently?",
    confirm: "Anonymize permanently",
    kept: "Kept: the orders with their amounts, items, payment status, shipping country and dates — needed for the bookkeeping and VAT.",
    scrubbed:
      "Scrubbed: name, email, phone and internal notes; the name, email, phone and customer note on every order; all order addresses except the country; stored payment-provider details.",
    deleted: "Deleted: the address book, wishlist, carts and newsletter subscription.",
    notCovered: "Not covered: a linked login account (handle it under Users) and free text in order timeline notes.",
    irreversible: "This cannot be undone.",
    done: "Customer anonymized.",
    already: "This customer was already anonymized.",
  },
  notFound: "This customer no longer exists or belongs to another shop.",
};
