export const copy = {
  crumb: "Sales",
  title: "Alerts",
  runNow: "Run matching now",
  runTitle: "Run matching now?",
  runBody: "Matches every product published in the last 7 days against all active alerts and sends due digests. Items already reported are never sent twice.",
  runConfirm: "Run matching",
  runDone: (created: number, mails: number) => `Matching done: ${created} new matches, ${mails} emails queued.`,
  stats: {
    label: "Alert statistics",
    active: "Active alerts",
    activeNote: (i: number, d: number, w: number) => `${i} instant · ${d} daily · ${w} weekly`,
    pending: "Awaiting confirmation",
    pendingNote: "Guests confirm by email (7 days)",
    deliveries: "Matches sent (30 days)",
    deliveriesNote: "New-arrival items",
    wishlist: "Wishlist alerts (30 days)",
    wishlistNote: (b: number, p: number) => `${b} back available · ${p} price drops`,
  },
  topCategories: "Most watched categories",
  topFacets: "Most watched facets",
  noTop: "No data yet.",
  tabs: { label: "Alert status", active: "Active", pending: "Pending", unsubscribed: "Stopped", all: "All" },
  search: "Search name or email…",
  table: {
    caption: "Saved searches",
    name: "Alert",
    email: "Email",
    frequency: "Frequency",
    status: "Status",
    matches: "Matches",
    created: "Created",
    lastSent: "Last email",
    customer: "Customer",
    guest: "Guest",
    empty: "No alerts here yet",
    emptyBody: "Shoppers create alerts with “Save search” in the catalog and “Notify me” on sold items.",
  },
  frequency: { INSTANT: "Instant", DAILY: "Daily", WEEKLY: "Weekly" },
  status: { active: "Active", pending: "Pending", unsubscribed: "Stopped" },
  disable: "Disable",
  disableTitle: "Disable this alert?",
  disableBody: "Use this for abuse. The person stops receiving it; they can create a new alert later.",
  disableConfirm: "Disable",
  disabled: "Alert disabled.",
  notFound: "This alert is already stopped.",
} as const;
