/* Screen copy for /admin/compliance (rules per country). */

export const copy = {
  crumb: "System",
  title: "Compliance",
  loading: "Loading compliance rules",
  intro:
    "Rules per country: hide items, blur their photos or block shipping, by category or by product flag. The visitor’s country comes from the edge (Cloudflare / proxy geo header); when it is unknown no country rules apply. Checkout checks the shipping country.",
  error: {
    title: "This page could not be loaded",
    body: "Something went wrong while loading the compliance rules. Try again; if it keeps happening, reload the page.",
    retry: "Try again",
  },
  list: {
    caption: "Compliance rules",
    new: "New rule",
    name: "Rule",
    match: "Applies to",
    countries: "Countries",
    action: "Action",
    status: "Status",
    active: "Active",
    inactive: "Off",
    editLabel: (name: string) => `Edit rule ${name}`,
    emptyTitle: "No rules yet",
    emptyBody: "Example: hide items with restricted symbols for Germany and Austria (§86a StGB).",
    more: (n: number) => `+${n}`,
  },
  form: {
    createTitle: "New rule",
    editTitle: "Edit rule",
    name: "Name",
    namePlaceholder: "e.g. §86a — Germany and Austria",
    match: "Applies to",
    category: "Category",
    categoryHint: "Includes all subcategories.",
    countries: "Countries",
    presets: "Presets",
    action: "Action",
    note: "Note",
    noteHint: "Legal basis or internal remark, e.g. “§86a StGB”.",
    isActive: "Active",
    save: "Save rule",
    create: "Create rule",
    cancel: "Cancel",
    delete: "Delete rule",
    deleteTitle: (name: string) => `Delete “${name}”?`,
    deleteBody: "The rule stops applying immediately.",
    deleteConfirm: "Delete rule",
    searchCountries: "Search country or code…",
    selected: (n: number) => `${n} selected`,
    clear: "Clear",
    noCountry: (q: string) => `No country matches “${q}”.`,
  },
  test: {
    heading: "Test",
    intro: "Check how a product is treated for a visitor or shipment in a country (uses the saved rules).",
    country: "Country",
    stockCode: "Stock code",
    submit: "Test",
    pending: "Checking…",
    clear: "No rule applies — shown, photos visible, can be shipped.",
    hidden: "Hidden from the shop",
    blurred: "Photos blurred",
    noShipping: "Cannot be shipped",
    matched: "Matching rules",
  },
  result: {
    check: "Check the highlighted fields.",
    failed: "That did not work. Try again.",
    saved: "Rule saved.",
    created: (name: string) => `Rule “${name}” created.`,
    deleted: "Rule deleted.",
  },
};
